// Code generated by `ubx sdk gen` from google_agentregistry_agentregistry_binding. DO NOT EDIT.
package agentregistry

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AgentregistryBinding_AuthProviderBinding struct {
	// Required. The resource name of the target AuthProvider. Format: * `projects/{project}/locations/{location}/authProviders/{auth_provider}`
	AuthProvider any
	// Optional. The continue URI of the AuthProvider. The URI is used to reauthenticate the user and finalize the managed OAuth flow.
	ContinueUri any
	// Optional. The list of OAuth2 scopes of the AuthProvider.
	Scopes any
}

type AgentregistryBinding_Source struct {
	// The identifier of the source Agent. Format: * `urn:agent:{publisher}:{namespace}:{name}`
	Identifier any
}

var AgentregistryBinding_AuthProviderBindingFields = ubx.FieldMap{
		"AuthProvider": ubx.FieldSpec{WireName: "auth_provider"},
		"ContinueUri": ubx.FieldSpec{WireName: "continue_uri"},
		"Scopes": ubx.FieldSpec{WireName: "scopes"},
	}

var AgentregistryBinding_SourceFields = ubx.FieldMap{
		"Identifier": ubx.FieldSpec{WireName: "identifier"},
	}

type AgentregistryBindingConfig struct {
	// The AuthProvider of the Binding.
	AuthProviderBinding any
	// Output only. Timestamp when this binding was created.
	CreateTime any
	// Optional. User-defined description of a Binding. Can have a maximum length of `2048` characters.
	Description any
	// Optional. User-defined display name for the Binding. Can have a maximum length of `63` characters.
	DisplayName any
	// Required. Identifier. The resource name of the Binding. Format: `projects/{project}/locations/{location}/bindings/{binding}`.
	Name any
	// The source of the Binding.
	Source any
	// The target of the Binding.
	Target any
	// Output only. Timestamp when this binding was last updated.
	UpdateTime any
}

type AgentregistryBindingAttrs struct {
	// The AuthProvider of the Binding.
	AuthProviderBinding any
	// Output only. Timestamp when this binding was created.
	CreateTime any
	// Optional. User-defined description of a Binding. Can have a maximum length of `2048` characters.
	Description any
	// Optional. User-defined display name for the Binding. Can have a maximum length of `63` characters.
	DisplayName any
	// Required. Identifier. The resource name of the Binding. Format: `projects/{project}/locations/{location}/bindings/{binding}`.
	Name any
	// The source of the Binding.
	Source any
	// The target of the Binding.
	Target any
	// Output only. Timestamp when this binding was last updated.
	UpdateTime any
}

var AgentregistryBinding = ubx.ResourceBinding{
	WireType: "google_agentregistry_agentregistry_binding",
	Fields: ubx.FieldMap{
		"AuthProviderBinding": ubx.FieldSpec{
			WireName: "auth_provider_binding",
			Kind: "object",
			Fields: AgentregistryBinding_AuthProviderBindingFields,
		},
		"CreateTime": ubx.FieldSpec{WireName: "create_time"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"DisplayName": ubx.FieldSpec{WireName: "display_name"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Source": ubx.FieldSpec{
			WireName: "source",
			Kind: "object",
			Fields: AgentregistryBinding_SourceFields,
		},
		"Target": ubx.FieldSpec{
			WireName: "target",
			Kind: "object",
			Fields: AgentregistryBinding_SourceFields,
		},
		"UpdateTime": ubx.FieldSpec{WireName: "update_time"},
	},
}
