// Code generated by `ubx sdk gen` from google_dialogflow_playbook. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Playbook_CodeBlock {
  code?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_AudioExportGcsDestination {
  uri?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_DtmfSettings {
  enabled?: boolean | Computed<boolean>;
  endpointingTimeoutDuration?: string | Computed<string>;
  finishDigit?: string | Computed<string>;
  interdigitTimeoutDuration?: string | Computed<string>;
  maxDigits?: number | Computed<number>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_LoggingSettings {
  enableConsentBasedRedaction?: boolean | Computed<boolean>;
  enableInteractionLogging?: boolean | Computed<boolean>;
  enableStackdriverLogging?: boolean | Computed<boolean>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_SpeechSettings {
  endpointerSensitivity?: number | Computed<number>;
  models?: Record<string, string> | Computed<Record<string, string>>;
  noSpeechTimeout?: string | Computed<string>;
  useTimeoutBasedEndpointing?: boolean | Computed<boolean>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings {
  audioExportGcsDestination?: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_AudioExportGcsDestination | Computed<Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_AudioExportGcsDestination>;
  dtmfSettings?: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_DtmfSettings | Computed<Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_DtmfSettings>;
  loggingSettings?: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_LoggingSettings | Computed<Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_LoggingSettings>;
  speechSettings?: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_SpeechSettings | Computed<Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_SpeechSettings>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ConversationSuccess {
  metadata?: Record<string, unknown> | Computed<Record<string, unknown>>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudio_Segments {
  allowPlaybackInterruption?: boolean | Computed<boolean>;
  audio?: string | Computed<string>;
  uri?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudio {
  segments?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudio_Segments[] | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudio_Segments[]>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_OutputAudioText {
  allowPlaybackInterruption?: boolean | Computed<boolean>;
  ssml?: string | Computed<string>;
  text?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_PlayAudio {
  allowPlaybackInterruption?: boolean | Computed<boolean>;
  audioUri?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_TelephonyTransferCall {
  phoneNumber?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_Text {
  allowPlaybackInterruption?: boolean | Computed<boolean>;
  text?: string[] | Computed<string[]>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ToolCall {
  action?: string | Computed<string>;
  inputParameters?: Record<string, unknown> | Computed<Record<string, unknown>>;
  tool?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message {
  channel?: string | Computed<string>;
  conversationSuccess?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ConversationSuccess | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ConversationSuccess>;
  endInteraction?: unknown | Computed<unknown>;
  knowledgeInfoCard?: unknown | Computed<unknown>;
  liveAgentHandoff?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ConversationSuccess | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ConversationSuccess>;
  mixedAudio?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudio | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudio>;
  outputAudioText?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_OutputAudioText | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_OutputAudioText>;
  payload?: Record<string, unknown> | Computed<Record<string, unknown>>;
  playAudio?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_PlayAudio | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_PlayAudio>;
  responseType?: string | Computed<string>;
  telephonyTransferCall?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_TelephonyTransferCall | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_TelephonyTransferCall>;
  text?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_Text | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_Text>;
  toolCall?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ToolCall | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ToolCall>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent {
  additionalCases?: unknown | Computed<unknown>;
  message?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases {
  caseContent?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent[] | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent[]>;
  condition?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases {
  cases?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases[] | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases[]>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_Generators {
  generator?: string | Computed<string>;
  inputParameters?: Record<string, string> | Computed<Record<string, string>>;
  outputParameter?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment_SetParameterActions {
  parameter?: string | Computed<string>;
  value?: unknown | Computed<unknown>;
}

export interface Playbook_Handlers_EventHandler_Fulfillment {
  advancedSettings?: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings | Computed<Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings>;
  codeBlockFunction?: string | Computed<string>;
  conditionalCases?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases[] | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases[]>;
  enableGenerativeFallback?: boolean | Computed<boolean>;
  generators?: Playbook_Handlers_EventHandler_Fulfillment_Generators[] | Computed<Playbook_Handlers_EventHandler_Fulfillment_Generators[]>;
  messages?: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message[] | Computed<Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message[]>;
  returnPartialResponses?: boolean | Computed<boolean>;
  setParameterActions?: Playbook_Handlers_EventHandler_Fulfillment_SetParameterActions[] | Computed<Playbook_Handlers_EventHandler_Fulfillment_SetParameterActions[]>;
  tag?: string | Computed<string>;
  webhook?: string | Computed<string>;
}

export interface Playbook_Handlers_EventHandler {
  condition?: string | Computed<string>;
  event?: string | Computed<string>;
  fulfillment?: Playbook_Handlers_EventHandler_Fulfillment | Computed<Playbook_Handlers_EventHandler_Fulfillment>;
}

export interface Playbook_Handlers_LifecycleHandler {
  condition?: string | Computed<string>;
  fulfillment?: Playbook_Handlers_EventHandler_Fulfillment | Computed<Playbook_Handlers_EventHandler_Fulfillment>;
  lifecycleStage?: string | Computed<string>;
}

export interface Playbook_Handlers {
  eventHandler?: Playbook_Handlers_EventHandler | Computed<Playbook_Handlers_EventHandler>;
  lifecycleHandler?: Playbook_Handlers_LifecycleHandler | Computed<Playbook_Handlers_LifecycleHandler>;
}

export interface Playbook_InputParameterDefinitions_TypeSchema_InlineSchema {
  items?: unknown | Computed<unknown>;
  type?: string | Computed<string>;
}

export interface Playbook_InputParameterDefinitions_TypeSchema_SchemaReference {
  schema?: string | Computed<string>;
  tool?: string | Computed<string>;
}

export interface Playbook_InputParameterDefinitions_TypeSchema {
  inlineSchema?: Playbook_InputParameterDefinitions_TypeSchema_InlineSchema | Computed<Playbook_InputParameterDefinitions_TypeSchema_InlineSchema>;
  schemaReference?: Playbook_InputParameterDefinitions_TypeSchema_SchemaReference | Computed<Playbook_InputParameterDefinitions_TypeSchema_SchemaReference>;
}

export interface Playbook_InputParameterDefinitions {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  type?: string | Computed<string>;
  typeSchema?: Playbook_InputParameterDefinitions_TypeSchema | Computed<Playbook_InputParameterDefinitions_TypeSchema>;
}

export interface Playbook_Instruction_Steps {
  steps?: unknown[] | Computed<unknown[]>;
  text?: string | Computed<string>;
}

export interface Playbook_Instruction {
  guidelines?: string | Computed<string>;
  steps?: Playbook_Instruction_Steps[] | Computed<Playbook_Instruction_Steps[]>;
}

export interface Playbook_LlmModelSettings {
  model?: string | Computed<string>;
  promptText?: string | Computed<string>;
}

const Playbook_CodeBlockFields: FieldMap = {
  code: "code",
};

const Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_AudioExportGcsDestinationFields: FieldMap = {
  uri: "uri",
};

const Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_DtmfSettingsFields: FieldMap = {
  enabled: "enabled",
  endpointingTimeoutDuration: "endpointing_timeout_duration",
  finishDigit: "finish_digit",
  interdigitTimeoutDuration: "interdigit_timeout_duration",
  maxDigits: "max_digits",
};

const Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_LoggingSettingsFields: FieldMap = {
  enableConsentBasedRedaction: "enable_consent_based_redaction",
  enableInteractionLogging: "enable_interaction_logging",
  enableStackdriverLogging: "enable_stackdriver_logging",
};

const Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_SpeechSettingsFields: FieldMap = {
  endpointerSensitivity: "endpointer_sensitivity",
  models: "models",
  noSpeechTimeout: "no_speech_timeout",
  useTimeoutBasedEndpointing: "use_timeout_based_endpointing",
};

const Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettingsFields: FieldMap = {
  audioExportGcsDestination: {
    wireName: "audio_export_gcs_destination",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_AudioExportGcsDestinationFields,
  },
  dtmfSettings: {
    wireName: "dtmf_settings",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_DtmfSettingsFields,
  },
  loggingSettings: {
    wireName: "logging_settings",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_LoggingSettingsFields,
  },
  speechSettings: {
    wireName: "speech_settings",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettings_SpeechSettingsFields,
  },
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ConversationSuccessFields: FieldMap = {
  metadata: "metadata",
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudio_SegmentsFields: FieldMap = {
  allowPlaybackInterruption: "allow_playback_interruption",
  audio: "audio",
  uri: "uri",
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudioFields: FieldMap = {
  segments: {
    wireName: "segments",
    kind: "list",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudio_SegmentsFields,
  },
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_OutputAudioTextFields: FieldMap = {
  allowPlaybackInterruption: "allow_playback_interruption",
  ssml: "ssml",
  text: "text",
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_PlayAudioFields: FieldMap = {
  allowPlaybackInterruption: "allow_playback_interruption",
  audioUri: "audio_uri",
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_TelephonyTransferCallFields: FieldMap = {
  phoneNumber: "phone_number",
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_TextFields: FieldMap = {
  allowPlaybackInterruption: "allow_playback_interruption",
  text: "text",
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ToolCallFields: FieldMap = {
  action: "action",
  inputParameters: "input_parameters",
  tool: "tool",
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_MessageFields: FieldMap = {
  channel: "channel",
  conversationSuccess: {
    wireName: "conversation_success",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ConversationSuccessFields,
  },
  endInteraction: "end_interaction",
  knowledgeInfoCard: "knowledge_info_card",
  liveAgentHandoff: {
    wireName: "live_agent_handoff",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ConversationSuccessFields,
  },
  mixedAudio: {
    wireName: "mixed_audio",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_MixedAudioFields,
  },
  outputAudioText: {
    wireName: "output_audio_text",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_OutputAudioTextFields,
  },
  payload: "payload",
  playAudio: {
    wireName: "play_audio",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_PlayAudioFields,
  },
  responseType: "response_type",
  telephonyTransferCall: {
    wireName: "telephony_transfer_call",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_TelephonyTransferCallFields,
  },
  text: {
    wireName: "text",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_TextFields,
  },
  toolCall: {
    wireName: "tool_call",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_Message_ToolCallFields,
  },
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContentFields: FieldMap = {
  additionalCases: "additional_cases",
  message: {
    wireName: "message",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_MessageFields,
  },
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_CasesFields: FieldMap = {
  caseContent: {
    wireName: "case_content",
    kind: "list",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContentFields,
  },
  condition: "condition",
};

const Playbook_Handlers_EventHandler_Fulfillment_ConditionalCasesFields: FieldMap = {
  cases: {
    wireName: "cases",
    kind: "list",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_CasesFields,
  },
};

const Playbook_Handlers_EventHandler_Fulfillment_GeneratorsFields: FieldMap = {
  generator: "generator",
  inputParameters: "input_parameters",
  outputParameter: "output_parameter",
};

const Playbook_Handlers_EventHandler_Fulfillment_SetParameterActionsFields: FieldMap = {
  parameter: "parameter",
  value: "value",
};

const Playbook_Handlers_EventHandler_FulfillmentFields: FieldMap = {
  advancedSettings: {
    wireName: "advanced_settings",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_Fulfillment_AdvancedSettingsFields,
  },
  codeBlockFunction: "code_block_function",
  conditionalCases: {
    wireName: "conditional_cases",
    kind: "list",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCasesFields,
  },
  enableGenerativeFallback: "enable_generative_fallback",
  generators: {
    wireName: "generators",
    kind: "list",
    fields: Playbook_Handlers_EventHandler_Fulfillment_GeneratorsFields,
  },
  messages: {
    wireName: "messages",
    kind: "list",
    fields: Playbook_Handlers_EventHandler_Fulfillment_ConditionalCases_Cases_CaseContent_MessageFields,
  },
  returnPartialResponses: "return_partial_responses",
  setParameterActions: {
    wireName: "set_parameter_actions",
    kind: "list",
    fields: Playbook_Handlers_EventHandler_Fulfillment_SetParameterActionsFields,
  },
  tag: "tag",
  webhook: "webhook",
};

const Playbook_Handlers_EventHandlerFields: FieldMap = {
  condition: "condition",
  event: "event",
  fulfillment: {
    wireName: "fulfillment",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_FulfillmentFields,
  },
};

const Playbook_Handlers_LifecycleHandlerFields: FieldMap = {
  condition: "condition",
  fulfillment: {
    wireName: "fulfillment",
    kind: "object",
    fields: Playbook_Handlers_EventHandler_FulfillmentFields,
  },
  lifecycleStage: "lifecycle_stage",
};

const Playbook_HandlersFields: FieldMap = {
  eventHandler: {
    wireName: "event_handler",
    kind: "object",
    fields: Playbook_Handlers_EventHandlerFields,
  },
  lifecycleHandler: {
    wireName: "lifecycle_handler",
    kind: "object",
    fields: Playbook_Handlers_LifecycleHandlerFields,
  },
};

const Playbook_InputParameterDefinitions_TypeSchema_InlineSchemaFields: FieldMap = {
  items: "items",
  type: "type",
};

const Playbook_InputParameterDefinitions_TypeSchema_SchemaReferenceFields: FieldMap = {
  schema: "schema",
  tool: "tool",
};

const Playbook_InputParameterDefinitions_TypeSchemaFields: FieldMap = {
  inlineSchema: {
    wireName: "inline_schema",
    kind: "object",
    fields: Playbook_InputParameterDefinitions_TypeSchema_InlineSchemaFields,
  },
  schemaReference: {
    wireName: "schema_reference",
    kind: "object",
    fields: Playbook_InputParameterDefinitions_TypeSchema_SchemaReferenceFields,
  },
};

const Playbook_InputParameterDefinitionsFields: FieldMap = {
  description: "description",
  name: "name",
  type: "type",
  typeSchema: {
    wireName: "type_schema",
    kind: "object",
    fields: Playbook_InputParameterDefinitions_TypeSchemaFields,
  },
};

const Playbook_Instruction_StepsFields: FieldMap = {
  steps: "steps",
  text: "text",
};

const Playbook_InstructionFields: FieldMap = {
  guidelines: "guidelines",
  steps: {
    wireName: "steps",
    kind: "list",
    fields: Playbook_Instruction_StepsFields,
  },
};

const Playbook_LlmModelSettingsFields: FieldMap = {
  model: "model",
  promptText: "prompt_text",
};

export interface PlaybookConfig {
  codeBlock?: Playbook_CodeBlock | Computed<Playbook_CodeBlock>;
  displayName?: string | Computed<string>;
  goal?: string | Computed<string>;
  handlers?: Playbook_Handlers[] | Computed<Playbook_Handlers[]>;
  inputParameterDefinitions?: Playbook_InputParameterDefinitions[] | Computed<Playbook_InputParameterDefinitions[]>;
  instruction?: Playbook_Instruction | Computed<Playbook_Instruction>;
  llmModelSettings?: Playbook_LlmModelSettings | Computed<Playbook_LlmModelSettings>;
  name?: string | Computed<string>;
  outputParameterDefinitions?: Playbook_InputParameterDefinitions[] | Computed<Playbook_InputParameterDefinitions[]>;
  playbookType?: string | Computed<string>;
  referencedTools?: string[] | Computed<string[]>;
}

export interface PlaybookAttrs {
  codeBlock: Playbook_CodeBlock;
  createTime: string;
  displayName: string;
  goal: string;
  handlers: Playbook_Handlers[];
  inlineActions: string[];
  inputParameterDefinitions: Playbook_InputParameterDefinitions[];
  instruction: Playbook_Instruction;
  llmModelSettings: Playbook_LlmModelSettings;
  name: string;
  outputParameterDefinitions: Playbook_InputParameterDefinitions[];
  playbookType: string;
  referencedFlows: string[];
  referencedPlaybooks: string[];
  referencedTools: string[];
  tokenCount: string;
  updateTime: string;
}

export const Playbook: ResourceBinding<PlaybookConfig, PlaybookAttrs> = {
  wireType: "google_dialogflow_playbook",
  fields: {
    codeBlock: {
      wireName: "code_block",
      kind: "object",
      fields: Playbook_CodeBlockFields,
    },
    displayName: "display_name",
    goal: "goal",
    handlers: {
      wireName: "handlers",
      kind: "list",
      fields: Playbook_HandlersFields,
    },
    inputParameterDefinitions: {
      wireName: "input_parameter_definitions",
      kind: "list",
      fields: Playbook_InputParameterDefinitionsFields,
    },
    instruction: {
      wireName: "instruction",
      kind: "object",
      fields: Playbook_InstructionFields,
    },
    llmModelSettings: {
      wireName: "llm_model_settings",
      kind: "object",
      fields: Playbook_LlmModelSettingsFields,
    },
    name: "name",
    outputParameterDefinitions: {
      wireName: "output_parameter_definitions",
      kind: "list",
      fields: Playbook_InputParameterDefinitionsFields,
    },
    playbookType: "playbook_type",
    referencedTools: "referenced_tools",
  },
};
