# Code generated by `ubx sdk gen` from google_apigee_security_profile. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SecurityProfile_Environments:
    attach_time: Any = None
    environment: Any = None

@dataclasses.dataclass
class SecurityProfile_ProfileConfig_Categories:
    abuse: Any = None
    authorization: Any = None
    cors: Any = None
    mediation: Any = None
    mtls: Any = None
    threat: Any = None

@dataclasses.dataclass
class SecurityProfile_ProfileConfig:
    # List of categories of profile config.
    categories: Any = None

@dataclasses.dataclass
class SecurityProfile_ScoringConfigs:
    description: Any = None
    score_path: Any = None
    title: Any = None

_SecurityProfile_EnvironmentsFields = {
    "attach_time": ubx.FieldSpec(wire_name="attach_time"),
    "environment": ubx.FieldSpec(wire_name="environment"),
}

_SecurityProfile_ProfileConfig_CategoriesFields = {
    "abuse": ubx.FieldSpec(wire_name="abuse"),
    "authorization": ubx.FieldSpec(wire_name="authorization"),
    "cors": ubx.FieldSpec(wire_name="cors"),
    "mediation": ubx.FieldSpec(wire_name="mediation"),
    "mtls": ubx.FieldSpec(wire_name="mtls"),
    "threat": ubx.FieldSpec(wire_name="threat"),
}

_SecurityProfile_ProfileConfigFields = {
    "categories": ubx.FieldSpec(
        wire_name="categories",
        kind="list",
        fields=_SecurityProfile_ProfileConfig_CategoriesFields,
    ),
}

_SecurityProfile_ScoringConfigsFields = {
    "description": ubx.FieldSpec(wire_name="description"),
    "score_path": ubx.FieldSpec(wire_name="score_path"),
    "title": ubx.FieldSpec(wire_name="title"),
}

@dataclasses.dataclass
class SecurityProfileConfig:
    # Description of the security profile.
    description: Any = None
    # DEPRECATED: DO NOT USE Display name of the security profile.
    display_name: Any = None
    # List of environments attached to security profile.
    environments: Any = None
    # Output only. Maximum security score that can be generated by this profile.
    max_score: Any = None
    # Output only. Minimum security score that can be generated by this profile.
    min_score: Any = None
    # Immutable. Name of the security profile resource. Format: organizations/{org}/securityProfiles/{profile}
    name: Any = None
    # ProfileConfig defines a set of categories and policies which will be used to compute security score.
    profile_config: Any = None
    # Output only. The time when revision was created.
    revision_create_time: Any = None
    # Output only. Revision ID of the security profile.
    revision_id: Any = None
    # Output only. DEPRECATED: DO NOT USE The time when revision was published. Once published, the security profile revision cannot be updated further and can be attached to environments.
    revision_publish_time: Any = None
    # Output only. The time when revision was updated.
    revision_update_time: Any = None
    # List of profile scoring configs in this revision.
    scoring_configs: Any = None

@dataclasses.dataclass
class SecurityProfileAttrs:
    # Description of the security profile.
    description: Any = None
    # DEPRECATED: DO NOT USE Display name of the security profile.
    display_name: Any = None
    # List of environments attached to security profile.
    environments: Any = None
    # Output only. Maximum security score that can be generated by this profile.
    max_score: Any = None
    # Output only. Minimum security score that can be generated by this profile.
    min_score: Any = None
    # Immutable. Name of the security profile resource. Format: organizations/{org}/securityProfiles/{profile}
    name: Any = None
    # ProfileConfig defines a set of categories and policies which will be used to compute security score.
    profile_config: Any = None
    # Output only. The time when revision was created.
    revision_create_time: Any = None
    # Output only. Revision ID of the security profile.
    revision_id: Any = None
    # Output only. DEPRECATED: DO NOT USE The time when revision was published. Once published, the security profile revision cannot be updated further and can be attached to environments.
    revision_publish_time: Any = None
    # Output only. The time when revision was updated.
    revision_update_time: Any = None
    # List of profile scoring configs in this revision.
    scoring_configs: Any = None

SecurityProfile = ubx.ResourceBinding(
    wire_type="google_apigee_security_profile",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "display_name": ubx.FieldSpec(wire_name="display_name"),
        "environments": ubx.FieldSpec(
            wire_name="environments",
            kind="list",
            fields=_SecurityProfile_EnvironmentsFields,
        ),
        "max_score": ubx.FieldSpec(wire_name="max_score"),
        "min_score": ubx.FieldSpec(wire_name="min_score"),
        "name": ubx.FieldSpec(wire_name="name"),
        "profile_config": ubx.FieldSpec(
            wire_name="profile_config",
            kind="object",
            fields=_SecurityProfile_ProfileConfigFields,
        ),
        "revision_create_time": ubx.FieldSpec(wire_name="revision_create_time"),
        "revision_id": ubx.FieldSpec(wire_name="revision_id"),
        "revision_publish_time": ubx.FieldSpec(wire_name="revision_publish_time"),
        "revision_update_time": ubx.FieldSpec(wire_name="revision_update_time"),
        "scoring_configs": ubx.FieldSpec(
            wire_name="scoring_configs",
            kind="list",
            fields=_SecurityProfile_ScoringConfigsFields,
        ),
    },
)
