// Code generated by `ubx sdk gen` from google_connectors_connectors_connection. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConnectorsConnection_AdminFilters_StringListValues {
  listValues?: string[] | Computed<string[]>;
}

export interface ConnectorsConnection_AdminFilters {
  filterKey?: string | Computed<string>;
  filterType?: string | Computed<string>;
  intValue?: string | Computed<string>;
  stringListValues?: ConnectorsConnection_AdminFilters_StringListValues | Computed<ConnectorsConnection_AdminFilters_StringListValues>;
  stringValue?: string | Computed<string>;
}

export interface ConnectorsConnection_AuthConfig_AdditionalVariables_EncryptionKeyValue {
  kmsKeyName?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue {
  secretVersion?: string | Computed<string>;
}

export interface ConnectorsConnection_AuthConfig_AdditionalVariables {
  boolValue?: boolean | Computed<boolean>;
  encryptionKeyValue?: ConnectorsConnection_AuthConfig_AdditionalVariables_EncryptionKeyValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_EncryptionKeyValue>;
  intValue?: string | Computed<string>;
  key?: string | Computed<string>;
  secretValue?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  stringValue?: string | Computed<string>;
}

export interface ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlow {
  /** Optional. Authorization code to be exchanged for access and refresh tokens. */
  authCode?: string | Computed<string>;
  /** Optional. Auth URL for Authorization Code Flow */
  authUri?: string | Computed<string>;
  /** Optional. Client ID for user-provided OAuth app. */
  clientId?: string | Computed<string>;
  /** Secret provides a reference to entries in Secret Manager. */
  clientSecret?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** Optional. Whether to enable PKCE when the user performs the auth code flow. */
  enablePkce?: boolean | Computed<boolean>;
  /** Optional. PKCE verifier to be used during the auth code exchange. */
  pkceVerifier?: string | Computed<string>;
  /** Optional. Redirect URI to be provided during the auth code exchange. */
  redirectUri?: string | Computed<string>;
  /** Optional. Scopes the connection will request when the user performs the auth code flow. */
  scopes?: string[] | Computed<string[]>;
}

export interface ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlowGoogleManaged {
  /** Optional. Authorization code to be exchanged for access and refresh tokens. */
  authCode?: string | Computed<string>;
  /** Optional. Redirect URI to be provided during the auth code exchange. */
  redirectUri?: string | Computed<string>;
  /** Required. Scopes the connection will request when the user performs the auth code flow. */
  scopes?: string[] | Computed<string[]>;
}

export interface ConnectorsConnection_AuthConfig_Oauth2ClientCredentials {
  /** Optional. The client identifier. */
  clientId?: string | Computed<string>;
  /** Secret provides a reference to entries in Secret Manager. */
  clientSecret?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
}

export interface ConnectorsConnection_AuthConfig_Oauth2JwtBearer_JwtClaims {
  /** Optional. Value for the "aud" claim. */
  audience?: string | Computed<string>;
  /** Optional. Value for the "iss" claim. */
  issuer?: string | Computed<string>;
  /** Optional. Value for the "sub" claim. */
  subject?: string | Computed<string>;
}

export interface ConnectorsConnection_AuthConfig_Oauth2JwtBearer {
  /** Secret provides a reference to entries in Secret Manager. */
  clientKey?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** JWT claims used for the jwt-bearer authorization grant. */
  jwtClaims?: ConnectorsConnection_AuthConfig_Oauth2JwtBearer_JwtClaims | Computed<ConnectorsConnection_AuthConfig_Oauth2JwtBearer_JwtClaims>;
}

export interface ConnectorsConnection_AuthConfig_SshPublicKey {
  /** Optional. Format of SSH Client cert. */
  certType?: string | Computed<string>;
  /** Secret provides a reference to entries in Secret Manager. */
  sshClientCert?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** Secret provides a reference to entries in Secret Manager. */
  sshClientCertPass?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** Optional. The user account used to authenticate. */
  username?: string | Computed<string>;
}

export interface ConnectorsConnection_AuthConfig_UserPassword {
  /** Secret provides a reference to entries in Secret Manager. */
  password?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** Optional. Username. */
  username?: string | Computed<string>;
}

export interface ConnectorsConnection_AuthConfig {
  /** Optional. List containing additional auth configs. */
  additionalVariables?: ConnectorsConnection_AuthConfig_AdditionalVariables[] | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables[]>;
  /** Optional. Identifier key for auth config */
  authKey?: string | Computed<string>;
  /** Optional. The type of authentication configured. */
  authType?: string | Computed<string>;
  /** Parameters to support Oauth 2.0 Auth Code Grant Authentication. See https://www.rfc-editor.org/rfc/rfc6749#section-1.3.1 for more details. */
  oauth2AuthCodeFlow?: ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlow | Computed<ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlow>;
  /** Parameters to support Oauth 2.0 Auth Code Grant Authentication using Google Provided OAuth Client. See https://tools.ietf.org/html/rfc6749#section-1.3.1 for more details. */
  oauth2AuthCodeFlowGoogleManaged?: ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlowGoogleManaged | Computed<ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlowGoogleManaged>;
  /** Parameters to support Oauth 2.0 Client Credentials Grant Authentication. See https://tools.ietf.org/html/rfc6749#section-1.3.4 for more details. */
  oauth2ClientCredentials?: ConnectorsConnection_AuthConfig_Oauth2ClientCredentials | Computed<ConnectorsConnection_AuthConfig_Oauth2ClientCredentials>;
  /** Parameters to support JSON Web Token (JWT) Profile for Oauth 2.0 Authorization Grant based authentication. See https://tools.ietf.org/html/rfc7523 for more details. */
  oauth2JwtBearer?: ConnectorsConnection_AuthConfig_Oauth2JwtBearer | Computed<ConnectorsConnection_AuthConfig_Oauth2JwtBearer>;
  /** Parameters to support Ssh public key Authentication. */
  sshPublicKey?: ConnectorsConnection_AuthConfig_SshPublicKey | Computed<ConnectorsConnection_AuthConfig_SshPublicKey>;
  /** Parameters to support Username and Password Authentication. */
  userPassword?: ConnectorsConnection_AuthConfig_UserPassword | Computed<ConnectorsConnection_AuthConfig_UserPassword>;
}

export interface ConnectorsConnection_BillingConfig {
  /** Output only. Billing category for the connector. */
  billingCategory?: string | Computed<string>;
}

export interface ConnectorsConnection_ConnectorVersionInfraConfig_HpaConfig {
  /** Output only. Percent CPU utilization where HPA triggers autoscaling. */
  cpuUtilizationThreshold?: string | Computed<string>;
  /** Output only. Percent Memory utilization where HPA triggers autoscaling. */
  memoryUtilizationThreshold?: string | Computed<string>;
}

export interface ConnectorsConnection_ConnectorVersionInfraConfig_ResourceLimits {
  /** Output only. CPU limit. */
  cpu?: string | Computed<string>;
  /** Output only. Memory limit. */
  memory?: string | Computed<string>;
}

export interface ConnectorsConnection_ConnectorVersionInfraConfig {
  /** Output only. The window used for ratelimiting runtime requests to connections. */
  connectionRatelimitWindowSeconds?: string | Computed<string>;
  /** Output only. Indicates whether connector is deployed on GKE/CloudRun */
  deploymentModel?: string | Computed<string>;
  /** Output only. Status of the deployment model migration. */
  deploymentModelMigrationState?: string | Computed<string>;
  /** Autoscaling config for connector deployment system metrics. */
  hpaConfig?: ConnectorsConnection_ConnectorVersionInfraConfig_HpaConfig | Computed<ConnectorsConnection_ConnectorVersionInfraConfig_HpaConfig>;
  /** Output only. Max QPS supported for internal requests originating from Connd. */
  internalclientRatelimitThreshold?: string | Computed<string>;
  /** Output only. Max instance request concurrency. */
  maxInstanceRequestConcurrency?: number | Computed<number>;
  /** Output only. Max QPS supported by the connector version before throttling of requests. */
  ratelimitThreshold?: string | Computed<string>;
  /** Resource limits defined for connection pods of a given connector type. */
  resourceLimits?: ConnectorsConnection_ConnectorVersionInfraConfig_ResourceLimits | Computed<ConnectorsConnection_ConnectorVersionInfraConfig_ResourceLimits>;
  /** Resource requests defined for connection pods of a given connector type. */
  resourceRequests?: ConnectorsConnection_ConnectorVersionInfraConfig_ResourceLimits | Computed<ConnectorsConnection_ConnectorVersionInfraConfig_ResourceLimits>;
  /** Output only. The name of shared connector deployment. */
  sharedDeployment?: string | Computed<string>;
  /** Output only. Status of the TLS migration. */
  tlsMigrationState?: string | Computed<string>;
}

export interface ConnectorsConnection_DestinationConfigs_Destinations {
  host?: string | Computed<string>;
  port?: number | Computed<number>;
  serviceAttachment?: string | Computed<string>;
}

export interface ConnectorsConnection_DestinationConfigs {
  destinations?: ConnectorsConnection_DestinationConfigs_Destinations[] | Computed<ConnectorsConnection_DestinationConfigs_Destinations[]>;
  key?: string | Computed<string>;
}

export interface ConnectorsConnection_EventingConfig_DeadLetterConfig {
  /** Optional. Project which has the topic given. */
  projectId?: string | Computed<string>;
  /** Optional. Topic to push events which couldn't be processed. */
  topic?: string | Computed<string>;
}

export interface ConnectorsConnection_EventingConfig_EnrichmentConfig {
  /** Optional. Append ACL to the event. */
  appendAcl?: boolean | Computed<boolean>;
}

export interface ConnectorsConnection_EventingConfig_SslConfig {
  /** Optional. Additional SSL related field values */
  additionalVariables?: ConnectorsConnection_AuthConfig_AdditionalVariables[] | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables[]>;
  /** Optional. Type of Client Cert (PEM/JKS/.. etc.) */
  clientCertType?: string | Computed<string>;
  /** Secret provides a reference to entries in Secret Manager. */
  clientCertificate?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** Secret provides a reference to entries in Secret Manager. */
  clientPrivateKey?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** Secret provides a reference to entries in Secret Manager. */
  clientPrivateKeyPass?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** Secret provides a reference to entries in Secret Manager. */
  privateServerCertificate?: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValue>;
  /** Optional. Type of Server Cert (PEM/JKS/.. etc.) */
  serverCertType?: string | Computed<string>;
  /** Optional. Trust Model of the SSL connection */
  trustModel?: string | Computed<string>;
  /** Optional. Controls the ssl type for the given connector version. */
  type?: string | Computed<string>;
  /** Optional. Bool for enabling SSL */
  useSsl?: boolean | Computed<boolean>;
}

export interface ConnectorsConnection_EventingConfig {
  /** Optional. Additional eventing related field values */
  additionalVariables?: ConnectorsConnection_AuthConfig_AdditionalVariables[] | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables[]>;
  /** Optional. List of allowed event types for the connection. */
  allowedEventTypes?: string[] | Computed<string[]>;
  /** AuthConfig defines details of a authentication type. */
  authConfig?: ConnectorsConnection_AuthConfig | Computed<ConnectorsConnection_AuthConfig>;
  /** Dead Letter configuration details provided by the user. */
  deadLetterConfig?: ConnectorsConnection_EventingConfig_DeadLetterConfig | Computed<ConnectorsConnection_EventingConfig_DeadLetterConfig>;
  /** Data enrichment configuration. */
  enrichmentConfig?: ConnectorsConnection_EventingConfig_EnrichmentConfig | Computed<ConnectorsConnection_EventingConfig_EnrichmentConfig>;
  /** Optional. Enrichment Enabled. */
  enrichmentEnabled?: boolean | Computed<boolean>;
  /** Output only. Ingress endpoint of the event listener. This is used only when private connectivity is enabled. */
  eventsListenerIngressEndpoint?: string | Computed<string>;
  /** Optional. Filter to be applied on the events to be received by the connection. */
  globalEventFilter?: string | Computed<string>;
  /** AuthConfig defines details of a authentication type. */
  listenerAuthConfig?: ConnectorsConnection_AuthConfig | Computed<ConnectorsConnection_AuthConfig>;
  /** Optional. List of projects to be allowlisted for the service attachment created in the tenant project for eventing ingress. */
  privateConnectivityAllowlistedProjects?: string[] | Computed<string[]>;
  /** Optional. Private Connectivity Enabled. */
  privateConnectivityEnabled?: boolean | Computed<boolean>;
  /** Define the Connectors target endpoint. */
  proxyDestinationConfig?: ConnectorsConnection_DestinationConfigs | Computed<ConnectorsConnection_DestinationConfigs>;
  /** Define the Connectors target endpoint. */
  registrationDestinationConfig?: ConnectorsConnection_DestinationConfigs | Computed<ConnectorsConnection_DestinationConfigs>;
  /** SSL Configuration of a connection */
  sslConfig?: ConnectorsConnection_EventingConfig_SslConfig | Computed<ConnectorsConnection_EventingConfig_SslConfig>;
}

export interface ConnectorsConnection_EventingRuntimeData_Status {
  /** Output only. Description of error if State is set to "ERROR". */
  description?: string | Computed<string>;
  /** Output only. State. */
  state?: string | Computed<string>;
}

export interface ConnectorsConnection_EventingRuntimeData_WebhookData {
  /** Output only. Additional webhook related field values. */
  additionalVariables?: ConnectorsConnection_AuthConfig_AdditionalVariables[] | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables[]>;
  /** Output only. Timestamp when the webhook was created. */
  createTime?: string | Computed<string>;
  /** Output only. List of event subscriptions which are using the webhook. */
  eventSubscriptions?: string[] | Computed<string[]>;
  /** Output only. List of event types for the webhook. This is the event types subscribed by the current webhook. */
  eventTypes?: string[] | Computed<string[]>;
  /** Output only. ID to uniquely identify webhook. */
  id?: string | Computed<string>;
  /** Output only. Name of the Webhook */
  name?: string | Computed<string>;
  /** Output only. Next webhook refresh time. Will be null if refresh is not supported. */
  nextRefreshTime?: string | Computed<string>;
  /** Output only. Timestamp when the webhook was last updated. */
  updateTime?: string | Computed<string>;
}

export interface ConnectorsConnection_EventingRuntimeData_WebhookSubscriptions {
  /** Output only. Webhook data. */
  webhookData?: ConnectorsConnection_EventingRuntimeData_WebhookData[] | Computed<ConnectorsConnection_EventingRuntimeData_WebhookData[]>;
}

export interface ConnectorsConnection_EventingRuntimeData {
  /** Output only. Events listener endpoint. The value will populated after provisioning the events listener. */
  eventsListenerEndpoint?: string | Computed<string>;
  /** Output only. Events listener PSC Service attachment. The value will be populated after provisioning the events listener with private connectivity enabled. */
  eventsListenerPscSa?: string | Computed<string>;
  /** EventingStatus indicates the state of eventing. */
  status?: ConnectorsConnection_EventingRuntimeData_Status | Computed<ConnectorsConnection_EventingRuntimeData_Status>;
  /** WebhookData has details of webhook configuration. */
  webhookData?: ConnectorsConnection_EventingRuntimeData_WebhookData | Computed<ConnectorsConnection_EventingRuntimeData_WebhookData>;
  /** WebhookSubscriptions has details of webhook subscriptions. */
  webhookSubscriptions?: ConnectorsConnection_EventingRuntimeData_WebhookSubscriptions | Computed<ConnectorsConnection_EventingRuntimeData_WebhookSubscriptions>;
}

export interface ConnectorsConnection_LockConfig {
  /** Optional. Indicates whether or not the connection is locked. */
  locked?: boolean | Computed<boolean>;
  /** Optional. Describes why a connection is locked. */
  reason?: string | Computed<string>;
}

export interface ConnectorsConnection_LogConfig {
  /** Optional. Enabled represents whether logging is enabled or not for a connection. */
  enabled?: boolean | Computed<boolean>;
  /** Optional. Log configuration level. */
  level?: string | Computed<string>;
}

export interface ConnectorsConnection_NodeConfig {
  /** Optional. Maximum number of nodes in the runtime nodes. */
  maxNodeCount?: number | Computed<number>;
  /** Optional. Minimum number of nodes in the runtime nodes. */
  minNodeCount?: number | Computed<number>;
}

export interface ConnectorsConnection_Status {
  /** Description. */
  description?: string | Computed<string>;
  /** State. */
  state?: string | Computed<string>;
  /** Status provides detailed information for the state. */
  status?: string | Computed<string>;
}

export interface ConnectorsConnection_TrafficShapingConfigs {
  duration?: string | Computed<string>;
  quotaLimit?: string | Computed<string>;
}

const ConnectorsConnection_AdminFilters_StringListValuesFields: FieldMap = {
  listValues: "list_values",
};

const ConnectorsConnection_AdminFiltersFields: FieldMap = {
  filterKey: "filter_key",
  filterType: "filter_type",
  intValue: "int_value",
  stringListValues: {
    wireName: "string_list_values",
    kind: "object",
    fields: ConnectorsConnection_AdminFilters_StringListValuesFields,
  },
  stringValue: "string_value",
};

const ConnectorsConnection_AuthConfig_AdditionalVariables_EncryptionKeyValueFields: FieldMap = {
  kmsKeyName: "kms_key_name",
  type: "type",
};

const ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields: FieldMap = {
  secretVersion: "secret_version",
};

const ConnectorsConnection_AuthConfig_AdditionalVariablesFields: FieldMap = {
  boolValue: "bool_value",
  encryptionKeyValue: {
    wireName: "encryption_key_value",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_EncryptionKeyValueFields,
  },
  intValue: "int_value",
  key: "key",
  secretValue: {
    wireName: "secret_value",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  stringValue: "string_value",
};

const ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlowFields: FieldMap = {
  authCode: "auth_code",
  authUri: "auth_uri",
  clientId: "client_id",
  clientSecret: {
    wireName: "client_secret",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  enablePkce: "enable_pkce",
  pkceVerifier: "pkce_verifier",
  redirectUri: "redirect_uri",
  scopes: "scopes",
};

const ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlowGoogleManagedFields: FieldMap = {
  authCode: "auth_code",
  redirectUri: "redirect_uri",
  scopes: "scopes",
};

const ConnectorsConnection_AuthConfig_Oauth2ClientCredentialsFields: FieldMap = {
  clientId: "client_id",
  clientSecret: {
    wireName: "client_secret",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
};

const ConnectorsConnection_AuthConfig_Oauth2JwtBearer_JwtClaimsFields: FieldMap = {
  audience: "audience",
  issuer: "issuer",
  subject: "subject",
};

const ConnectorsConnection_AuthConfig_Oauth2JwtBearerFields: FieldMap = {
  clientKey: {
    wireName: "client_key",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  jwtClaims: {
    wireName: "jwt_claims",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_Oauth2JwtBearer_JwtClaimsFields,
  },
};

const ConnectorsConnection_AuthConfig_SshPublicKeyFields: FieldMap = {
  certType: "cert_type",
  sshClientCert: {
    wireName: "ssh_client_cert",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  sshClientCertPass: {
    wireName: "ssh_client_cert_pass",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  username: "username",
};

const ConnectorsConnection_AuthConfig_UserPasswordFields: FieldMap = {
  password: {
    wireName: "password",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  username: "username",
};

const ConnectorsConnection_AuthConfigFields: FieldMap = {
  additionalVariables: {
    wireName: "additional_variables",
    kind: "list",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariablesFields,
  },
  authKey: "auth_key",
  authType: "auth_type",
  oauth2AuthCodeFlow: {
    wireName: "oauth2_auth_code_flow",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlowFields,
  },
  oauth2AuthCodeFlowGoogleManaged: {
    wireName: "oauth2_auth_code_flow_google_managed",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_Oauth2AuthCodeFlowGoogleManagedFields,
  },
  oauth2ClientCredentials: {
    wireName: "oauth2_client_credentials",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_Oauth2ClientCredentialsFields,
  },
  oauth2JwtBearer: {
    wireName: "oauth2_jwt_bearer",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_Oauth2JwtBearerFields,
  },
  sshPublicKey: {
    wireName: "ssh_public_key",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_SshPublicKeyFields,
  },
  userPassword: {
    wireName: "user_password",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_UserPasswordFields,
  },
};

const ConnectorsConnection_BillingConfigFields: FieldMap = {
  billingCategory: "billing_category",
};

const ConnectorsConnection_ConnectorVersionInfraConfig_HpaConfigFields: FieldMap = {
  cpuUtilizationThreshold: "cpu_utilization_threshold",
  memoryUtilizationThreshold: "memory_utilization_threshold",
};

const ConnectorsConnection_ConnectorVersionInfraConfig_ResourceLimitsFields: FieldMap = {
  cpu: "cpu",
  memory: "memory",
};

const ConnectorsConnection_ConnectorVersionInfraConfigFields: FieldMap = {
  connectionRatelimitWindowSeconds: "connection_ratelimit_window_seconds",
  deploymentModel: "deployment_model",
  deploymentModelMigrationState: "deployment_model_migration_state",
  hpaConfig: {
    wireName: "hpa_config",
    kind: "object",
    fields: ConnectorsConnection_ConnectorVersionInfraConfig_HpaConfigFields,
  },
  internalclientRatelimitThreshold: "internalclient_ratelimit_threshold",
  maxInstanceRequestConcurrency: "max_instance_request_concurrency",
  ratelimitThreshold: "ratelimit_threshold",
  resourceLimits: {
    wireName: "resource_limits",
    kind: "object",
    fields: ConnectorsConnection_ConnectorVersionInfraConfig_ResourceLimitsFields,
  },
  resourceRequests: {
    wireName: "resource_requests",
    kind: "object",
    fields: ConnectorsConnection_ConnectorVersionInfraConfig_ResourceLimitsFields,
  },
  sharedDeployment: "shared_deployment",
  tlsMigrationState: "tls_migration_state",
};

const ConnectorsConnection_DestinationConfigs_DestinationsFields: FieldMap = {
  host: "host",
  port: "port",
  serviceAttachment: "service_attachment",
};

const ConnectorsConnection_DestinationConfigsFields: FieldMap = {
  destinations: {
    wireName: "destinations",
    kind: "list",
    fields: ConnectorsConnection_DestinationConfigs_DestinationsFields,
  },
  key: "key",
};

const ConnectorsConnection_EventingConfig_DeadLetterConfigFields: FieldMap = {
  projectId: "project_id",
  topic: "topic",
};

const ConnectorsConnection_EventingConfig_EnrichmentConfigFields: FieldMap = {
  appendAcl: "append_acl",
};

const ConnectorsConnection_EventingConfig_SslConfigFields: FieldMap = {
  additionalVariables: {
    wireName: "additional_variables",
    kind: "list",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariablesFields,
  },
  clientCertType: "client_cert_type",
  clientCertificate: {
    wireName: "client_certificate",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  clientPrivateKey: {
    wireName: "client_private_key",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  clientPrivateKeyPass: {
    wireName: "client_private_key_pass",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  privateServerCertificate: {
    wireName: "private_server_certificate",
    kind: "object",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariables_SecretValueFields,
  },
  serverCertType: "server_cert_type",
  trustModel: "trust_model",
  type: "type",
  useSsl: "use_ssl",
};

const ConnectorsConnection_EventingConfigFields: FieldMap = {
  additionalVariables: {
    wireName: "additional_variables",
    kind: "list",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariablesFields,
  },
  allowedEventTypes: "allowed_event_types",
  authConfig: {
    wireName: "auth_config",
    kind: "object",
    fields: ConnectorsConnection_AuthConfigFields,
  },
  deadLetterConfig: {
    wireName: "dead_letter_config",
    kind: "object",
    fields: ConnectorsConnection_EventingConfig_DeadLetterConfigFields,
  },
  enrichmentConfig: {
    wireName: "enrichment_config",
    kind: "object",
    fields: ConnectorsConnection_EventingConfig_EnrichmentConfigFields,
  },
  enrichmentEnabled: "enrichment_enabled",
  eventsListenerIngressEndpoint: "events_listener_ingress_endpoint",
  globalEventFilter: "global_event_filter",
  listenerAuthConfig: {
    wireName: "listener_auth_config",
    kind: "object",
    fields: ConnectorsConnection_AuthConfigFields,
  },
  privateConnectivityAllowlistedProjects: "private_connectivity_allowlisted_projects",
  privateConnectivityEnabled: "private_connectivity_enabled",
  proxyDestinationConfig: {
    wireName: "proxy_destination_config",
    kind: "object",
    fields: ConnectorsConnection_DestinationConfigsFields,
  },
  registrationDestinationConfig: {
    wireName: "registration_destination_config",
    kind: "object",
    fields: ConnectorsConnection_DestinationConfigsFields,
  },
  sslConfig: {
    wireName: "ssl_config",
    kind: "object",
    fields: ConnectorsConnection_EventingConfig_SslConfigFields,
  },
};

const ConnectorsConnection_EventingRuntimeData_StatusFields: FieldMap = {
  description: "description",
  state: "state",
};

const ConnectorsConnection_EventingRuntimeData_WebhookDataFields: FieldMap = {
  additionalVariables: {
    wireName: "additional_variables",
    kind: "list",
    fields: ConnectorsConnection_AuthConfig_AdditionalVariablesFields,
  },
  createTime: "create_time",
  eventSubscriptions: "event_subscriptions",
  eventTypes: "event_types",
  id: "id",
  name: "name",
  nextRefreshTime: "next_refresh_time",
  updateTime: "update_time",
};

const ConnectorsConnection_EventingRuntimeData_WebhookSubscriptionsFields: FieldMap = {
  webhookData: {
    wireName: "webhook_data",
    kind: "list",
    fields: ConnectorsConnection_EventingRuntimeData_WebhookDataFields,
  },
};

const ConnectorsConnection_EventingRuntimeDataFields: FieldMap = {
  eventsListenerEndpoint: "events_listener_endpoint",
  eventsListenerPscSa: "events_listener_psc_sa",
  status: {
    wireName: "status",
    kind: "object",
    fields: ConnectorsConnection_EventingRuntimeData_StatusFields,
  },
  webhookData: {
    wireName: "webhook_data",
    kind: "object",
    fields: ConnectorsConnection_EventingRuntimeData_WebhookDataFields,
  },
  webhookSubscriptions: {
    wireName: "webhook_subscriptions",
    kind: "object",
    fields: ConnectorsConnection_EventingRuntimeData_WebhookSubscriptionsFields,
  },
};

const ConnectorsConnection_LockConfigFields: FieldMap = {
  locked: "locked",
  reason: "reason",
};

const ConnectorsConnection_LogConfigFields: FieldMap = {
  enabled: "enabled",
  level: "level",
};

const ConnectorsConnection_NodeConfigFields: FieldMap = {
  maxNodeCount: "max_node_count",
  minNodeCount: "min_node_count",
};

const ConnectorsConnection_StatusFields: FieldMap = {
  description: "description",
  state: "state",
  status: "status",
};

const ConnectorsConnection_TrafficShapingConfigsFields: FieldMap = {
  duration: "duration",
  quotaLimit: "quota_limit",
};

export interface ConnectorsConnectionConfig {
  /** Optional. Admin filters for the connection. These are used by Gemini Enterprise. */
  adminFilters?: ConnectorsConnection_AdminFilters[] | Computed<ConnectorsConnection_AdminFilters[]>;
  /** Optional. Async operations enabled for the connection. If Async Operations is enabled, Connection allows the customers to initiate async long running operations using the actions API. */
  asyncOperationsEnabled?: boolean | Computed<boolean>;
  /** AuthConfig defines details of a authentication type. */
  authConfig?: ConnectorsConnection_AuthConfig | Computed<ConnectorsConnection_AuthConfig>;
  /** Optional. Auth override enabled for the connection. If Auth Override is enabled, Connection allows the backend service auth to be overridden in the entities/actions API. */
  authOverrideEnabled?: boolean | Computed<boolean>;
  /** Billing config for the connection. */
  billingConfig?: ConnectorsConnection_BillingConfig | Computed<ConnectorsConnection_BillingConfig>;
  /** Optional. Configuration for configuring the connection with an external system. */
  configVariables?: ConnectorsConnection_AuthConfig_AdditionalVariables[] | Computed<ConnectorsConnection_AuthConfig_AdditionalVariables[]>;
  /** Output only. Connection revision. This field is only updated when the connection is created or updated by User. */
  connectionRevision?: string | Computed<string>;
  /** Required. Connector version on which the connection is created. The format is: projects/* /locations/* /providers/* /connectors/* /versions/* Only global location is supported for ConnectorVersion resource. */
  connectorVersion?: string | Computed<string>;
  /** This configuration provides infra configs like rate limit threshold which need to be configurable for every connector version */
  connectorVersionInfraConfig?: ConnectorsConnection_ConnectorVersionInfraConfig | Computed<ConnectorsConnection_ConnectorVersionInfraConfig>;
  /** Output only. Flag to mark the version indicating the launch stage. */
  connectorVersionLaunchStage?: string | Computed<string>;
  /** Output only. Created time. */
  createTime?: string | Computed<string>;
  /** Optional. Description of the resource. */
  description?: string | Computed<string>;
  /** Optional. Configuration of the Connector's destination. Only accepted for Connectors that accepts user defined destination(s). */
  destinationConfigs?: ConnectorsConnection_DestinationConfigs[] | Computed<ConnectorsConnection_DestinationConfigs[]>;
  /** Output only. GCR location where the envoy image is stored. formatted like: gcr.io/{bucketName}/{imageName} */
  envoyImageLocation?: string | Computed<string>;
  /** AuthConfig defines details of a authentication type. */
  euaOauthAuthConfig?: ConnectorsConnection_AuthConfig | Computed<ConnectorsConnection_AuthConfig>;
  /** Eventing Configuration of a connection next: 21 */
  eventingConfig?: ConnectorsConnection_EventingConfig | Computed<ConnectorsConnection_EventingConfig>;
  /** Optional. Eventing enablement type. Will be nil if eventing is not enabled. */
  eventingEnablementType?: string | Computed<string>;
  /** Eventing runtime data has the details related to eventing managed by the system. */
  eventingRuntimeData?: ConnectorsConnection_EventingRuntimeData | Computed<ConnectorsConnection_EventingRuntimeData>;
  /** Optional. Fallback on admin credentials for the connection. If this both auth_override_enabled and fallback_on_admin_credentials are set to true, the connection will use the admin credentials if the dynamic auth header is not present during auth override. */
  fallbackOnAdminCredentials?: boolean | Computed<boolean>;
  /** Output only. The name of the Hostname of the Service Directory service with TLS. */
  host?: string | Computed<string>;
  /** Output only. GCR location where the runtime image is stored. formatted like: gcr.io/{bucketName}/{imageName} */
  imageLocation?: string | Computed<string>;
  /** Output only. Is trusted tester program enabled for the project. */
  isTrustedTester?: boolean | Computed<boolean>;
  /** Optional. Resource labels to represent user-provided metadata. Refer to cloud documentation on labels for more details. https://cloud.google.com/compute/docs/labeling-resources */
  labels?: Record<string, string> | Computed<Record<string, string>>;
  /** Determines whether or no a connection is locked. If locked, a reason must be specified. */
  lockConfig?: ConnectorsConnection_LockConfig | Computed<ConnectorsConnection_LockConfig>;
  /** Log configuration for the connection. */
  logConfig?: ConnectorsConnection_LogConfig | Computed<ConnectorsConnection_LogConfig>;
  /** Output only. Resource name of the Connection. Format: projects/{project}/locations/{location}/connections/{connection} */
  name?: string | Computed<string>;
  /** Node configuration for the connection. */
  nodeConfig?: ConnectorsConnection_NodeConfig | Computed<ConnectorsConnection_NodeConfig>;
  /** Optional. Service account needed for runtime plane to access Google Cloud resources. */
  serviceAccount?: string | Computed<string>;
  /** Output only. The name of the Service Directory service name. Used for Private Harpoon to resolve the ILB address. e.g. "projects/cloud-connectors-e2e-testing/locations/us-central1/namespaces/istio-system/services/istio-ingressgateway-connectors" */
  serviceDirectory?: string | Computed<string>;
  /** SSL Configuration of a connection */
  sslConfig?: ConnectorsConnection_EventingConfig_SslConfig | Computed<ConnectorsConnection_EventingConfig_SslConfig>;
  /** ConnectionStatus indicates the state of the connection. */
  status?: ConnectorsConnection_Status | Computed<ConnectorsConnection_Status>;
  /** Output only. This subscription type enum states the subscription type of the project. */
  subscriptionType?: string | Computed<string>;
  /** Optional. Suspended indicates if a user has suspended a connection or not. */
  suspended?: boolean | Computed<boolean>;
  /** Output only. The name of the Service Directory service with TLS. */
  tlsServiceDirectory?: string | Computed<string>;
  /** Optional. Traffic shaping configuration for the connection. */
  trafficShapingConfigs?: ConnectorsConnection_TrafficShapingConfigs[] | Computed<ConnectorsConnection_TrafficShapingConfigs[]>;
  /** Output only. Updated time. */
  updateTime?: string | Computed<string>;
}

export interface ConnectorsConnectionAttrs {
  /** Optional. Admin filters for the connection. These are used by Gemini Enterprise. */
  adminFilters: ConnectorsConnection_AdminFilters[];
  /** Optional. Async operations enabled for the connection. If Async Operations is enabled, Connection allows the customers to initiate async long running operations using the actions API. */
  asyncOperationsEnabled: boolean;
  /** AuthConfig defines details of a authentication type. */
  authConfig: ConnectorsConnection_AuthConfig;
  /** Optional. Auth override enabled for the connection. If Auth Override is enabled, Connection allows the backend service auth to be overridden in the entities/actions API. */
  authOverrideEnabled: boolean;
  /** Billing config for the connection. */
  billingConfig: ConnectorsConnection_BillingConfig;
  /** Optional. Configuration for configuring the connection with an external system. */
  configVariables: ConnectorsConnection_AuthConfig_AdditionalVariables[];
  /** Output only. Connection revision. This field is only updated when the connection is created or updated by User. */
  connectionRevision: string;
  /** Required. Connector version on which the connection is created. The format is: projects/* /locations/* /providers/* /connectors/* /versions/* Only global location is supported for ConnectorVersion resource. */
  connectorVersion: string;
  /** This configuration provides infra configs like rate limit threshold which need to be configurable for every connector version */
  connectorVersionInfraConfig: ConnectorsConnection_ConnectorVersionInfraConfig;
  /** Output only. Flag to mark the version indicating the launch stage. */
  connectorVersionLaunchStage: string;
  /** Output only. Created time. */
  createTime: string;
  /** Optional. Description of the resource. */
  description: string;
  /** Optional. Configuration of the Connector's destination. Only accepted for Connectors that accepts user defined destination(s). */
  destinationConfigs: ConnectorsConnection_DestinationConfigs[];
  /** Output only. GCR location where the envoy image is stored. formatted like: gcr.io/{bucketName}/{imageName} */
  envoyImageLocation: string;
  /** AuthConfig defines details of a authentication type. */
  euaOauthAuthConfig: ConnectorsConnection_AuthConfig;
  /** Eventing Configuration of a connection next: 21 */
  eventingConfig: ConnectorsConnection_EventingConfig;
  /** Optional. Eventing enablement type. Will be nil if eventing is not enabled. */
  eventingEnablementType: string;
  /** Eventing runtime data has the details related to eventing managed by the system. */
  eventingRuntimeData: ConnectorsConnection_EventingRuntimeData;
  /** Optional. Fallback on admin credentials for the connection. If this both auth_override_enabled and fallback_on_admin_credentials are set to true, the connection will use the admin credentials if the dynamic auth header is not present during auth override. */
  fallbackOnAdminCredentials: boolean;
  /** Output only. The name of the Hostname of the Service Directory service with TLS. */
  host: string;
  /** Output only. GCR location where the runtime image is stored. formatted like: gcr.io/{bucketName}/{imageName} */
  imageLocation: string;
  /** Output only. Is trusted tester program enabled for the project. */
  isTrustedTester: boolean;
  /** Optional. Resource labels to represent user-provided metadata. Refer to cloud documentation on labels for more details. https://cloud.google.com/compute/docs/labeling-resources */
  labels: Record<string, string>;
  /** Determines whether or no a connection is locked. If locked, a reason must be specified. */
  lockConfig: ConnectorsConnection_LockConfig;
  /** Log configuration for the connection. */
  logConfig: ConnectorsConnection_LogConfig;
  /** Output only. Resource name of the Connection. Format: projects/{project}/locations/{location}/connections/{connection} */
  name: string;
  /** Node configuration for the connection. */
  nodeConfig: ConnectorsConnection_NodeConfig;
  /** Optional. Service account needed for runtime plane to access Google Cloud resources. */
  serviceAccount: string;
  /** Output only. The name of the Service Directory service name. Used for Private Harpoon to resolve the ILB address. e.g. "projects/cloud-connectors-e2e-testing/locations/us-central1/namespaces/istio-system/services/istio-ingressgateway-connectors" */
  serviceDirectory: string;
  /** SSL Configuration of a connection */
  sslConfig: ConnectorsConnection_EventingConfig_SslConfig;
  /** ConnectionStatus indicates the state of the connection. */
  status: ConnectorsConnection_Status;
  /** Output only. This subscription type enum states the subscription type of the project. */
  subscriptionType: string;
  /** Optional. Suspended indicates if a user has suspended a connection or not. */
  suspended: boolean;
  /** Output only. The name of the Service Directory service with TLS. */
  tlsServiceDirectory: string;
  /** Optional. Traffic shaping configuration for the connection. */
  trafficShapingConfigs: ConnectorsConnection_TrafficShapingConfigs[];
  /** Output only. Updated time. */
  updateTime: string;
}

export const ConnectorsConnection: ResourceBinding<ConnectorsConnectionConfig, ConnectorsConnectionAttrs> = {
  wireType: "google_connectors_connectors_connection",
  fields: {
    adminFilters: {
      wireName: "admin_filters",
      kind: "list",
      fields: ConnectorsConnection_AdminFiltersFields,
    },
    asyncOperationsEnabled: "async_operations_enabled",
    authConfig: {
      wireName: "auth_config",
      kind: "object",
      fields: ConnectorsConnection_AuthConfigFields,
    },
    authOverrideEnabled: "auth_override_enabled",
    billingConfig: {
      wireName: "billing_config",
      kind: "object",
      fields: ConnectorsConnection_BillingConfigFields,
    },
    configVariables: {
      wireName: "config_variables",
      kind: "list",
      fields: ConnectorsConnection_AuthConfig_AdditionalVariablesFields,
    },
    connectionRevision: "connection_revision",
    connectorVersion: "connector_version",
    connectorVersionInfraConfig: {
      wireName: "connector_version_infra_config",
      kind: "object",
      fields: ConnectorsConnection_ConnectorVersionInfraConfigFields,
    },
    connectorVersionLaunchStage: "connector_version_launch_stage",
    createTime: "create_time",
    description: "description",
    destinationConfigs: {
      wireName: "destination_configs",
      kind: "list",
      fields: ConnectorsConnection_DestinationConfigsFields,
    },
    envoyImageLocation: "envoy_image_location",
    euaOauthAuthConfig: {
      wireName: "eua_oauth_auth_config",
      kind: "object",
      fields: ConnectorsConnection_AuthConfigFields,
    },
    eventingConfig: {
      wireName: "eventing_config",
      kind: "object",
      fields: ConnectorsConnection_EventingConfigFields,
    },
    eventingEnablementType: "eventing_enablement_type",
    eventingRuntimeData: {
      wireName: "eventing_runtime_data",
      kind: "object",
      fields: ConnectorsConnection_EventingRuntimeDataFields,
    },
    fallbackOnAdminCredentials: "fallback_on_admin_credentials",
    host: "host",
    imageLocation: "image_location",
    isTrustedTester: "is_trusted_tester",
    labels: "labels",
    lockConfig: {
      wireName: "lock_config",
      kind: "object",
      fields: ConnectorsConnection_LockConfigFields,
    },
    logConfig: {
      wireName: "log_config",
      kind: "object",
      fields: ConnectorsConnection_LogConfigFields,
    },
    name: "name",
    nodeConfig: {
      wireName: "node_config",
      kind: "object",
      fields: ConnectorsConnection_NodeConfigFields,
    },
    serviceAccount: "service_account",
    serviceDirectory: "service_directory",
    sslConfig: {
      wireName: "ssl_config",
      kind: "object",
      fields: ConnectorsConnection_EventingConfig_SslConfigFields,
    },
    status: {
      wireName: "status",
      kind: "object",
      fields: ConnectorsConnection_StatusFields,
    },
    subscriptionType: "subscription_type",
    suspended: "suspended",
    tlsServiceDirectory: "tls_service_directory",
    trafficShapingConfigs: {
      wireName: "traffic_shaping_configs",
      kind: "list",
      fields: ConnectorsConnection_TrafficShapingConfigsFields,
    },
    updateTime: "update_time",
  },
};
