// Code generated by `ubx sdk gen` from google_deploymentmanager_v2beta_type_provider. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptions_Diagnostics {
  field?: string | Computed<string>;
  level?: string | Computed<string>;
}

export interface V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptions {
  diagnostics?: V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptions_Diagnostics[] | Computed<V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptions_Diagnostics[]>;
  failCondition?: string | Computed<string>;
  finishCondition?: string | Computed<string>;
  pollingLink?: string | Computed<string>;
  targetLink?: string | Computed<string>;
}

export interface V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions {
  methodMatch?: string | Computed<string>;
  pollingOptions?: V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptions | Computed<V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptions>;
}

export interface V2betaTypeProvider_CollectionOverrides_Options_InputMappings {
  fieldName?: string | Computed<string>;
  location?: string | Computed<string>;
  methodMatch?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface V2betaTypeProvider_CollectionOverrides_Options_ValidationOptions {
  schemaValidation?: string | Computed<string>;
  undeclaredProperties?: string | Computed<string>;
}

export interface V2betaTypeProvider_CollectionOverrides_Options {
  asyncOptions?: V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions[] | Computed<V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions[]>;
  inputMappings?: V2betaTypeProvider_CollectionOverrides_Options_InputMappings[] | Computed<V2betaTypeProvider_CollectionOverrides_Options_InputMappings[]>;
  validationOptions?: V2betaTypeProvider_CollectionOverrides_Options_ValidationOptions | Computed<V2betaTypeProvider_CollectionOverrides_Options_ValidationOptions>;
  virtualProperties?: string | Computed<string>;
}

export interface V2betaTypeProvider_CollectionOverrides {
  collection?: string | Computed<string>;
  options?: V2betaTypeProvider_CollectionOverrides_Options | Computed<V2betaTypeProvider_CollectionOverrides_Options>;
}

export interface V2betaTypeProvider_Credential_BasicAuth {
  password?: string | Computed<string>;
  user?: string | Computed<string>;
}

export interface V2betaTypeProvider_Credential_ServiceAccount {
  /** The IAM service account email address like test@myproject.iam.gserviceaccount.com */
  email?: string | Computed<string>;
}

export interface V2betaTypeProvider_Credential {
  /** Basic Auth used as a credential. */
  basicAuth?: V2betaTypeProvider_Credential_BasicAuth | Computed<V2betaTypeProvider_Credential_BasicAuth>;
  /** Service Account used as a credential. */
  serviceAccount?: V2betaTypeProvider_Credential_ServiceAccount | Computed<V2betaTypeProvider_Credential_ServiceAccount>;
  /** Specify to use the project default credential, only supported by Deployment. */
  useProjectDefault?: boolean | Computed<boolean>;
}

export interface V2betaTypeProvider_Labels {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation_Error_Errors_DebugInfo {
  detail?: string | Computed<string>;
  stackEntries?: string[] | Computed<string[]>;
}

export interface V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_ErrorInfo {
  domain?: string | Computed<string>;
  metadatas?: Record<string, string> | Computed<Record<string, string>>;
  reason?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_Help_Links {
  description?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_Help {
  links?: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_Help_Links[] | Computed<V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_Help_Links[]>;
}

export interface V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_LocalizedMessage {
  locale?: string | Computed<string>;
  message?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_QuotaInfo {
  dimensions?: Record<string, string> | Computed<Record<string, string>>;
  futureLimit?: number | Computed<number>;
  limit?: number | Computed<number>;
  limitName?: string | Computed<string>;
  metricName?: string | Computed<string>;
  rolloutStatus?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation_Error_Errors_ErrorDetails {
  errorInfo?: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_ErrorInfo | Computed<V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_ErrorInfo>;
  help?: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_Help | Computed<V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_Help>;
  localizedMessage?: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_LocalizedMessage | Computed<V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_LocalizedMessage>;
  quotaInfo?: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_QuotaInfo | Computed<V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_QuotaInfo>;
}

export interface V2betaTypeProvider_Operation_Error_Errors {
  arguments?: string[] | Computed<string[]>;
  code?: string | Computed<string>;
  debugInfo?: V2betaTypeProvider_Operation_Error_Errors_DebugInfo | Computed<V2betaTypeProvider_Operation_Error_Errors_DebugInfo>;
  errorDetails?: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails[] | Computed<V2betaTypeProvider_Operation_Error_Errors_ErrorDetails[]>;
  location?: string | Computed<string>;
  message?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation_Error {
  /** [Output Only] The array of errors encountered while processing this operation. */
  errors?: V2betaTypeProvider_Operation_Error_Errors[] | Computed<V2betaTypeProvider_Operation_Error_Errors[]>;
}

export interface V2betaTypeProvider_Operation_FirewallPolicyRuleOperationMetadata {
  /** The priority allocated for the firewall policy rule if query parameters specified minPriority/maxPriority. */
  allocatedPriority?: number | Computed<number>;
}

export interface V2betaTypeProvider_Operation_GetVersionOperationMetadata_InlineSbomInfo {
  /** SBOM versions currently applied to the resource. The key is the component name and the value is the version. */
  currentComponentVersions?: Record<string, string> | Computed<Record<string, string>>;
  /** SBOM versions scheduled for the next maintenance. The key is the component name and the value is the version. */
  targetComponentVersions?: Record<string, string> | Computed<Record<string, string>>;
}

export interface V2betaTypeProvider_Operation_GetVersionOperationMetadata {
  inlineSbomInfo?: V2betaTypeProvider_Operation_GetVersionOperationMetadata_InlineSbomInfo | Computed<V2betaTypeProvider_Operation_GetVersionOperationMetadata_InlineSbomInfo>;
}

export interface V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadata_PerLocationStatus {
  createdVmCount?: number | Computed<number>;
  deletedVmCount?: number | Computed<number>;
  failedToCreateVmCount?: number | Computed<number>;
  status?: string | Computed<string>;
  targetVmCount?: number | Computed<number>;
}

export interface V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadata {
  /** [Output Only] The machine type of the VMs that were created used internally only by KCP flex bulk insert. */
  machineType?: string | Computed<string>;
  /** Status information per location (location name is key). Example key: zones/us-central1-a */
  perLocationStatus?: Record<string, V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadata_PerLocationStatus> | Computed<Record<string, V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadata_PerLocationStatus>>;
}

export interface V2betaTypeProvider_Operation_SetAutoscalerLinkOperationMetadata {
  /** List of zonal IGM IDs part of the RMIG. */
  zonalIgmIds?: string[] | Computed<string[]>;
  /** Map of zone to an ID of the zonal IGM belonging to the RMIG. */
  zoneToIgmIds?: Record<string, string> | Computed<Record<string, string>>;
}

export interface V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperations_Error {
  code?: number | Computed<number>;
  details?: Record<string, unknown>[] | Computed<Record<string, unknown>[]>;
  message?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperations {
  error?: V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperations_Error | Computed<V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperations_Error>;
  state?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata {
  /** [Output Only] The client operation id. */
  clientOperationId?: string | Computed<string>;
  /** [Output Only] Status information per location (location name is key). Example key: zones/us-central1-a */
  perLocationOperations?: Record<string, V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperations> | Computed<Record<string, V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperations>>;
}

export interface V2betaTypeProvider_Operation_Warnings {
  code?: string | Computed<string>;
  data?: V2betaTypeProvider_Labels[] | Computed<V2betaTypeProvider_Labels[]>;
  message?: string | Computed<string>;
}

export interface V2betaTypeProvider_Operation {
  /** [Output Only] The value of `requestId` if you provided it in the request. Not present otherwise. */
  clientOperationId?: string | Computed<string>;
  /** [Deprecated] This field is deprecated. */
  creationTimestamp?: string | Computed<string>;
  /** [Output Only] A textual description of the operation, which is set when the operation is created. */
  description?: string | Computed<string>;
  /** [Output Only] The time that this operation was completed. This value is in RFC3339 text format. */
  endTime?: string | Computed<string>;
  /** [Output Only] If errors are generated during processing of the operation, this field will be populated. */
  error?: V2betaTypeProvider_Operation_Error | Computed<V2betaTypeProvider_Operation_Error>;
  firewallPolicyRuleOperationMetadata?: V2betaTypeProvider_Operation_FirewallPolicyRuleOperationMetadata | Computed<V2betaTypeProvider_Operation_FirewallPolicyRuleOperationMetadata>;
  getVersionOperationMetadata?: V2betaTypeProvider_Operation_GetVersionOperationMetadata | Computed<V2betaTypeProvider_Operation_GetVersionOperationMetadata>;
  /** [Output Only] If the operation fails, this field contains the HTTP error message that was returned, such as `NOT FOUND`. */
  httpErrorMessage?: string | Computed<string>;
  /** [Output Only] If the operation fails, this field contains the HTTP error status code that was returned. For example, a `404` means the resource was not found. */
  httpErrorStatusCode?: number | Computed<number>;
  /** [Output Only] The unique identifier for the operation. This identifier is defined by the server. */
  id?: string | Computed<string>;
  /** [Output Only] The time that this operation was requested. This value is in RFC3339 text format. */
  insertTime?: string | Computed<string>;
  instancesBulkInsertOperationMetadata?: V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadata | Computed<V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadata>;
  /** Output only. [Output Only] Type of the resource. Always `compute#operation` for Operation resources. */
  kind?: string | Computed<string>;
  /** [Output Only] Name of the operation. */
  name?: string | Computed<string>;
  /** Output only. [Output Only] An ID that represents a group of operations, such as when a group of operations results from a `bulkInsert` API request. */
  operationGroupId?: string | Computed<string>;
  /** [Output Only] The type of operation, such as `insert`, `update`, or `delete`, and so on. */
  operationType?: string | Computed<string>;
  /** [Output Only] An optional progress indicator that ranges from 0 to 100. There is no requirement that this be linear or support any granularity of operations. This should not be used to guess when the operation will be complete. This number should monotonically increase as the operation progresses. */
  progress?: number | Computed<number>;
  /** [Output Only] The URL of the region where the operation resides. Only applicable when performing regional operations. */
  region?: string | Computed<string>;
  /** [Output Only] Server-defined URL for the resource. */
  selfLink?: string | Computed<string>;
  /** Output only. [Output Only] Server-defined URL for this resource with the resource id. */
  selfLinkWithId?: string | Computed<string>;
  setAutoscalerLinkOperationMetadata?: V2betaTypeProvider_Operation_SetAutoscalerLinkOperationMetadata | Computed<V2betaTypeProvider_Operation_SetAutoscalerLinkOperationMetadata>;
  setCommonInstanceMetadataOperationMetadata?: V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata | Computed<V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata>;
  /** [Output Only] The time that this operation was started by the server. This value is in RFC3339 text format. */
  startTime?: string | Computed<string>;
  /** [Output Only] The status of the operation, which can be one of the following: `PENDING`, `RUNNING`, or `DONE`. */
  status?: string | Computed<string>;
  /** [Output Only] An optional textual description of the current status of the operation. */
  statusMessage?: string | Computed<string>;
  /** [Output Only] The unique target ID, which identifies a specific incarnation of the target resource. */
  targetId?: string | Computed<string>;
  /** [Output Only] The URL of the resource that the operation modifies. For operations related to creating a snapshot, this points to the disk that the snapshot was created from. */
  targetLink?: string | Computed<string>;
  /** [Output Only] User who requested the operation, for example: `user@example.com` or `alice_smith_identifier (global/workforcePools/example-com-us-employees)`. */
  user?: string | Computed<string>;
  /** [Output Only] If warning messages are generated during processing of the operation, this field will be populated. */
  warnings?: V2betaTypeProvider_Operation_Warnings[] | Computed<V2betaTypeProvider_Operation_Warnings[]>;
  /** [Output Only] The URL of the zone where the operation resides. Only applicable when performing per-zone operations. */
  zone?: string | Computed<string>;
}

const V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptions_DiagnosticsFields: FieldMap = {
  field: "field",
  level: "level",
};

const V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptionsFields: FieldMap = {
  diagnostics: {
    wireName: "diagnostics",
    kind: "list",
    fields: V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptions_DiagnosticsFields,
  },
  failCondition: "fail_condition",
  finishCondition: "finish_condition",
  pollingLink: "polling_link",
  targetLink: "target_link",
};

const V2betaTypeProvider_CollectionOverrides_Options_AsyncOptionsFields: FieldMap = {
  methodMatch: "method_match",
  pollingOptions: {
    wireName: "polling_options",
    kind: "object",
    fields: V2betaTypeProvider_CollectionOverrides_Options_AsyncOptions_PollingOptionsFields,
  },
};

const V2betaTypeProvider_CollectionOverrides_Options_InputMappingsFields: FieldMap = {
  fieldName: "field_name",
  location: "location",
  methodMatch: "method_match",
  value: "value",
};

const V2betaTypeProvider_CollectionOverrides_Options_ValidationOptionsFields: FieldMap = {
  schemaValidation: "schema_validation",
  undeclaredProperties: "undeclared_properties",
};

const V2betaTypeProvider_CollectionOverrides_OptionsFields: FieldMap = {
  asyncOptions: {
    wireName: "async_options",
    kind: "list",
    fields: V2betaTypeProvider_CollectionOverrides_Options_AsyncOptionsFields,
  },
  inputMappings: {
    wireName: "input_mappings",
    kind: "list",
    fields: V2betaTypeProvider_CollectionOverrides_Options_InputMappingsFields,
  },
  validationOptions: {
    wireName: "validation_options",
    kind: "object",
    fields: V2betaTypeProvider_CollectionOverrides_Options_ValidationOptionsFields,
  },
  virtualProperties: "virtual_properties",
};

const V2betaTypeProvider_CollectionOverridesFields: FieldMap = {
  collection: "collection",
  options: {
    wireName: "options",
    kind: "object",
    fields: V2betaTypeProvider_CollectionOverrides_OptionsFields,
  },
};

const V2betaTypeProvider_Credential_BasicAuthFields: FieldMap = {
  password: "password",
  user: "user",
};

const V2betaTypeProvider_Credential_ServiceAccountFields: FieldMap = {
  email: "email",
};

const V2betaTypeProvider_CredentialFields: FieldMap = {
  basicAuth: {
    wireName: "basic_auth",
    kind: "object",
    fields: V2betaTypeProvider_Credential_BasicAuthFields,
  },
  serviceAccount: {
    wireName: "service_account",
    kind: "object",
    fields: V2betaTypeProvider_Credential_ServiceAccountFields,
  },
  useProjectDefault: "use_project_default",
};

const V2betaTypeProvider_LabelsFields: FieldMap = {
  key: "key",
  value: "value",
};

const V2betaTypeProvider_Operation_Error_Errors_DebugInfoFields: FieldMap = {
  detail: "detail",
  stackEntries: "stack_entries",
};

const V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_ErrorInfoFields: FieldMap = {
  domain: "domain",
  metadatas: "metadatas",
  reason: "reason",
};

const V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_Help_LinksFields: FieldMap = {
  description: "description",
  url: "url",
};

const V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_HelpFields: FieldMap = {
  links: {
    wireName: "links",
    kind: "list",
    fields: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_Help_LinksFields,
  },
};

const V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_LocalizedMessageFields: FieldMap = {
  locale: "locale",
  message: "message",
};

const V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_QuotaInfoFields: FieldMap = {
  dimensions: "dimensions",
  futureLimit: "future_limit",
  limit: "limit",
  limitName: "limit_name",
  metricName: "metric_name",
  rolloutStatus: "rollout_status",
};

const V2betaTypeProvider_Operation_Error_Errors_ErrorDetailsFields: FieldMap = {
  errorInfo: {
    wireName: "error_info",
    kind: "object",
    fields: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_ErrorInfoFields,
  },
  help: {
    wireName: "help",
    kind: "object",
    fields: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_HelpFields,
  },
  localizedMessage: {
    wireName: "localized_message",
    kind: "object",
    fields: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_LocalizedMessageFields,
  },
  quotaInfo: {
    wireName: "quota_info",
    kind: "object",
    fields: V2betaTypeProvider_Operation_Error_Errors_ErrorDetails_QuotaInfoFields,
  },
};

const V2betaTypeProvider_Operation_Error_ErrorsFields: FieldMap = {
  arguments: "arguments",
  code: "code",
  debugInfo: {
    wireName: "debug_info",
    kind: "object",
    fields: V2betaTypeProvider_Operation_Error_Errors_DebugInfoFields,
  },
  errorDetails: {
    wireName: "error_details",
    kind: "list",
    fields: V2betaTypeProvider_Operation_Error_Errors_ErrorDetailsFields,
  },
  location: "location",
  message: "message",
};

const V2betaTypeProvider_Operation_ErrorFields: FieldMap = {
  errors: {
    wireName: "errors",
    kind: "list",
    fields: V2betaTypeProvider_Operation_Error_ErrorsFields,
  },
};

const V2betaTypeProvider_Operation_FirewallPolicyRuleOperationMetadataFields: FieldMap = {
  allocatedPriority: "allocated_priority",
};

const V2betaTypeProvider_Operation_GetVersionOperationMetadata_InlineSbomInfoFields: FieldMap = {
  currentComponentVersions: "current_component_versions",
  targetComponentVersions: "target_component_versions",
};

const V2betaTypeProvider_Operation_GetVersionOperationMetadataFields: FieldMap = {
  inlineSbomInfo: {
    wireName: "inline_sbom_info",
    kind: "object",
    fields: V2betaTypeProvider_Operation_GetVersionOperationMetadata_InlineSbomInfoFields,
  },
};

const V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadata_PerLocationStatusFields: FieldMap = {
  createdVmCount: "created_vm_count",
  deletedVmCount: "deleted_vm_count",
  failedToCreateVmCount: "failed_to_create_vm_count",
  status: "status",
  targetVmCount: "target_vm_count",
};

const V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadataFields: FieldMap = {
  machineType: "machine_type",
  perLocationStatus: {
    wireName: "per_location_status",
    kind: "map",
    fields: V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadata_PerLocationStatusFields,
  },
};

const V2betaTypeProvider_Operation_SetAutoscalerLinkOperationMetadataFields: FieldMap = {
  zonalIgmIds: "zonal_igm_ids",
  zoneToIgmIds: "zone_to_igm_ids",
};

const V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperations_ErrorFields: FieldMap = {
  code: "code",
  details: "details",
  message: "message",
};

const V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperationsFields: FieldMap = {
  error: {
    wireName: "error",
    kind: "object",
    fields: V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperations_ErrorFields,
  },
  state: "state",
};

const V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadataFields: FieldMap = {
  clientOperationId: "client_operation_id",
  perLocationOperations: {
    wireName: "per_location_operations",
    kind: "map",
    fields: V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadata_PerLocationOperationsFields,
  },
};

const V2betaTypeProvider_Operation_WarningsFields: FieldMap = {
  code: "code",
  data: {
    wireName: "data",
    kind: "list",
    fields: V2betaTypeProvider_LabelsFields,
  },
  message: "message",
};

const V2betaTypeProvider_OperationFields: FieldMap = {
  clientOperationId: "client_operation_id",
  creationTimestamp: "creation_timestamp",
  description: "description",
  endTime: "end_time",
  error: {
    wireName: "error",
    kind: "object",
    fields: V2betaTypeProvider_Operation_ErrorFields,
  },
  firewallPolicyRuleOperationMetadata: {
    wireName: "firewall_policy_rule_operation_metadata",
    kind: "object",
    fields: V2betaTypeProvider_Operation_FirewallPolicyRuleOperationMetadataFields,
  },
  getVersionOperationMetadata: {
    wireName: "get_version_operation_metadata",
    kind: "object",
    fields: V2betaTypeProvider_Operation_GetVersionOperationMetadataFields,
  },
  httpErrorMessage: "http_error_message",
  httpErrorStatusCode: "http_error_status_code",
  id: "id",
  insertTime: "insert_time",
  instancesBulkInsertOperationMetadata: {
    wireName: "instances_bulk_insert_operation_metadata",
    kind: "object",
    fields: V2betaTypeProvider_Operation_InstancesBulkInsertOperationMetadataFields,
  },
  kind: "kind",
  name: "name",
  operationGroupId: "operation_group_id",
  operationType: "operation_type",
  progress: "progress",
  region: "region",
  selfLink: "self_link",
  selfLinkWithId: "self_link_with_id",
  setAutoscalerLinkOperationMetadata: {
    wireName: "set_autoscaler_link_operation_metadata",
    kind: "object",
    fields: V2betaTypeProvider_Operation_SetAutoscalerLinkOperationMetadataFields,
  },
  setCommonInstanceMetadataOperationMetadata: {
    wireName: "set_common_instance_metadata_operation_metadata",
    kind: "object",
    fields: V2betaTypeProvider_Operation_SetCommonInstanceMetadataOperationMetadataFields,
  },
  startTime: "start_time",
  status: "status",
  statusMessage: "status_message",
  targetId: "target_id",
  targetLink: "target_link",
  user: "user",
  warnings: {
    wireName: "warnings",
    kind: "list",
    fields: V2betaTypeProvider_Operation_WarningsFields,
  },
  zone: "zone",
};

export interface V2betaTypeProviderConfig {
  /** Allows resource handling overrides for specific collections */
  collectionOverrides?: V2betaTypeProvider_CollectionOverrides[] | Computed<V2betaTypeProvider_CollectionOverrides[]>;
  /** The credential used by Deployment Manager and TypeProvider. Only one of the options is permitted. */
  credential?: V2betaTypeProvider_Credential | Computed<V2betaTypeProvider_Credential>;
  /** List of up to 2 custom certificate authority roots to use for TLS authentication when making calls on behalf of this type provider. If set, TLS authentication will exclusively use these roots instead of relying on publicly trusted certificate authorities when validating TLS certificate authenticity. The certificates must be in base64-encoded PEM format. The maximum size of each certificate must not exceed 10KB. */
  customCertificateAuthorityRoots?: string[] | Computed<string[]>;
  /** An optional textual description of the resource; provided by the client when the resource is created. */
  description?: string | Computed<string>;
  /** Descriptor Url for the this type provider. */
  descriptorUrl?: string | Computed<string>;
  /** Output only. Unique identifier for the resource defined by the server. */
  id?: string | Computed<string>;
  /** Output only. Creation timestamp in RFC3339 text format. */
  insertTime?: string | Computed<string>;
  /** Map of One Platform labels; provided by the client when the resource is created or updated. Specifically: Label keys must be between 1 and 63 characters long and must conform to the following regular expression: `[a-z]([-a-z0-9]*[a-z0-9])?` Label values must be between 0 and 63 characters long and must conform to the regular expression `([a-z]([-a-z0-9]*[a-z0-9])?)?` */
  labels?: V2betaTypeProvider_Labels[] | Computed<V2betaTypeProvider_Labels[]>;
  /** Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash. */
  name?: string | Computed<string>;
  /** Represents an Operation resource. Google Compute Engine has three Operation resources: * [Global](/compute/docs/reference/rest/{$api_version}/globalOperations) * [Regional](/compute/docs/reference/rest/{$api_version}/regionOperations) * [Zonal](/compute/docs/reference/rest/{$api_version}/zoneOperations) You can use an operation resource to manage asynchronous API requests. For more information, read Handling API responses. Operations can be global, regional or zonal. - For global operations, use the `globalOperations` resource. - For regional operations, use the `regionOperations` resource. - For zonal operations, use the `zoneOperations` resource. For more information, read Global, Regional, and Zonal Resources. Note that completed Operation resources have a limited retention period. */
  operation?: V2betaTypeProvider_Operation | Computed<V2betaTypeProvider_Operation>;
  /** Options allows customized resource handling by Deployment Manager. */
  options?: V2betaTypeProvider_CollectionOverrides_Options | Computed<V2betaTypeProvider_CollectionOverrides_Options>;
  /** Output only. Self link for the type provider. */
  selfLink?: string | Computed<string>;
}

export interface V2betaTypeProviderAttrs {
  /** Allows resource handling overrides for specific collections */
  collectionOverrides: V2betaTypeProvider_CollectionOverrides[];
  /** The credential used by Deployment Manager and TypeProvider. Only one of the options is permitted. */
  credential: V2betaTypeProvider_Credential;
  /** List of up to 2 custom certificate authority roots to use for TLS authentication when making calls on behalf of this type provider. If set, TLS authentication will exclusively use these roots instead of relying on publicly trusted certificate authorities when validating TLS certificate authenticity. The certificates must be in base64-encoded PEM format. The maximum size of each certificate must not exceed 10KB. */
  customCertificateAuthorityRoots: string[];
  /** An optional textual description of the resource; provided by the client when the resource is created. */
  description: string;
  /** Descriptor Url for the this type provider. */
  descriptorUrl: string;
  /** Output only. Unique identifier for the resource defined by the server. */
  id: string;
  /** Output only. Creation timestamp in RFC3339 text format. */
  insertTime: string;
  /** Map of One Platform labels; provided by the client when the resource is created or updated. Specifically: Label keys must be between 1 and 63 characters long and must conform to the following regular expression: `[a-z]([-a-z0-9]*[a-z0-9])?` Label values must be between 0 and 63 characters long and must conform to the regular expression `([a-z]([-a-z0-9]*[a-z0-9])?)?` */
  labels: V2betaTypeProvider_Labels[];
  /** Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash. */
  name: string;
  /** Represents an Operation resource. Google Compute Engine has three Operation resources: * [Global](/compute/docs/reference/rest/{$api_version}/globalOperations) * [Regional](/compute/docs/reference/rest/{$api_version}/regionOperations) * [Zonal](/compute/docs/reference/rest/{$api_version}/zoneOperations) You can use an operation resource to manage asynchronous API requests. For more information, read Handling API responses. Operations can be global, regional or zonal. - For global operations, use the `globalOperations` resource. - For regional operations, use the `regionOperations` resource. - For zonal operations, use the `zoneOperations` resource. For more information, read Global, Regional, and Zonal Resources. Note that completed Operation resources have a limited retention period. */
  operation: V2betaTypeProvider_Operation;
  /** Options allows customized resource handling by Deployment Manager. */
  options: V2betaTypeProvider_CollectionOverrides_Options;
  /** Output only. Self link for the type provider. */
  selfLink: string;
}

export const V2betaTypeProvider: ResourceBinding<V2betaTypeProviderConfig, V2betaTypeProviderAttrs> = {
  wireType: "google_deploymentmanager_v2beta_type_provider",
  fields: {
    collectionOverrides: {
      wireName: "collection_overrides",
      kind: "list",
      fields: V2betaTypeProvider_CollectionOverridesFields,
    },
    credential: {
      wireName: "credential",
      kind: "object",
      fields: V2betaTypeProvider_CredentialFields,
    },
    customCertificateAuthorityRoots: "custom_certificate_authority_roots",
    description: "description",
    descriptorUrl: "descriptor_url",
    id: "id",
    insertTime: "insert_time",
    labels: {
      wireName: "labels",
      kind: "list",
      fields: V2betaTypeProvider_LabelsFields,
    },
    name: "name",
    operation: {
      wireName: "operation",
      kind: "object",
      fields: V2betaTypeProvider_OperationFields,
    },
    options: {
      wireName: "options",
      kind: "object",
      fields: V2betaTypeProvider_CollectionOverrides_OptionsFields,
    },
    selfLink: "self_link",
  },
};
