// Code generated by `ubx sdk gen` from google_sasportal_sasportal_device. DO NOT EDIT.
package sasportal

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SasportalDevice_ActiveConfig_AirInterface struct {
	// Conditional. This field specifies the radio access technology that is used for the CBSD.
	RadioTechnology any
	// Optional. This field is related to the `radioTechnology` and provides the air interface specification that the CBSD is compliant with at the time of registration.
	SupportedSpec any
}

type SasportalDevice_ActiveConfig_InstallationParams struct {
	// Boresight direction of the horizontal plane of the antenna in degrees with respect to true north. The value of this parameter is an integer with a value between 0 and 359 inclusive. A value of 0 degrees means true north; a value of 90 degrees means east. This parameter is optional for Category A devices and conditional for Category B devices.
	AntennaAzimuth any
	// 3-dB antenna beamwidth of the antenna in the horizontal-plane in degrees. This parameter is an unsigned integer having a value between 0 and 360 (degrees) inclusive; it is optional for Category A devices and conditional for Category B devices.
	AntennaBeamwidth any
	// Antenna downtilt in degrees and is an integer with a value between -90 and +90 inclusive; a negative value means the antenna is tilted up (above horizontal). This parameter is optional for Category A devices and conditional for Category B devices.
	AntennaDowntilt any
	// Peak antenna gain in dBi. This parameter is a double with a value between -127 and +128 (dBi) inclusive. Part of Release 2 to support floating-point value
	AntennaGain any
	// If an external antenna is used, the antenna model is optionally provided in this field. The string has a maximum length of 128 octets.
	AntennaModel any
	// If present, this parameter specifies whether the CBSD is a CPE-CBSD or not.
	CpeCbsdIndication any
	// This parameter is the maximum device EIRP in units of dBm/10MHz and is an integer with a value between -127 and +47 (dBm/10 MHz) inclusive. If not included, SAS interprets it as maximum allowable EIRP in units of dBm/10MHz for device category.
	EirpCapability any
	// Device antenna height in meters. When the `heightType` parameter value is "AGL", the antenna height should be given relative to ground level. When the `heightType` parameter value is "AMSL", it is given with respect to WGS84 datum.
	Height any
	// Specifies how the height is measured.
	HeightType any
	// A positive number in meters to indicate accuracy of the device antenna horizontal location. This optional parameter should only be present if its value is less than the FCC requirement of 50 meters.
	HorizontalAccuracy any
	// Whether the device antenna is indoor or not. `true`: indoor. `false`: outdoor.
	IndoorDeployment any
	// Latitude of the device antenna location in degrees relative to the WGS 84 datum. The allowed range is from -90.000000 to +90.000000. Positive values represent latitudes north of the equator; negative values south of the equator.
	Latitude any
	// Longitude of the device antenna location in degrees relative to the WGS 84 datum. The allowed range is from -180.000000 to +180.000000. Positive values represent longitudes east of the prime meridian; negative values west of the prime meridian.
	Longitude any
	// A positive number in meters to indicate accuracy of the device antenna vertical location. This optional parameter should only be present if its value is less than the FCC requirement of 3 meters.
	VerticalAccuracy any
}

type SasportalDevice_ActiveConfig_Model struct {
	// The firmware version of the device.
	FirmwareVersion any
	// The hardware version of the device.
	HardwareVersion any
	// The name of the device model.
	Name any
	// The software version of the device.
	SoftwareVersion any
	// The name of the device vendor.
	Vendor any
}

type SasportalDevice_ActiveConfig struct {
	// Information about the device's air interface.
	AirInterface any
	// The call sign of the device operator.
	CallSign any
	// FCC category of the device.
	Category any
	// Information about the device installation parameters.
	InstallationParams any
	// Output only. Whether the configuration has been signed by a CPI.
	IsSigned any
	// Measurement reporting capabilities of the device.
	MeasurementCapabilities any
	// Information about the model of the device.
	Model any
	// State of the configuration.
	State any
	// Output only. The last time the device configuration was edited.
	UpdateTime any
	// The identifier of a device user.
	UserId any
}

type SasportalDevice_CurrentChannels_FrequencyRange struct {
	HighFrequencyMhz any
	LowFrequencyMhz any
}

type SasportalDevice_CurrentChannels struct {
	FrequencyRange any
	Score any
}

type SasportalDevice_DeviceMetadata_NrqzValidation struct {
	// Validation case ID.
	CaseId any
	// CPI who signed the validation.
	CpiId any
	// Device latitude that's associated with the validation.
	Latitude any
	// Device longitude that's associated with the validation.
	Longitude any
	// State of the NRQZ validation info.
	State any
}

type SasportalDevice_DeviceMetadata struct {
	// If populated, the Antenna Model Pattern to use. Format is: `RecordCreatorId:PatternId`
	AntennaModel any
	// Common Channel Group (CCG). A group of CBSDs in the same ICG requesting a common primary channel assignment. For more details, see [CBRSA-TS-2001 V3.0.0](https://ongoalliance.org/wp-content/uploads/2020/02/CBRSA-TS-2001-V3.0.0_Approved-for-publication.pdf).
	CommonChannelGroup any
	// Interference Coordination Group (ICG). A group of CBSDs that manage their own interference with the group. For more details, see [CBRSA-TS-2001 V3.0.0](https://ongoalliance.org/wp-content/uploads/2020/02/CBRSA-TS-2001-V3.0.0_Approved-for-publication.pdf).
	InterferenceCoordinationGroup any
	// Output only. Set to `true` if a CPI has validated that they have coordinated with the National Quiet Zone office.
	NrqzValidated any
	// Information about National Radio Quiet Zone validation.
	NrqzValidation any
}

type SasportalDevice_Grants_MoveList struct {
	DpaId any
	FrequencyRange any
}

type SasportalDevice_Grants struct {
	ChannelType any
	ExpireTime any
	FrequencyRange any
	GrantId any
	LastHeartbeatTransmitExpireTime any
	MaxEirp any
	MoveList any
	State any
	SuspensionReason any
}

var SasportalDevice_ActiveConfig_AirInterfaceFields = ubx.FieldMap{
		"RadioTechnology": ubx.FieldSpec{WireName: "radio_technology"},
		"SupportedSpec": ubx.FieldSpec{WireName: "supported_spec"},
	}

var SasportalDevice_ActiveConfig_InstallationParamsFields = ubx.FieldMap{
		"AntennaAzimuth": ubx.FieldSpec{WireName: "antenna_azimuth"},
		"AntennaBeamwidth": ubx.FieldSpec{WireName: "antenna_beamwidth"},
		"AntennaDowntilt": ubx.FieldSpec{WireName: "antenna_downtilt"},
		"AntennaGain": ubx.FieldSpec{WireName: "antenna_gain"},
		"AntennaModel": ubx.FieldSpec{WireName: "antenna_model"},
		"CpeCbsdIndication": ubx.FieldSpec{WireName: "cpe_cbsd_indication"},
		"EirpCapability": ubx.FieldSpec{WireName: "eirp_capability"},
		"Height": ubx.FieldSpec{WireName: "height"},
		"HeightType": ubx.FieldSpec{WireName: "height_type"},
		"HorizontalAccuracy": ubx.FieldSpec{WireName: "horizontal_accuracy"},
		"IndoorDeployment": ubx.FieldSpec{WireName: "indoor_deployment"},
		"Latitude": ubx.FieldSpec{WireName: "latitude"},
		"Longitude": ubx.FieldSpec{WireName: "longitude"},
		"VerticalAccuracy": ubx.FieldSpec{WireName: "vertical_accuracy"},
	}

var SasportalDevice_ActiveConfig_ModelFields = ubx.FieldMap{
		"FirmwareVersion": ubx.FieldSpec{WireName: "firmware_version"},
		"HardwareVersion": ubx.FieldSpec{WireName: "hardware_version"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"SoftwareVersion": ubx.FieldSpec{WireName: "software_version"},
		"Vendor": ubx.FieldSpec{WireName: "vendor"},
	}

var SasportalDevice_ActiveConfigFields = ubx.FieldMap{
		"AirInterface": ubx.FieldSpec{
			WireName: "air_interface",
			Kind: "object",
			Fields: SasportalDevice_ActiveConfig_AirInterfaceFields,
		},
		"CallSign": ubx.FieldSpec{WireName: "call_sign"},
		"Category": ubx.FieldSpec{WireName: "category"},
		"InstallationParams": ubx.FieldSpec{
			WireName: "installation_params",
			Kind: "object",
			Fields: SasportalDevice_ActiveConfig_InstallationParamsFields,
		},
		"IsSigned": ubx.FieldSpec{WireName: "is_signed"},
		"MeasurementCapabilities": ubx.FieldSpec{WireName: "measurement_capabilities"},
		"Model": ubx.FieldSpec{
			WireName: "model",
			Kind: "object",
			Fields: SasportalDevice_ActiveConfig_ModelFields,
		},
		"State": ubx.FieldSpec{WireName: "state"},
		"UpdateTime": ubx.FieldSpec{WireName: "update_time"},
		"UserId": ubx.FieldSpec{WireName: "user_id"},
	}

var SasportalDevice_CurrentChannels_FrequencyRangeFields = ubx.FieldMap{
		"HighFrequencyMhz": ubx.FieldSpec{WireName: "high_frequency_mhz"},
		"LowFrequencyMhz": ubx.FieldSpec{WireName: "low_frequency_mhz"},
	}

var SasportalDevice_CurrentChannelsFields = ubx.FieldMap{
		"FrequencyRange": ubx.FieldSpec{
			WireName: "frequency_range",
			Kind: "object",
			Fields: SasportalDevice_CurrentChannels_FrequencyRangeFields,
		},
		"Score": ubx.FieldSpec{WireName: "score"},
	}

var SasportalDevice_DeviceMetadata_NrqzValidationFields = ubx.FieldMap{
		"CaseId": ubx.FieldSpec{WireName: "case_id"},
		"CpiId": ubx.FieldSpec{WireName: "cpi_id"},
		"Latitude": ubx.FieldSpec{WireName: "latitude"},
		"Longitude": ubx.FieldSpec{WireName: "longitude"},
		"State": ubx.FieldSpec{WireName: "state"},
	}

var SasportalDevice_DeviceMetadataFields = ubx.FieldMap{
		"AntennaModel": ubx.FieldSpec{WireName: "antenna_model"},
		"CommonChannelGroup": ubx.FieldSpec{WireName: "common_channel_group"},
		"InterferenceCoordinationGroup": ubx.FieldSpec{WireName: "interference_coordination_group"},
		"NrqzValidated": ubx.FieldSpec{WireName: "nrqz_validated"},
		"NrqzValidation": ubx.FieldSpec{
			WireName: "nrqz_validation",
			Kind: "object",
			Fields: SasportalDevice_DeviceMetadata_NrqzValidationFields,
		},
	}

var SasportalDevice_Grants_MoveListFields = ubx.FieldMap{
		"DpaId": ubx.FieldSpec{WireName: "dpa_id"},
		"FrequencyRange": ubx.FieldSpec{
			WireName: "frequency_range",
			Kind: "object",
			Fields: SasportalDevice_CurrentChannels_FrequencyRangeFields,
		},
	}

var SasportalDevice_GrantsFields = ubx.FieldMap{
		"ChannelType": ubx.FieldSpec{WireName: "channel_type"},
		"ExpireTime": ubx.FieldSpec{WireName: "expire_time"},
		"FrequencyRange": ubx.FieldSpec{
			WireName: "frequency_range",
			Kind: "object",
			Fields: SasportalDevice_CurrentChannels_FrequencyRangeFields,
		},
		"GrantId": ubx.FieldSpec{WireName: "grant_id"},
		"LastHeartbeatTransmitExpireTime": ubx.FieldSpec{WireName: "last_heartbeat_transmit_expire_time"},
		"MaxEirp": ubx.FieldSpec{WireName: "max_eirp"},
		"MoveList": ubx.FieldSpec{
			WireName: "move_list",
			Kind: "list",
			Fields: SasportalDevice_Grants_MoveListFields,
		},
		"State": ubx.FieldSpec{WireName: "state"},
		"SuspensionReason": ubx.FieldSpec{WireName: "suspension_reason"},
	}

type SasportalDeviceConfig struct {
	// Information about the device configuration.
	ActiveConfig any
	// Output only. Current channels with scores.
	CurrentChannels any
	// Device data overridable by both SAS Portal and registration requests.
	DeviceMetadata any
	// Device display name.
	DisplayName any
	// The FCC identifier of the device. Refer to https://www.fcc.gov/oet/ea/fccid for FccID format. Accept underscores and periods because some test-SAS customers use them.
	FccId any
	// Only ranges that are within the allowlists are available for new grants.
	GrantRangeAllowlists any
	// Output only. Grants held by the device.
	Grants any
	// Output only. The resource path name.
	Name any
	// Information about the device configuration.
	PreloadedConfig any
	// A serial number assigned to the device by the device manufacturer.
	SerialNumber any
	// Output only. Device state.
	State any
}

type SasportalDeviceAttrs struct {
	// Information about the device configuration.
	ActiveConfig any
	// Output only. Current channels with scores.
	CurrentChannels any
	// Device data overridable by both SAS Portal and registration requests.
	DeviceMetadata any
	// Device display name.
	DisplayName any
	// The FCC identifier of the device. Refer to https://www.fcc.gov/oet/ea/fccid for FccID format. Accept underscores and periods because some test-SAS customers use them.
	FccId any
	// Only ranges that are within the allowlists are available for new grants.
	GrantRangeAllowlists any
	// Output only. Grants held by the device.
	Grants any
	// Output only. The resource path name.
	Name any
	// Information about the device configuration.
	PreloadedConfig any
	// A serial number assigned to the device by the device manufacturer.
	SerialNumber any
	// Output only. Device state.
	State any
}

var SasportalDevice = ubx.ResourceBinding{
	WireType: "google_sasportal_sasportal_device",
	Fields: ubx.FieldMap{
		"ActiveConfig": ubx.FieldSpec{
			WireName: "active_config",
			Kind: "object",
			Fields: SasportalDevice_ActiveConfigFields,
		},
		"CurrentChannels": ubx.FieldSpec{
			WireName: "current_channels",
			Kind: "list",
			Fields: SasportalDevice_CurrentChannelsFields,
		},
		"DeviceMetadata": ubx.FieldSpec{
			WireName: "device_metadata",
			Kind: "object",
			Fields: SasportalDevice_DeviceMetadataFields,
		},
		"DisplayName": ubx.FieldSpec{WireName: "display_name"},
		"FccId": ubx.FieldSpec{WireName: "fcc_id"},
		"GrantRangeAllowlists": ubx.FieldSpec{
			WireName: "grant_range_allowlists",
			Kind: "list",
			Fields: SasportalDevice_CurrentChannels_FrequencyRangeFields,
		},
		"Grants": ubx.FieldSpec{
			WireName: "grants",
			Kind: "list",
			Fields: SasportalDevice_GrantsFields,
		},
		"Name": ubx.FieldSpec{WireName: "name"},
		"PreloadedConfig": ubx.FieldSpec{
			WireName: "preloaded_config",
			Kind: "object",
			Fields: SasportalDevice_ActiveConfigFields,
		},
		"SerialNumber": ubx.FieldSpec{WireName: "serial_number"},
		"State": ubx.FieldSpec{WireName: "state"},
	},
}
