# Code generated by `ubx sdk gen` from google_colab_runtime. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Runtime_NotebookRuntimeTemplateRef:
    notebook_runtime_template: Any = None

@dataclasses.dataclass
class Runtime_Timeouts:
    create: Any = None
    delete: Any = None
    update: Any = None

_Runtime_NotebookRuntimeTemplateRefFields = {
    "notebook_runtime_template": ubx.FieldSpec(wire_name="notebook_runtime_template"),
}

_Runtime_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class RuntimeConfig:
    auto_upgrade: Any = None
    deletion_policy: Any = None
    description: Any = None
    desired_state: Any = None
    display_name: Any = None
    id: Any = None
    location: Any = None
    name: Any = None
    project: Any = None
    runtime_user: Any = None
    notebook_runtime_template_ref: Any = None
    timeouts: Any = None

Runtime = ubx.ResourceBinding(
    wire_type="google_colab_runtime",
    fields={
        "auto_upgrade": ubx.FieldSpec(wire_name="auto_upgrade"),
        "deletion_policy": ubx.FieldSpec(wire_name="deletion_policy"),
        "description": ubx.FieldSpec(wire_name="description"),
        "desired_state": ubx.FieldSpec(wire_name="desired_state"),
        "display_name": ubx.FieldSpec(wire_name="display_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "name": ubx.FieldSpec(wire_name="name"),
        "project": ubx.FieldSpec(wire_name="project"),
        "runtime_user": ubx.FieldSpec(wire_name="runtime_user"),
        "notebook_runtime_template_ref": ubx.FieldSpec(
            wire_name="notebook_runtime_template_ref",
            kind="list",
            fields=_Runtime_NotebookRuntimeTemplateRefFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Runtime_TimeoutsFields,
        ),
    },
)
