// Code generated by `ubx sdk gen` from google_aiplatform_feature. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Feature_MonitoringStatsAnomalies_FeatureStatsAnomaly {
  anomalyDetectionThreshold?: number | Computed<number>;
  anomalyUri?: string | Computed<string>;
  distributionDeviation?: number | Computed<number>;
  endTime?: string | Computed<string>;
  score?: number | Computed<number>;
  startTime?: string | Computed<string>;
  statsUri?: string | Computed<string>;
}

export interface Feature_MonitoringStatsAnomalies {
  featureStatsAnomaly?: Feature_MonitoringStatsAnomalies_FeatureStatsAnomaly | Computed<Feature_MonitoringStatsAnomalies_FeatureStatsAnomaly>;
  objective?: string | Computed<string>;
}

export interface FeatureConfig {
  /** Description of the Feature. */
  description?: string | Computed<string>;
  /** Optional. Only applicable for Vertex AI Feature Store (Legacy). If not set, use the monitoring_config defined for the EntityType this Feature belongs to. Only Features with type (Feature.ValueType) BOOL, STRING, DOUBLE or INT64 can enable monitoring. If set to true, all types of data monitoring are disabled despite the config on EntityType. */
  disableMonitoring?: boolean | Computed<boolean>;
  /** Used to perform a consistent read-modify-write updates. If not set, a blind "overwrite" update happens. */
  etag?: string | Computed<string>;
  /** Optional. The labels with user-defined metadata to organize your Features. Label keys and values can be no longer than 64 characters (Unicode codepoints), can only contain lowercase letters, numeric characters, underscores and dashes. International characters are allowed. See https://goo.gl/xmQnxf for more information on and examples of labels. No more than 64 user labels can be associated with one Feature (System labels are excluded)." System reserved label keys are prefixed with "aiplatform.googleapis.com/" and are immutable. */
  labels?: Record<string, string> | Computed<Record<string, string>>;
  /** Immutable. Name of the Feature. Format: `projects/{project}/locations/{location}/featurestores/{featurestore}/entityTypes/{entity_type}/features/{feature}` `projects/{project}/locations/{location}/featureGroups/{feature_group}/features/{feature}` The last part feature is assigned by the client. The feature can be up to 64 characters long and can consist only of ASCII Latin letters A-Z and a-z, underscore(_), and ASCII digits 0-9 starting with a letter. The value will be unique given an entity type. */
  name?: string | Computed<string>;
  /** Entity responsible for maintaining this feature. Can be comma separated list of email addresses or URIs. */
  pointOfContact?: string | Computed<string>;
  /** Immutable. Only applicable for Vertex AI Feature Store (Legacy). Type of Feature value. */
  valueType?: string | Computed<string>;
  /** Only applicable for Vertex AI Feature Store. The name of the BigQuery Table/View column hosting data for this version. If no value is provided, will use feature_id. */
  versionColumnName?: string | Computed<string>;
}

export interface FeatureAttrs {
  /** Output only. Only applicable for Vertex AI Feature Store (Legacy). Timestamp when this EntityType was created. */
  createTime: string;
  /** Description of the Feature. */
  description: string;
  /** Optional. Only applicable for Vertex AI Feature Store (Legacy). If not set, use the monitoring_config defined for the EntityType this Feature belongs to. Only Features with type (Feature.ValueType) BOOL, STRING, DOUBLE or INT64 can enable monitoring. If set to true, all types of data monitoring are disabled despite the config on EntityType. */
  disableMonitoring: boolean;
  /** Used to perform a consistent read-modify-write updates. If not set, a blind "overwrite" update happens. */
  etag: string;
  /** Optional. The labels with user-defined metadata to organize your Features. Label keys and values can be no longer than 64 characters (Unicode codepoints), can only contain lowercase letters, numeric characters, underscores and dashes. International characters are allowed. See https://goo.gl/xmQnxf for more information on and examples of labels. No more than 64 user labels can be associated with one Feature (System labels are excluded)." System reserved label keys are prefixed with "aiplatform.googleapis.com/" and are immutable. */
  labels: Record<string, string>;
  /** Output only. Only applicable for Vertex AI Feature Store (Legacy). The list of historical stats and anomalies with specified objectives. */
  monitoringStatsAnomalies: Feature_MonitoringStatsAnomalies[];
  /** Immutable. Name of the Feature. Format: `projects/{project}/locations/{location}/featurestores/{featurestore}/entityTypes/{entity_type}/features/{feature}` `projects/{project}/locations/{location}/featureGroups/{feature_group}/features/{feature}` The last part feature is assigned by the client. The feature can be up to 64 characters long and can consist only of ASCII Latin letters A-Z and a-z, underscore(_), and ASCII digits 0-9 starting with a letter. The value will be unique given an entity type. */
  name: string;
  /** Entity responsible for maintaining this feature. Can be comma separated list of email addresses or URIs. */
  pointOfContact: string;
  /** Output only. Only applicable for Vertex AI Feature Store (Legacy). Timestamp when this EntityType was most recently updated. */
  updateTime: string;
  /** Immutable. Only applicable for Vertex AI Feature Store (Legacy). Type of Feature value. */
  valueType: string;
  /** Only applicable for Vertex AI Feature Store. The name of the BigQuery Table/View column hosting data for this version. If no value is provided, will use feature_id. */
  versionColumnName: string;
}

export const Feature: ResourceBinding<FeatureConfig, FeatureAttrs> = {
  wireType: "google_aiplatform_feature",
  fields: {
    description: "description",
    disableMonitoring: "disable_monitoring",
    etag: "etag",
    labels: "labels",
    name: "name",
    pointOfContact: "point_of_contact",
    valueType: "value_type",
    versionColumnName: "version_column_name",
  },
};
