// Code generated by `ubx sdk gen` from google_aiplatform_v1beta1_slice. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotations_AttributedItems {
  annotationResourceName?: string | Computed<string>;
  distance?: number | Computed<number>;
}

export interface V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotations {
  attributedItems?: V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotations_AttributedItems[] | Computed<V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotations_AttributedItems[]>;
  outlierScore?: number | Computed<number>;
  outlierThreshold?: number | Computed<number>;
  queryType?: string | Computed<string>;
}

export interface V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_Attributions {
  approximationError?: number | Computed<number>;
  baselineOutputValue?: number | Computed<number>;
  featureAttributions?: unknown | Computed<unknown>;
  instanceOutputValue?: number | Computed<number>;
  outputDisplayName?: string | Computed<string>;
  outputIndex?: number[] | Computed<number[]>;
  outputName?: string | Computed<string>;
}

export interface V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_Neighbors {
  neighborDistance?: number | Computed<number>;
  neighborId?: string | Computed<string>;
}

export interface V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation {
  attributions?: V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_Attributions[] | Computed<V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_Attributions[]>;
  neighbors?: V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_Neighbors[] | Computed<V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_Neighbors[]>;
}

export interface V1beta1Slice_EvaluatedAnnotations_Explanations {
  explanation?: V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation | Computed<V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation>;
  explanationType?: string | Computed<string>;
}

export interface V1beta1Slice_EvaluatedAnnotations {
  dataItemPayload?: unknown | Computed<unknown>;
  errorAnalysisAnnotations?: V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotations[] | Computed<V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotations[]>;
  evaluatedDataItemViewId?: string | Computed<string>;
  explanations?: V1beta1Slice_EvaluatedAnnotations_Explanations[] | Computed<V1beta1Slice_EvaluatedAnnotations_Explanations[]>;
  groundTruths?: unknown[] | Computed<unknown[]>;
  predictions?: unknown[] | Computed<unknown[]>;
  type?: string | Computed<string>;
}

export interface V1beta1Slice_ModelExplanation {
  /** Output only. Aggregated attributions explaining the Model's prediction outputs over the set of instances. The attributions are grouped by outputs. For Models that predict only one output, such as regression Models that predict only one score, there is only one attibution that explains the predicted output. For Models that predict multiple outputs, such as multiclass Models that predict multiple classes, each element explains one specific item. Attribution.output_index can be used to identify which output this attribution is explaining. The baselineOutputValue, instanceOutputValue and featureAttributions fields are averaged over the test data. NOTE: Currently AutoML tabular classification Models produce only one attribution, which averages attributions over all the classes it predicts. Attribution.approximation_error is not populated. */
  meanAttributions?: V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_Attributions[] | Computed<V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_Attributions[]>;
}

export interface V1beta1Slice_Slice_SliceSpec_Configs_Range {
  high?: number | Computed<number>;
  low?: number | Computed<number>;
}

export interface V1beta1Slice_Slice_SliceSpec_Configs_Value {
  floatValue?: number | Computed<number>;
  stringValue?: string | Computed<string>;
}

export interface V1beta1Slice_Slice_SliceSpec_Configs {
  allValues?: boolean | Computed<boolean>;
  range?: V1beta1Slice_Slice_SliceSpec_Configs_Range | Computed<V1beta1Slice_Slice_SliceSpec_Configs_Range>;
  value?: V1beta1Slice_Slice_SliceSpec_Configs_Value | Computed<V1beta1Slice_Slice_SliceSpec_Configs_Value>;
}

export interface V1beta1Slice_Slice_SliceSpec {
  /** Mapping configuration for this SliceSpec. The key is the name of the feature. By default, the key will be prefixed by "instance" as a dictionary prefix for Vertex Batch Predictions output format. */
  configs?: Record<string, V1beta1Slice_Slice_SliceSpec_Configs> | Computed<Record<string, V1beta1Slice_Slice_SliceSpec_Configs>>;
}

export interface V1beta1Slice_Slice {
  /** Output only. The dimension of the slice. Well-known dimensions are: * `annotationSpec`: This slice is on the test data that has either ground truth or prediction with AnnotationSpec.display_name equals to value. * `slice`: This slice is a user customized slice defined by its SliceSpec. */
  dimension?: string | Computed<string>;
  /** Specification for how the data should be sliced. */
  sliceSpec?: V1beta1Slice_Slice_SliceSpec | Computed<V1beta1Slice_Slice_SliceSpec>;
  /** Output only. The value of the dimension in this slice. */
  value?: string | Computed<string>;
}

const V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotations_AttributedItemsFields: FieldMap = {
  annotationResourceName: "annotation_resource_name",
  distance: "distance",
};

const V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotationsFields: FieldMap = {
  attributedItems: {
    wireName: "attributed_items",
    kind: "list",
    fields: V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotations_AttributedItemsFields,
  },
  outlierScore: "outlier_score",
  outlierThreshold: "outlier_threshold",
  queryType: "query_type",
};

const V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_AttributionsFields: FieldMap = {
  approximationError: "approximation_error",
  baselineOutputValue: "baseline_output_value",
  featureAttributions: "feature_attributions",
  instanceOutputValue: "instance_output_value",
  outputDisplayName: "output_display_name",
  outputIndex: "output_index",
  outputName: "output_name",
};

const V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_NeighborsFields: FieldMap = {
  neighborDistance: "neighbor_distance",
  neighborId: "neighbor_id",
};

const V1beta1Slice_EvaluatedAnnotations_Explanations_ExplanationFields: FieldMap = {
  attributions: {
    wireName: "attributions",
    kind: "list",
    fields: V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_AttributionsFields,
  },
  neighbors: {
    wireName: "neighbors",
    kind: "list",
    fields: V1beta1Slice_EvaluatedAnnotations_Explanations_Explanation_NeighborsFields,
  },
};

const V1beta1Slice_EvaluatedAnnotations_ExplanationsFields: FieldMap = {
  explanation: {
    wireName: "explanation",
    kind: "object",
    fields: V1beta1Slice_EvaluatedAnnotations_Explanations_ExplanationFields,
  },
  explanationType: "explanation_type",
};

const V1beta1Slice_EvaluatedAnnotationsFields: FieldMap = {
  dataItemPayload: "data_item_payload",
  errorAnalysisAnnotations: {
    wireName: "error_analysis_annotations",
    kind: "list",
    fields: V1beta1Slice_EvaluatedAnnotations_ErrorAnalysisAnnotationsFields,
  },
  evaluatedDataItemViewId: "evaluated_data_item_view_id",
  explanations: {
    wireName: "explanations",
    kind: "list",
    fields: V1beta1Slice_EvaluatedAnnotations_ExplanationsFields,
  },
  groundTruths: "ground_truths",
  predictions: "predictions",
  type: "type",
};

export interface V1beta1SliceConfig {
  /** Required. Evaluated annotations resource to be imported. */
  evaluatedAnnotations?: V1beta1Slice_EvaluatedAnnotations[] | Computed<V1beta1Slice_EvaluatedAnnotations[]>;
}

export interface V1beta1SliceAttrs {
  /** Output only. Timestamp when this ModelEvaluationSlice was created. */
  createTime: string;
  /** Required. Evaluated annotations resource to be imported. */
  evaluatedAnnotations: V1beta1Slice_EvaluatedAnnotations[];
  /** Output only. Sliced evaluation metrics of the Model. The schema of the metrics is stored in metrics_schema_uri */
  metrics: unknown;
  /** Output only. Points to a YAML file stored on Google Cloud Storage describing the metrics of this ModelEvaluationSlice. The schema is defined as an OpenAPI 3.0.2 [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#schemaObject). */
  metricsSchemaUri: string;
  /** Aggregated explanation metrics for a Model over a set of instances. */
  modelExplanation: V1beta1Slice_ModelExplanation;
  /** Output only. The resource name of the ModelEvaluationSlice. */
  name: string;
  /** Definition of a slice. */
  slice: V1beta1Slice_Slice;
}

export const V1beta1Slice: ResourceBinding<V1beta1SliceConfig, V1beta1SliceAttrs> = {
  wireType: "google_aiplatform_v1beta1_slice",
  fields: {
    evaluatedAnnotations: {
      wireName: "evaluated_annotations",
      kind: "list",
      fields: V1beta1Slice_EvaluatedAnnotationsFields,
    },
  },
};
