# Code generated by `ubx sdk gen` from google_compute_per_instance_config. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PerInstanceConfig_PreservedState_Disk:
    delete_rule: Any = None
    device_name: Any = None
    mode: Any = None
    source: Any = None

@dataclasses.dataclass
class PerInstanceConfig_PreservedState_ExternalIp_IpAddress:
    address: Any = None

@dataclasses.dataclass
class PerInstanceConfig_PreservedState_ExternalIp:
    auto_delete: Any = None
    interface_name: Any = None
    ip_address: Any = None

@dataclasses.dataclass
class PerInstanceConfig_PreservedState:
    metadata: Any = None
    disk: Any = None
    external_ip: Any = None
    internal_ip: Any = None

@dataclasses.dataclass
class PerInstanceConfig_Timeouts:
    create: Any = None
    delete: Any = None
    update: Any = None

_PerInstanceConfig_PreservedState_DiskFields = {
    "delete_rule": ubx.FieldSpec(wire_name="delete_rule"),
    "device_name": ubx.FieldSpec(wire_name="device_name"),
    "mode": ubx.FieldSpec(wire_name="mode"),
    "source": ubx.FieldSpec(wire_name="source"),
}

_PerInstanceConfig_PreservedState_ExternalIp_IpAddressFields = {
    "address": ubx.FieldSpec(wire_name="address"),
}

_PerInstanceConfig_PreservedState_ExternalIpFields = {
    "auto_delete": ubx.FieldSpec(wire_name="auto_delete"),
    "interface_name": ubx.FieldSpec(wire_name="interface_name"),
    "ip_address": ubx.FieldSpec(
        wire_name="ip_address",
        kind="list",
        fields=_PerInstanceConfig_PreservedState_ExternalIp_IpAddressFields,
    ),
}

_PerInstanceConfig_PreservedStateFields = {
    "metadata": ubx.FieldSpec(wire_name="metadata"),
    "disk": ubx.FieldSpec(
        wire_name="disk",
        kind="set",
        fields=_PerInstanceConfig_PreservedState_DiskFields,
    ),
    "external_ip": ubx.FieldSpec(
        wire_name="external_ip",
        kind="set",
        fields=_PerInstanceConfig_PreservedState_ExternalIpFields,
    ),
    "internal_ip": ubx.FieldSpec(
        wire_name="internal_ip",
        kind="set",
        fields=_PerInstanceConfig_PreservedState_ExternalIpFields,
    ),
}

_PerInstanceConfig_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class PerInstanceConfigConfig:
    deletion_policy: Any = None
    id: Any = None
    instance_group_manager: Any = None
    minimal_action: Any = None
    most_disruptive_allowed_action: Any = None
    name: Any = None
    project: Any = None
    remove_instance_on_destroy: Any = None
    remove_instance_state_on_destroy: Any = None
    zone: Any = None
    preserved_state: Any = None
    timeouts: Any = None

PerInstanceConfig = ubx.ResourceBinding(
    wire_type="google_compute_per_instance_config",
    fields={
        "deletion_policy": ubx.FieldSpec(wire_name="deletion_policy"),
        "id": ubx.FieldSpec(wire_name="id"),
        "instance_group_manager": ubx.FieldSpec(wire_name="instance_group_manager"),
        "minimal_action": ubx.FieldSpec(wire_name="minimal_action"),
        "most_disruptive_allowed_action": ubx.FieldSpec(wire_name="most_disruptive_allowed_action"),
        "name": ubx.FieldSpec(wire_name="name"),
        "project": ubx.FieldSpec(wire_name="project"),
        "remove_instance_on_destroy": ubx.FieldSpec(wire_name="remove_instance_on_destroy"),
        "remove_instance_state_on_destroy": ubx.FieldSpec(wire_name="remove_instance_state_on_destroy"),
        "zone": ubx.FieldSpec(wire_name="zone"),
        "preserved_state": ubx.FieldSpec(
            wire_name="preserved_state",
            kind="list",
            fields=_PerInstanceConfig_PreservedStateFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_PerInstanceConfig_TimeoutsFields,
        ),
    },
)
