# Code generated by `ubx sdk gen` from google_speech_v1p1beta1_custom_class. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class V1p1beta1CustomClass_CustomClass_Items:
    value: Any = None

@dataclasses.dataclass
class V1p1beta1CustomClass_CustomClass:
    # Output only. Allows users to store small amounts of arbitrary data. Both the key and the value must be 63 characters or less each. At most 100 annotations. This field is not used.
    annotations: Any = None
    # If this custom class is a resource, the custom_class_id is the resource id of the CustomClass. Case sensitive.
    custom_class_id: Any = None
    # Output only. The time at which this resource was requested for deletion. This field is not used.
    delete_time: Any = None
    # Output only. User-settable, human-readable name for the CustomClass. Must be 63 characters or less. This field is not used.
    display_name: Any = None
    # Output only. This checksum is computed by the server based on the value of other fields. This may be sent on update, undelete, and delete requests to ensure the client has an up-to-date value before proceeding. This field is not used.
    etag: Any = None
    # Output only. The time at which this resource will be purged. This field is not used.
    expire_time: Any = None
    # A collection of class items.
    items: Any = None
    # Output only. The [KMS key name](https://cloud.google.com/kms/docs/resource-hierarchy#keys) with which the content of the ClassItem is encrypted. The expected format is `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}`.
    kms_key_name: Any = None
    # Output only. The [KMS key version name](https://cloud.google.com/kms/docs/resource-hierarchy#key_versions) with which content of the ClassItem is encrypted. The expected format is `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}/cryptoKeyVersions/{crypto_key_version}`.
    kms_key_version_name: Any = None
    # The resource name of the custom class.
    name: Any = None
    # Output only. Whether or not this CustomClass is in the process of being updated. This field is not used.
    reconciling: Any = None
    # Output only. The CustomClass lifecycle state. This field is not used.
    state: Any = None
    # Output only. System-assigned unique identifier for the CustomClass. This field is not used.
    uid: Any = None

_V1p1beta1CustomClass_CustomClass_ItemsFields = {
    "value": ubx.FieldSpec(wire_name="value"),
}

_V1p1beta1CustomClass_CustomClassFields = {
    "annotations": ubx.FieldSpec(wire_name="annotations"),
    "custom_class_id": ubx.FieldSpec(wire_name="custom_class_id"),
    "delete_time": ubx.FieldSpec(wire_name="delete_time"),
    "display_name": ubx.FieldSpec(wire_name="display_name"),
    "etag": ubx.FieldSpec(wire_name="etag"),
    "expire_time": ubx.FieldSpec(wire_name="expire_time"),
    "items": ubx.FieldSpec(
        wire_name="items",
        kind="list",
        fields=_V1p1beta1CustomClass_CustomClass_ItemsFields,
    ),
    "kms_key_name": ubx.FieldSpec(wire_name="kms_key_name"),
    "kms_key_version_name": ubx.FieldSpec(wire_name="kms_key_version_name"),
    "name": ubx.FieldSpec(wire_name="name"),
    "reconciling": ubx.FieldSpec(wire_name="reconciling"),
    "state": ubx.FieldSpec(wire_name="state"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

@dataclasses.dataclass
class V1p1beta1CustomClassConfig:
    # A set of words or phrases that represents a common concept likely to appear in your audio, for example a list of passenger ship names. CustomClass items can be substituted into placeholders that you set in PhraseSet phrases.
    custom_class: Any = None
    # Required. The ID to use for the custom class, which will become the final component of the custom class' resource name. This value should restrict to letters, numbers, and hyphens, with the first character a letter, the last a letter or a number, and be 4-63 characters.
    custom_class_id: Any = None

@dataclasses.dataclass
class V1p1beta1CustomClassAttrs:
    # Output only. Allows users to store small amounts of arbitrary data. Both the key and the value must be 63 characters or less each. At most 100 annotations. This field is not used.
    annotations: Any = None
    # A set of words or phrases that represents a common concept likely to appear in your audio, for example a list of passenger ship names. CustomClass items can be substituted into placeholders that you set in PhraseSet phrases.
    custom_class: Any = None
    # Required. The ID to use for the custom class, which will become the final component of the custom class' resource name. This value should restrict to letters, numbers, and hyphens, with the first character a letter, the last a letter or a number, and be 4-63 characters.
    custom_class_id: Any = None
    # Output only. The time at which this resource was requested for deletion. This field is not used.
    delete_time: Any = None
    # Output only. User-settable, human-readable name for the CustomClass. Must be 63 characters or less. This field is not used.
    display_name: Any = None
    # Output only. This checksum is computed by the server based on the value of other fields. This may be sent on update, undelete, and delete requests to ensure the client has an up-to-date value before proceeding. This field is not used.
    etag: Any = None
    # Output only. The time at which this resource will be purged. This field is not used.
    expire_time: Any = None
    # A collection of class items.
    items: Any = None
    # Output only. The [KMS key name](https://cloud.google.com/kms/docs/resource-hierarchy#keys) with which the content of the ClassItem is encrypted. The expected format is `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}`.
    kms_key_name: Any = None
    # Output only. The [KMS key version name](https://cloud.google.com/kms/docs/resource-hierarchy#key_versions) with which content of the ClassItem is encrypted. The expected format is `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}/cryptoKeyVersions/{crypto_key_version}`.
    kms_key_version_name: Any = None
    # The resource name of the custom class.
    name: Any = None
    # Output only. Whether or not this CustomClass is in the process of being updated. This field is not used.
    reconciling: Any = None
    # Output only. The CustomClass lifecycle state. This field is not used.
    state: Any = None
    # Output only. System-assigned unique identifier for the CustomClass. This field is not used.
    uid: Any = None

V1p1beta1CustomClass = ubx.ResourceBinding(
    wire_type="google_speech_v1p1beta1_custom_class",
    fields={
        "custom_class": ubx.FieldSpec(
            wire_name="custom_class",
            kind="object",
            fields=_V1p1beta1CustomClass_CustomClassFields,
        ),
        "custom_class_id": ubx.FieldSpec(wire_name="custom_class_id"),
    },
)
