// Code generated by `ubx sdk gen` from google_networksecurity_backend_authentication_config. DO NOT EDIT.
package networksecurity

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type BackendAuthenticationConfigConfig struct {
	// Optional. A reference to a certificatemanager.googleapis.com.Certificate resource. This is a relative resource path following the form "projects/{project}/locations/{location}/certificates/{certificate}". Used by a BackendService to negotiate mTLS when the backend connection uses TLS and the backend requests a client certificate. Must have a CLIENT_AUTH scope.
	ClientCertificate any
	// Output only. The timestamp when the resource was created.
	CreateTime any
	// Optional. Free-text description of the resource.
	Description any
	// Output only. Etag of the resource.
	Etag any
	// Set of label tags associated with the resource.
	Labels any
	// Required. Name of the BackendAuthenticationConfig resource. It matches the pattern `projects/*/locations/{location}/backendAuthenticationConfigs/{backend_authentication_config}`
	Name any
	// Optional. A reference to a TrustConfig resource from the certificatemanager.googleapis.com namespace. This is a relative resource path following the form "projects/{project}/locations/{location}/trustConfigs/{trust_config}". A BackendService uses the chain of trust represented by this TrustConfig, if specified, to validate the server certificates presented by the backend. Required unless wellKnownRoots is set to PUBLIC_ROOTS.
	TrustConfig any
	// Output only. The timestamp when the resource was updated.
	UpdateTime any
	// Well known roots to use for server certificate validation.
	WellKnownRoots any
}

type BackendAuthenticationConfigAttrs struct {
	// Optional. A reference to a certificatemanager.googleapis.com.Certificate resource. This is a relative resource path following the form "projects/{project}/locations/{location}/certificates/{certificate}". Used by a BackendService to negotiate mTLS when the backend connection uses TLS and the backend requests a client certificate. Must have a CLIENT_AUTH scope.
	ClientCertificate any
	// Output only. The timestamp when the resource was created.
	CreateTime any
	// Optional. Free-text description of the resource.
	Description any
	// Output only. Etag of the resource.
	Etag any
	// Set of label tags associated with the resource.
	Labels any
	// Required. Name of the BackendAuthenticationConfig resource. It matches the pattern `projects/*/locations/{location}/backendAuthenticationConfigs/{backend_authentication_config}`
	Name any
	// Optional. A reference to a TrustConfig resource from the certificatemanager.googleapis.com namespace. This is a relative resource path following the form "projects/{project}/locations/{location}/trustConfigs/{trust_config}". A BackendService uses the chain of trust represented by this TrustConfig, if specified, to validate the server certificates presented by the backend. Required unless wellKnownRoots is set to PUBLIC_ROOTS.
	TrustConfig any
	// Output only. The timestamp when the resource was updated.
	UpdateTime any
	// Well known roots to use for server certificate validation.
	WellKnownRoots any
}

var BackendAuthenticationConfig = ubx.ResourceBinding{
	WireType: "google_networksecurity_backend_authentication_config",
	Fields: ubx.FieldMap{
		"ClientCertificate": ubx.FieldSpec{WireName: "client_certificate"},
		"CreateTime": ubx.FieldSpec{WireName: "create_time"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"Etag": ubx.FieldSpec{WireName: "etag"},
		"Labels": ubx.FieldSpec{WireName: "labels"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"TrustConfig": ubx.FieldSpec{WireName: "trust_config"},
		"UpdateTime": ubx.FieldSpec{WireName: "update_time"},
		"WellKnownRoots": ubx.FieldSpec{WireName: "well_known_roots"},
	},
}
