// Code generated by `ubx sdk gen` from google_networksecurity_url_list. DO NOT EDIT.
package networksecurity

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type UrlListConfig struct {
	// Optional. Free-text description of the resource.
	Description any
	// Required. Name of the resource provided by the user. Name is of the form projects/{project}/locations/{location}/urlLists/{url_list} url_list should match the pattern:(^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$).
	Name any
	// Required. FQDNs and URLs.
	Values any
}

type UrlListAttrs struct {
	// Output only. Time when the security policy was created.
	CreateTime any
	// Optional. Free-text description of the resource.
	Description any
	// Required. Name of the resource provided by the user. Name is of the form projects/{project}/locations/{location}/urlLists/{url_list} url_list should match the pattern:(^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$).
	Name any
	// Output only. Time when the security policy was updated.
	UpdateTime any
	// Required. FQDNs and URLs.
	Values any
}

var UrlList = ubx.ResourceBinding{
	WireType: "google_networksecurity_url_list",
	Fields: ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"Name":        ubx.FieldSpec{WireName: "name"},
		"Values":      ubx.FieldSpec{WireName: "values"},
	},
}
