// Code generated by `ubx sdk gen` from google_apigee_apigee_debugsession. DO NOT EDIT.
package apigee

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ApigeeDebugsessionConfig struct {
	// Optional. The number of request to be traced. Min = 1, Max = 15, Default = 10.
	Count any
	// Output only. The first transaction creation timestamp, recorded by UAP.
	CreateTime any
	// Optional. A conditional statement which is evaluated against the request message to determine if it should be traced. Syntax matches that of on API Proxy bundle flow Condition.
	Filter any
	// A unique ID for this DebugSession.
	Name any
	// Optional. The time in seconds after which this DebugSession should end. This value will override the value in query param, if both are provided.
	Timeout any
	// Optional. The maximum number of bytes captured from the response payload. Min = 0, Max = 5120, Default = 5120.
	Tracesize any
	// Optional. The length of time, in seconds, that this debug session is valid, starting from when it's received in the control plane. Min = 1, Max = 15, Default = 10.
	Validity any
}

type ApigeeDebugsessionAttrs struct {
	// Optional. The number of request to be traced. Min = 1, Max = 15, Default = 10.
	Count any
	// Output only. The first transaction creation timestamp, recorded by UAP.
	CreateTime any
	// Optional. A conditional statement which is evaluated against the request message to determine if it should be traced. Syntax matches that of on API Proxy bundle flow Condition.
	Filter any
	// A unique ID for this DebugSession.
	Name any
	// Optional. The time in seconds after which this DebugSession should end. This value will override the value in query param, if both are provided.
	Timeout any
	// Optional. The maximum number of bytes captured from the response payload. Min = 0, Max = 5120, Default = 5120.
	Tracesize any
	// Optional. The length of time, in seconds, that this debug session is valid, starting from when it's received in the control plane. Min = 1, Max = 15, Default = 10.
	Validity any
}

var ApigeeDebugsession = ubx.ResourceBinding{
	WireType: "google_apigee_apigee_debugsession",
	Fields: ubx.FieldMap{
		"Count": ubx.FieldSpec{WireName: "count"},
		"CreateTime": ubx.FieldSpec{WireName: "create_time"},
		"Filter": ubx.FieldSpec{WireName: "filter"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Timeout": ubx.FieldSpec{WireName: "timeout"},
		"Tracesize": ubx.FieldSpec{WireName: "tracesize"},
		"Validity": ubx.FieldSpec{WireName: "validity"},
	},
}
