# Code generated by `ubx sdk gen` from google_orgpolicy_custom_constraint. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CustomConstraintConfig:
    # Allow or deny type.
    action_type: Any = None
    # A Common Expression Language (CEL) condition which is used in the evaluation of the constraint. For example: `resource.instanceName.matches("(production|test)_(.+_)?[\d]+")` or, `resource.management.auto_upgrade == true` The max length of the condition is 1000 characters.
    condition: Any = None
    # Detailed information about this custom policy constraint. The max length of the description is 2000 characters.
    description: Any = None
    # One line display name for the UI. The max length of the display_name is 200 characters.
    display_name: Any = None
    # All the operations being applied for this constraint.
    method_types: Any = None
    # Immutable. Name of the constraint. This is unique within the organization. The name must be of the form: * `organizations/{organization_id}/customConstraints/{custom_constraint_id}` Example: `organizations/123/customConstraints/custom.createOnlyE2TypeVms` The max length is 71 characters and the minimum length is 1. Note that the prefix `organizations/{organization_id}/customConstraints/custom.` is not counted.
    name: Any = None
    # Immutable. The resource instance type on which this policy applies. Format will be of the form : `/` Example: * `compute.googleapis.com/Instance`.
    resource_types: Any = None
    # Output only. The last time this custom constraint was updated. This represents the last time that the `CreateCustomConstraint` or `UpdateCustomConstraint` methods were called.
    update_time: Any = None

@dataclasses.dataclass
class CustomConstraintAttrs:
    # Allow or deny type.
    action_type: Any = None
    # A Common Expression Language (CEL) condition which is used in the evaluation of the constraint. For example: `resource.instanceName.matches("(production|test)_(.+_)?[\d]+")` or, `resource.management.auto_upgrade == true` The max length of the condition is 1000 characters.
    condition: Any = None
    # Detailed information about this custom policy constraint. The max length of the description is 2000 characters.
    description: Any = None
    # One line display name for the UI. The max length of the display_name is 200 characters.
    display_name: Any = None
    # All the operations being applied for this constraint.
    method_types: Any = None
    # Immutable. Name of the constraint. This is unique within the organization. The name must be of the form: * `organizations/{organization_id}/customConstraints/{custom_constraint_id}` Example: `organizations/123/customConstraints/custom.createOnlyE2TypeVms` The max length is 71 characters and the minimum length is 1. Note that the prefix `organizations/{organization_id}/customConstraints/custom.` is not counted.
    name: Any = None
    # Immutable. The resource instance type on which this policy applies. Format will be of the form : `/` Example: * `compute.googleapis.com/Instance`.
    resource_types: Any = None
    # Output only. The last time this custom constraint was updated. This represents the last time that the `CreateCustomConstraint` or `UpdateCustomConstraint` methods were called.
    update_time: Any = None

CustomConstraint = ubx.ResourceBinding(
    wire_type="google_orgpolicy_custom_constraint",
    fields={
        "action_type": ubx.FieldSpec(wire_name="action_type"),
        "condition": ubx.FieldSpec(wire_name="condition"),
        "description": ubx.FieldSpec(wire_name="description"),
        "display_name": ubx.FieldSpec(wire_name="display_name"),
        "method_types": ubx.FieldSpec(wire_name="method_types"),
        "name": ubx.FieldSpec(wire_name="name"),
        "resource_types": ubx.FieldSpec(wire_name="resource_types"),
        "update_time": ubx.FieldSpec(wire_name="update_time"),
    },
)
