// Code generated by `ubx sdk gen` from google_composer_environment. DO NOT EDIT.
package composer

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Environment_Config_DataRetentionConfig_AirflowMetadataRetentionConfig struct {
	RetentionDays any
	RetentionMode any
}

type Environment_Config_DataRetentionConfig_TaskLogsRetentionConfig struct {
	StorageMode any
}

type Environment_Config_DataRetentionConfig struct {
	AirflowMetadataRetentionConfig any
	TaskLogsRetentionConfig any
}

type Environment_Config_DatabaseConfig struct {
	MachineType any
	Zone any
}

type Environment_Config_EncryptionConfig struct {
	KmsKeyName any
}

type Environment_Config_MaintenanceWindow struct {
	EndTime any
	Recurrence any
	StartTime any
}

type Environment_Config_MasterAuthorizedNetworksConfig_CidrBlocks struct {
	CidrBlock any
	DisplayName any
}

type Environment_Config_MasterAuthorizedNetworksConfig struct {
	Enabled any
	CidrBlocks any
}

type Environment_Config_NodeConfig_IpAllocationPolicy struct {
	ClusterIpv4CidrBlock any
	ClusterSecondaryRangeName any
	ServicesIpv4CidrBlock any
	ServicesSecondaryRangeName any
	UseIpAliases any
}

type Environment_Config_NodeConfig struct {
	ComposerInternalIpv4CidrBlock any
	ComposerNetworkAttachment any
	DiskSizeGb any
	EnableIpMasqAgent any
	MachineType any
	Network any
	OauthScopes any
	ServiceAccount any
	Subnetwork any
	Tags any
	Zone any
	IpAllocationPolicy any
}

type Environment_Config_PrivateEnvironmentConfig struct {
	CloudComposerConnectionSubnetwork any
	CloudComposerNetworkIpv4CidrBlock any
	CloudSqlIpv4CidrBlock any
	ConnectionType any
	EnablePrivateEndpoint any
	EnablePrivatelyUsedPublicIps any
	MasterIpv4CidrBlock any
	WebServerIpv4CidrBlock any
}

type Environment_Config_RecoveryConfig_ScheduledSnapshotsConfig struct {
	Enabled any
	SnapshotCreationSchedule any
	SnapshotLocation any
	TimeZone any
}

type Environment_Config_RecoveryConfig struct {
	ScheduledSnapshotsConfig any
}

type Environment_Config_SoftwareConfig_CloudDataLineageIntegration struct {
	Enabled any
}

type Environment_Config_SoftwareConfig struct {
	AirflowConfigOverrides any
	EnvVariables any
	ImageVersion any
	PypiPackages any
	PythonVersion any
	SchedulerCount any
	WebServerPluginsMode any
	CloudDataLineageIntegration any
}

type Environment_Config_WebServerConfig struct {
	MachineType any
}

type Environment_Config_WebServerNetworkAccessControl_AllowedIpRange struct {
	Description any
	Value any
}

type Environment_Config_WebServerNetworkAccessControl struct {
	AllowedIpRange any
}

type Environment_Config_WorkloadsConfig_DagProcessor struct {
	Count any
	Cpu any
	MemoryGb any
	StorageGb any
}

type Environment_Config_WorkloadsConfig_Triggerer struct {
	Count any
	Cpu any
	MemoryGb any
}

type Environment_Config_WorkloadsConfig_WebServer struct {
	Cpu any
	MemoryGb any
	StorageGb any
}

type Environment_Config_WorkloadsConfig_Worker struct {
	Cpu any
	MaxCount any
	MemoryGb any
	MinCount any
	StorageGb any
}

type Environment_Config_WorkloadsConfig struct {
	DagProcessor any
	Scheduler any
	Triggerer any
	WebServer any
	Worker any
}

type Environment_Config struct {
	AirflowUri any
	DagGcsPrefix any
	EnablePrivateBuildsOnly any
	EnablePrivateEnvironment any
	EnvironmentSize any
	GkeCluster any
	NodeCount any
	ResilienceMode any
	DataRetentionConfig any
	DatabaseConfig any
	EncryptionConfig any
	MaintenanceWindow any
	MasterAuthorizedNetworksConfig any
	NodeConfig any
	PrivateEnvironmentConfig any
	RecoveryConfig any
	SoftwareConfig any
	WebServerConfig any
	WebServerNetworkAccessControl any
	WorkloadsConfig any
}

type Environment_StorageConfig struct {
	Bucket any
}

type Environment_Timeouts struct {
	Create any
	Delete any
	Update any
}

var Environment_Config_DataRetentionConfig_AirflowMetadataRetentionConfigFields = ubx.FieldMap{
		"RetentionDays": ubx.FieldSpec{WireName: "retention_days"},
		"RetentionMode": ubx.FieldSpec{WireName: "retention_mode"},
	}

var Environment_Config_DataRetentionConfig_TaskLogsRetentionConfigFields = ubx.FieldMap{
		"StorageMode": ubx.FieldSpec{WireName: "storage_mode"},
	}

var Environment_Config_DataRetentionConfigFields = ubx.FieldMap{
		"AirflowMetadataRetentionConfig": ubx.FieldSpec{
			WireName: "airflow_metadata_retention_config",
			Kind: "list",
			Fields: Environment_Config_DataRetentionConfig_AirflowMetadataRetentionConfigFields,
		},
		"TaskLogsRetentionConfig": ubx.FieldSpec{
			WireName: "task_logs_retention_config",
			Kind: "list",
			Fields: Environment_Config_DataRetentionConfig_TaskLogsRetentionConfigFields,
		},
	}

var Environment_Config_DatabaseConfigFields = ubx.FieldMap{
		"MachineType": ubx.FieldSpec{WireName: "machine_type"},
		"Zone": ubx.FieldSpec{WireName: "zone"},
	}

var Environment_Config_EncryptionConfigFields = ubx.FieldMap{
		"KmsKeyName": ubx.FieldSpec{WireName: "kms_key_name"},
	}

var Environment_Config_MaintenanceWindowFields = ubx.FieldMap{
		"EndTime": ubx.FieldSpec{WireName: "end_time"},
		"Recurrence": ubx.FieldSpec{WireName: "recurrence"},
		"StartTime": ubx.FieldSpec{WireName: "start_time"},
	}

var Environment_Config_MasterAuthorizedNetworksConfig_CidrBlocksFields = ubx.FieldMap{
		"CidrBlock": ubx.FieldSpec{WireName: "cidr_block"},
		"DisplayName": ubx.FieldSpec{WireName: "display_name"},
	}

var Environment_Config_MasterAuthorizedNetworksConfigFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"CidrBlocks": ubx.FieldSpec{
			WireName: "cidr_blocks",
			Kind: "set",
			Fields: Environment_Config_MasterAuthorizedNetworksConfig_CidrBlocksFields,
		},
	}

var Environment_Config_NodeConfig_IpAllocationPolicyFields = ubx.FieldMap{
		"ClusterIpv4CidrBlock": ubx.FieldSpec{WireName: "cluster_ipv4_cidr_block"},
		"ClusterSecondaryRangeName": ubx.FieldSpec{WireName: "cluster_secondary_range_name"},
		"ServicesIpv4CidrBlock": ubx.FieldSpec{WireName: "services_ipv4_cidr_block"},
		"ServicesSecondaryRangeName": ubx.FieldSpec{WireName: "services_secondary_range_name"},
		"UseIpAliases": ubx.FieldSpec{WireName: "use_ip_aliases"},
	}

var Environment_Config_NodeConfigFields = ubx.FieldMap{
		"ComposerInternalIpv4CidrBlock": ubx.FieldSpec{WireName: "composer_internal_ipv4_cidr_block"},
		"ComposerNetworkAttachment": ubx.FieldSpec{WireName: "composer_network_attachment"},
		"DiskSizeGb": ubx.FieldSpec{WireName: "disk_size_gb"},
		"EnableIpMasqAgent": ubx.FieldSpec{WireName: "enable_ip_masq_agent"},
		"MachineType": ubx.FieldSpec{WireName: "machine_type"},
		"Network": ubx.FieldSpec{WireName: "network"},
		"OauthScopes": ubx.FieldSpec{WireName: "oauth_scopes"},
		"ServiceAccount": ubx.FieldSpec{WireName: "service_account"},
		"Subnetwork": ubx.FieldSpec{WireName: "subnetwork"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"Zone": ubx.FieldSpec{WireName: "zone"},
		"IpAllocationPolicy": ubx.FieldSpec{
			WireName: "ip_allocation_policy",
			Kind: "list",
			Fields: Environment_Config_NodeConfig_IpAllocationPolicyFields,
		},
	}

var Environment_Config_PrivateEnvironmentConfigFields = ubx.FieldMap{
		"CloudComposerConnectionSubnetwork": ubx.FieldSpec{WireName: "cloud_composer_connection_subnetwork"},
		"CloudComposerNetworkIpv4CidrBlock": ubx.FieldSpec{WireName: "cloud_composer_network_ipv4_cidr_block"},
		"CloudSqlIpv4CidrBlock": ubx.FieldSpec{WireName: "cloud_sql_ipv4_cidr_block"},
		"ConnectionType": ubx.FieldSpec{WireName: "connection_type"},
		"EnablePrivateEndpoint": ubx.FieldSpec{WireName: "enable_private_endpoint"},
		"EnablePrivatelyUsedPublicIps": ubx.FieldSpec{WireName: "enable_privately_used_public_ips"},
		"MasterIpv4CidrBlock": ubx.FieldSpec{WireName: "master_ipv4_cidr_block"},
		"WebServerIpv4CidrBlock": ubx.FieldSpec{WireName: "web_server_ipv4_cidr_block"},
	}

var Environment_Config_RecoveryConfig_ScheduledSnapshotsConfigFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"SnapshotCreationSchedule": ubx.FieldSpec{WireName: "snapshot_creation_schedule"},
		"SnapshotLocation": ubx.FieldSpec{WireName: "snapshot_location"},
		"TimeZone": ubx.FieldSpec{WireName: "time_zone"},
	}

var Environment_Config_RecoveryConfigFields = ubx.FieldMap{
		"ScheduledSnapshotsConfig": ubx.FieldSpec{
			WireName: "scheduled_snapshots_config",
			Kind: "list",
			Fields: Environment_Config_RecoveryConfig_ScheduledSnapshotsConfigFields,
		},
	}

var Environment_Config_SoftwareConfig_CloudDataLineageIntegrationFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
	}

var Environment_Config_SoftwareConfigFields = ubx.FieldMap{
		"AirflowConfigOverrides": ubx.FieldSpec{WireName: "airflow_config_overrides"},
		"EnvVariables": ubx.FieldSpec{WireName: "env_variables"},
		"ImageVersion": ubx.FieldSpec{WireName: "image_version"},
		"PypiPackages": ubx.FieldSpec{WireName: "pypi_packages"},
		"PythonVersion": ubx.FieldSpec{WireName: "python_version"},
		"SchedulerCount": ubx.FieldSpec{WireName: "scheduler_count"},
		"WebServerPluginsMode": ubx.FieldSpec{WireName: "web_server_plugins_mode"},
		"CloudDataLineageIntegration": ubx.FieldSpec{
			WireName: "cloud_data_lineage_integration",
			Kind: "list",
			Fields: Environment_Config_SoftwareConfig_CloudDataLineageIntegrationFields,
		},
	}

var Environment_Config_WebServerConfigFields = ubx.FieldMap{
		"MachineType": ubx.FieldSpec{WireName: "machine_type"},
	}

var Environment_Config_WebServerNetworkAccessControl_AllowedIpRangeFields = ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

var Environment_Config_WebServerNetworkAccessControlFields = ubx.FieldMap{
		"AllowedIpRange": ubx.FieldSpec{
			WireName: "allowed_ip_range",
			Kind: "set",
			Fields: Environment_Config_WebServerNetworkAccessControl_AllowedIpRangeFields,
		},
	}

var Environment_Config_WorkloadsConfig_DagProcessorFields = ubx.FieldMap{
		"Count": ubx.FieldSpec{WireName: "count"},
		"Cpu": ubx.FieldSpec{WireName: "cpu"},
		"MemoryGb": ubx.FieldSpec{WireName: "memory_gb"},
		"StorageGb": ubx.FieldSpec{WireName: "storage_gb"},
	}

var Environment_Config_WorkloadsConfig_TriggererFields = ubx.FieldMap{
		"Count": ubx.FieldSpec{WireName: "count"},
		"Cpu": ubx.FieldSpec{WireName: "cpu"},
		"MemoryGb": ubx.FieldSpec{WireName: "memory_gb"},
	}

var Environment_Config_WorkloadsConfig_WebServerFields = ubx.FieldMap{
		"Cpu": ubx.FieldSpec{WireName: "cpu"},
		"MemoryGb": ubx.FieldSpec{WireName: "memory_gb"},
		"StorageGb": ubx.FieldSpec{WireName: "storage_gb"},
	}

var Environment_Config_WorkloadsConfig_WorkerFields = ubx.FieldMap{
		"Cpu": ubx.FieldSpec{WireName: "cpu"},
		"MaxCount": ubx.FieldSpec{WireName: "max_count"},
		"MemoryGb": ubx.FieldSpec{WireName: "memory_gb"},
		"MinCount": ubx.FieldSpec{WireName: "min_count"},
		"StorageGb": ubx.FieldSpec{WireName: "storage_gb"},
	}

var Environment_Config_WorkloadsConfigFields = ubx.FieldMap{
		"DagProcessor": ubx.FieldSpec{
			WireName: "dag_processor",
			Kind: "list",
			Fields: Environment_Config_WorkloadsConfig_DagProcessorFields,
		},
		"Scheduler": ubx.FieldSpec{
			WireName: "scheduler",
			Kind: "list",
			Fields: Environment_Config_WorkloadsConfig_DagProcessorFields,
		},
		"Triggerer": ubx.FieldSpec{
			WireName: "triggerer",
			Kind: "list",
			Fields: Environment_Config_WorkloadsConfig_TriggererFields,
		},
		"WebServer": ubx.FieldSpec{
			WireName: "web_server",
			Kind: "list",
			Fields: Environment_Config_WorkloadsConfig_WebServerFields,
		},
		"Worker": ubx.FieldSpec{
			WireName: "worker",
			Kind: "list",
			Fields: Environment_Config_WorkloadsConfig_WorkerFields,
		},
	}

var Environment_ConfigFields = ubx.FieldMap{
		"AirflowUri": ubx.FieldSpec{WireName: "airflow_uri"},
		"DagGcsPrefix": ubx.FieldSpec{WireName: "dag_gcs_prefix"},
		"EnablePrivateBuildsOnly": ubx.FieldSpec{WireName: "enable_private_builds_only"},
		"EnablePrivateEnvironment": ubx.FieldSpec{WireName: "enable_private_environment"},
		"EnvironmentSize": ubx.FieldSpec{WireName: "environment_size"},
		"GkeCluster": ubx.FieldSpec{WireName: "gke_cluster"},
		"NodeCount": ubx.FieldSpec{WireName: "node_count"},
		"ResilienceMode": ubx.FieldSpec{WireName: "resilience_mode"},
		"DataRetentionConfig": ubx.FieldSpec{
			WireName: "data_retention_config",
			Kind: "list",
			Fields: Environment_Config_DataRetentionConfigFields,
		},
		"DatabaseConfig": ubx.FieldSpec{
			WireName: "database_config",
			Kind: "list",
			Fields: Environment_Config_DatabaseConfigFields,
		},
		"EncryptionConfig": ubx.FieldSpec{
			WireName: "encryption_config",
			Kind: "list",
			Fields: Environment_Config_EncryptionConfigFields,
		},
		"MaintenanceWindow": ubx.FieldSpec{
			WireName: "maintenance_window",
			Kind: "list",
			Fields: Environment_Config_MaintenanceWindowFields,
		},
		"MasterAuthorizedNetworksConfig": ubx.FieldSpec{
			WireName: "master_authorized_networks_config",
			Kind: "list",
			Fields: Environment_Config_MasterAuthorizedNetworksConfigFields,
		},
		"NodeConfig": ubx.FieldSpec{
			WireName: "node_config",
			Kind: "list",
			Fields: Environment_Config_NodeConfigFields,
		},
		"PrivateEnvironmentConfig": ubx.FieldSpec{
			WireName: "private_environment_config",
			Kind: "list",
			Fields: Environment_Config_PrivateEnvironmentConfigFields,
		},
		"RecoveryConfig": ubx.FieldSpec{
			WireName: "recovery_config",
			Kind: "list",
			Fields: Environment_Config_RecoveryConfigFields,
		},
		"SoftwareConfig": ubx.FieldSpec{
			WireName: "software_config",
			Kind: "list",
			Fields: Environment_Config_SoftwareConfigFields,
		},
		"WebServerConfig": ubx.FieldSpec{
			WireName: "web_server_config",
			Kind: "list",
			Fields: Environment_Config_WebServerConfigFields,
		},
		"WebServerNetworkAccessControl": ubx.FieldSpec{
			WireName: "web_server_network_access_control",
			Kind: "list",
			Fields: Environment_Config_WebServerNetworkAccessControlFields,
		},
		"WorkloadsConfig": ubx.FieldSpec{
			WireName: "workloads_config",
			Kind: "list",
			Fields: Environment_Config_WorkloadsConfigFields,
		},
	}

var Environment_StorageConfigFields = ubx.FieldMap{
		"Bucket": ubx.FieldSpec{WireName: "bucket"},
	}

var Environment_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type EnvironmentConfig struct {
	DeletionPolicy any
	Id any
	Labels any
	Name any
	Project any
	Region any
	Config any
	StorageConfig any
	Timeouts any
}

var Environment = ubx.ResourceBinding{
	WireType: "google_composer_environment",
	Fields: ubx.FieldMap{
		"DeletionPolicy": ubx.FieldSpec{WireName: "deletion_policy"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Labels": ubx.FieldSpec{WireName: "labels"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Project": ubx.FieldSpec{WireName: "project"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"Config": ubx.FieldSpec{
			WireName: "config",
			Kind: "list",
			Fields: Environment_ConfigFields,
		},
		"StorageConfig": ubx.FieldSpec{
			WireName: "storage_config",
			Kind: "list",
			Fields: Environment_StorageConfigFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Environment_TimeoutsFields,
		},
	},
}
