// Code generated by `ubx sdk gen` from google_clouddeploy_delivery_pipeline_iam_binding. DO NOT EDIT.
package clouddeploy

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DeliveryPipelineIamBinding_Condition struct {
	Description any
	Expression any
	Title any
}

var DeliveryPipelineIamBinding_ConditionFields = ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"Expression": ubx.FieldSpec{WireName: "expression"},
		"Title": ubx.FieldSpec{WireName: "title"},
	}

type DeliveryPipelineIamBindingConfig struct {
	Id any
	Location any
	Members any
	Name any
	Project any
	Role any
	Condition any
}

var DeliveryPipelineIamBinding = ubx.ResourceBinding{
	WireType: "google_clouddeploy_delivery_pipeline_iam_binding",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
		"Location": ubx.FieldSpec{WireName: "location"},
		"Members": ubx.FieldSpec{WireName: "members"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Project": ubx.FieldSpec{WireName: "project"},
		"Role": ubx.FieldSpec{WireName: "role"},
		"Condition": ubx.FieldSpec{
			WireName: "condition",
			Kind: "list",
			Fields: DeliveryPipelineIamBinding_ConditionFields,
		},
	},
}
