// Code generated by `ubx sdk gen` from google_networkmanagement_networkmanagement_network_monitoring_provider. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface NetworkmanagementNetworkMonitoringProviderConfig {
  /** Output only. The time the NetworkMonitoringProvider was created. */
  createTime?: string | Computed<string>;
  /** Output only. The list of error messages detected for the NetworkMonitoringProvider. */
  errors?: string[] | Computed<string[]>;
  /** Output only. Identifier. Name of the resource. Format: `projects/{project}/locations/{location}/networkMonitoringProviders/{network_monitoring_provider}` */
  name?: string | Computed<string>;
  /** Required. Type of the NetworkMonitoringProvider. */
  providerType?: string | Computed<string>;
  /** Output only. Link to the provider's UI. */
  providerUri?: string | Computed<string>;
  /** Output only. State of the NetworkMonitoringProvider. */
  state?: string | Computed<string>;
  /** Output only. The time the NetworkMonitoringProvider was updated. */
  updateTime?: string | Computed<string>;
}

export interface NetworkmanagementNetworkMonitoringProviderAttrs {
  /** Output only. The time the NetworkMonitoringProvider was created. */
  createTime: string;
  /** Output only. The list of error messages detected for the NetworkMonitoringProvider. */
  errors: string[];
  /** Output only. Identifier. Name of the resource. Format: `projects/{project}/locations/{location}/networkMonitoringProviders/{network_monitoring_provider}` */
  name: string;
  /** Required. Type of the NetworkMonitoringProvider. */
  providerType: string;
  /** Output only. Link to the provider's UI. */
  providerUri: string;
  /** Output only. State of the NetworkMonitoringProvider. */
  state: string;
  /** Output only. The time the NetworkMonitoringProvider was updated. */
  updateTime: string;
}

export const NetworkmanagementNetworkMonitoringProvider: ResourceBinding<NetworkmanagementNetworkMonitoringProviderConfig, NetworkmanagementNetworkMonitoringProviderAttrs> = {
  wireType: "google_networkmanagement_networkmanagement_network_monitoring_provider",
  fields: {
    createTime: "create_time",
    errors: "errors",
    name: "name",
    providerType: "provider_type",
    providerUri: "provider_uri",
    state: "state",
    updateTime: "update_time",
  },
};
