# Code generated by `ubx sdk gen` from google_firestore_v1beta1_index. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class V1beta1Index_Fields:
    field_path: Any = None
    mode: Any = None

_V1beta1Index_FieldsFields = {
    "field_path": ubx.FieldSpec(wire_name="field_path"),
    "mode": ubx.FieldSpec(wire_name="mode"),
}

@dataclasses.dataclass
class V1beta1IndexConfig:
    # The collection ID to which this index applies. Required.
    collection_id: Any = None
    # The fields to index.
    fields: Any = None
    # The resource name of the index. Output only.
    name: Any = None
    # The state of the index. Output only.
    state: Any = None

@dataclasses.dataclass
class V1beta1IndexAttrs:
    # The collection ID to which this index applies. Required.
    collection_id: Any = None
    # The fields to index.
    fields: Any = None
    # The resource name of the index. Output only.
    name: Any = None
    # The state of the index. Output only.
    state: Any = None

V1beta1Index = ubx.ResourceBinding(
    wire_type="google_firestore_v1beta1_index",
    fields={
        "collection_id": ubx.FieldSpec(wire_name="collection_id"),
        "fields": ubx.FieldSpec(
            wire_name="fields",
            kind="list",
            fields=_V1beta1Index_FieldsFields,
        ),
        "name": ubx.FieldSpec(wire_name="name"),
        "state": ubx.FieldSpec(wire_name="state"),
    },
)
