# Code generated by `ubx sdk gen` from google_dataform_v1beta1_repository. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class V1beta1Repository_DataEncryptionState:
    # Required. The KMS key version name with which data of a resource is encrypted.
    kms_key_version_name: Any = None

@dataclasses.dataclass
class V1beta1Repository_GitRemoteSettings_SshAuthenticationConfig:
    # Required. Content of a public SSH key to verify an identity of a remote Git host.
    host_public_key: Any = None
    # Required. The name of the Secret Manager secret version to use as a ssh private key for Git operations. Must be in the format `projects/*/secrets/*/versions/*`.
    user_private_key_secret_version: Any = None

@dataclasses.dataclass
class V1beta1Repository_GitRemoteSettings:
    # Optional. The name of the Secret Manager secret version to use as an authentication token for Git operations. Must be in the format `projects/*/secrets/*/versions/*`.
    authentication_token_secret_version: Any = None
    # Optional. The Git remote's default branch name. If not set, `main` will be used.
    default_branch: Any = None
    # Output only. The Git remote's effective default branch name. This is the default branch name of the Git remote if it is set, otherwise it is `main`.
    effective_default_branch: Any = None
    # Optional. Resource name for the `GitRepositoryLink` used for machine credentials. Must be in the format `projects/*/locations/*/connections/*/gitRepositoryLinks/*`
    git_repository_link: Any = None
    # Configures fields for performing SSH authentication.
    ssh_authentication_config: Any = None
    # Output only. Deprecated: The field does not contain any token status information. Instead use https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories/computeAccessTokenStatus
    token_status: Any = None
    # Required. The Git remote's URL.
    url: Any = None

@dataclasses.dataclass
class V1beta1Repository_WorkspaceCompilationOverrides:
    # Optional. The default database (Google Cloud project ID).
    default_database: Any = None
    # Optional. The suffix that should be appended to all schema (BigQuery dataset ID) names.
    schema_suffix: Any = None
    # Optional. The prefix that should be prepended to all table names.
    table_prefix: Any = None

_V1beta1Repository_DataEncryptionStateFields = {
    "kms_key_version_name": ubx.FieldSpec(wire_name="kms_key_version_name"),
}

_V1beta1Repository_GitRemoteSettings_SshAuthenticationConfigFields = {
    "host_public_key": ubx.FieldSpec(wire_name="host_public_key"),
    "user_private_key_secret_version": ubx.FieldSpec(wire_name="user_private_key_secret_version"),
}

_V1beta1Repository_GitRemoteSettingsFields = {
    "authentication_token_secret_version": ubx.FieldSpec(wire_name="authentication_token_secret_version"),
    "default_branch": ubx.FieldSpec(wire_name="default_branch"),
    "effective_default_branch": ubx.FieldSpec(wire_name="effective_default_branch"),
    "git_repository_link": ubx.FieldSpec(wire_name="git_repository_link"),
    "ssh_authentication_config": ubx.FieldSpec(
        wire_name="ssh_authentication_config",
        kind="object",
        fields=_V1beta1Repository_GitRemoteSettings_SshAuthenticationConfigFields,
    ),
    "token_status": ubx.FieldSpec(wire_name="token_status"),
    "url": ubx.FieldSpec(wire_name="url"),
}

_V1beta1Repository_WorkspaceCompilationOverridesFields = {
    "default_database": ubx.FieldSpec(wire_name="default_database"),
    "schema_suffix": ubx.FieldSpec(wire_name="schema_suffix"),
    "table_prefix": ubx.FieldSpec(wire_name="table_prefix"),
}

@dataclasses.dataclass
class V1beta1RepositoryConfig:
    # Optional. The name of the containing folder of the repository. The field is immutable and it can be modified via a MoveRepository operation. Format: `projects/*/locations/*/folders/*`. or `projects/*/locations/*/teamFolders/*`.
    containing_folder: Any = None
    # Output only. The timestamp of when the repository was created.
    create_time: Any = None
    # Describes encryption state of a resource.
    data_encryption_state: Any = None
    # Optional. The repository's user-friendly name.
    display_name: Any = None
    # Controls Git remote configuration for a repository.
    git_remote_settings: Any = None
    # Output only. All the metadata information that is used internally to serve the resource. For example: timestamps, flags, status fields, etc. The format of this field is a JSON string.
    internal_metadata: Any = None
    # Optional. The reference to a KMS encryption key. If provided, it will be used to encrypt user data in the repository and all child resources. It is not possible to add or update the encryption key after the repository is created. Example: `projects/{kms_project}/locations/{location}/keyRings/{key_location}/cryptoKeys/{key}`
    kms_key_name: Any = None
    # Optional. Repository user labels.
    labels: Any = None
    # Identifier. The repository's name.
    name: Any = None
    # Optional. The name of the Secret Manager secret version to be used to interpolate variables into the .npmrc file for package installation operations. Must be in the format `projects/*/secrets/*/versions/*`. The file itself must be in a JSON format.
    npmrc_environment_variables_secret_version: Any = None
    # Optional. The service account to run workflow invocations under.
    service_account: Any = None
    # Optional. Input only. If set to true, the authenticated user will be granted the roles/dataform.admin role on the created repository. To modify access to the created repository later apply setIamPolicy from https://cloud.google.com/dataform/reference/rest#rest-resource:-v1beta1.projects.locations.repositories
    set_authenticated_user_admin: Any = None
    # Output only. The resource name of the TeamFolder that this Repository is associated with. This should take the format: projects/{project}/locations/{location}/teamFolders/{teamFolder}. If this is not set, the Repository is not associated with a TeamFolder.
    team_folder_name: Any = None
    # Configures workspace compilation overrides for a repository. Primarily used by the UI (`console.cloud.google.com`). `schema_suffix` and `table_prefix` can have a special expression - `${workspaceName}`, which refers to the workspace name from which the compilation results will be created. API callers are expected to resolve the expression in these overrides and provide them explicitly in `code_compilation_config` (https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories.compilationResults#codecompilationconfig) when creating workspace-scoped compilation results.
    workspace_compilation_overrides: Any = None

@dataclasses.dataclass
class V1beta1RepositoryAttrs:
    # Optional. The name of the containing folder of the repository. The field is immutable and it can be modified via a MoveRepository operation. Format: `projects/*/locations/*/folders/*`. or `projects/*/locations/*/teamFolders/*`.
    containing_folder: Any = None
    # Output only. The timestamp of when the repository was created.
    create_time: Any = None
    # Describes encryption state of a resource.
    data_encryption_state: Any = None
    # Optional. The repository's user-friendly name.
    display_name: Any = None
    # Controls Git remote configuration for a repository.
    git_remote_settings: Any = None
    # Output only. All the metadata information that is used internally to serve the resource. For example: timestamps, flags, status fields, etc. The format of this field is a JSON string.
    internal_metadata: Any = None
    # Optional. The reference to a KMS encryption key. If provided, it will be used to encrypt user data in the repository and all child resources. It is not possible to add or update the encryption key after the repository is created. Example: `projects/{kms_project}/locations/{location}/keyRings/{key_location}/cryptoKeys/{key}`
    kms_key_name: Any = None
    # Optional. Repository user labels.
    labels: Any = None
    # Identifier. The repository's name.
    name: Any = None
    # Optional. The name of the Secret Manager secret version to be used to interpolate variables into the .npmrc file for package installation operations. Must be in the format `projects/*/secrets/*/versions/*`. The file itself must be in a JSON format.
    npmrc_environment_variables_secret_version: Any = None
    # Optional. The service account to run workflow invocations under.
    service_account: Any = None
    # Optional. Input only. If set to true, the authenticated user will be granted the roles/dataform.admin role on the created repository. To modify access to the created repository later apply setIamPolicy from https://cloud.google.com/dataform/reference/rest#rest-resource:-v1beta1.projects.locations.repositories
    set_authenticated_user_admin: Any = None
    # Output only. The resource name of the TeamFolder that this Repository is associated with. This should take the format: projects/{project}/locations/{location}/teamFolders/{teamFolder}. If this is not set, the Repository is not associated with a TeamFolder.
    team_folder_name: Any = None
    # Configures workspace compilation overrides for a repository. Primarily used by the UI (`console.cloud.google.com`). `schema_suffix` and `table_prefix` can have a special expression - `${workspaceName}`, which refers to the workspace name from which the compilation results will be created. API callers are expected to resolve the expression in these overrides and provide them explicitly in `code_compilation_config` (https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories.compilationResults#codecompilationconfig) when creating workspace-scoped compilation results.
    workspace_compilation_overrides: Any = None

V1beta1Repository = ubx.ResourceBinding(
    wire_type="google_dataform_v1beta1_repository",
    fields={
        "containing_folder": ubx.FieldSpec(wire_name="containing_folder"),
        "create_time": ubx.FieldSpec(wire_name="create_time"),
        "data_encryption_state": ubx.FieldSpec(
            wire_name="data_encryption_state",
            kind="object",
            fields=_V1beta1Repository_DataEncryptionStateFields,
        ),
        "display_name": ubx.FieldSpec(wire_name="display_name"),
        "git_remote_settings": ubx.FieldSpec(
            wire_name="git_remote_settings",
            kind="object",
            fields=_V1beta1Repository_GitRemoteSettingsFields,
        ),
        "internal_metadata": ubx.FieldSpec(wire_name="internal_metadata"),
        "kms_key_name": ubx.FieldSpec(wire_name="kms_key_name"),
        "labels": ubx.FieldSpec(wire_name="labels"),
        "name": ubx.FieldSpec(wire_name="name"),
        "npmrc_environment_variables_secret_version": ubx.FieldSpec(wire_name="npmrc_environment_variables_secret_version"),
        "service_account": ubx.FieldSpec(wire_name="service_account"),
        "set_authenticated_user_admin": ubx.FieldSpec(wire_name="set_authenticated_user_admin"),
        "team_folder_name": ubx.FieldSpec(wire_name="team_folder_name"),
        "workspace_compilation_overrides": ubx.FieldSpec(
            wire_name="workspace_compilation_overrides",
            kind="object",
            fields=_V1beta1Repository_WorkspaceCompilationOverridesFields,
        ),
    },
)
