// Code generated by `ubx sdk gen` from google_managedidentities_sql_integration. DO NOT EDIT.
package managedidentities

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SqlIntegrationConfig struct {
	Name any
}

type SqlIntegrationAttrs struct {
	// Output only. The time the SQL integration was created.
	CreateTime any
	Name       any
	// The full resource name of an integrated SQL instance
	SqlInstance any
	// Output only. The current state of the SQL integration.
	State any
	// Output only. The time the SQL integration was updated.
	UpdateTime any
}

var SqlIntegration = ubx.DataSourceBinding{
	WireType: "google_managedidentities_sql_integration",
	Fields: ubx.FieldMap{
		"Name": ubx.FieldSpec{WireName: "name"},
	},
}
