// Code generated by `ubx sdk gen` from google_spanner_instance. DO NOT EDIT.
package spanner

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_Overrides_AutoscalingLimits struct {
	MaxNodes any
	MaxProcessingUnits any
	MinNodes any
	MinProcessingUnits any
}

type Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_Overrides struct {
	AutoscalingTargetHighPriorityCpuUtilizationPercent any
	AutoscalingTargetTotalCpuUtilizationPercent any
	DisableHighPriorityCpuAutoscaling any
	DisableTotalCpuAutoscaling any
	AutoscalingLimits any
}

type Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_ReplicaSelection struct {
	Location any
}

type Instance_AutoscalingConfig_AsymmetricAutoscalingOptions struct {
	Overrides any
	ReplicaSelection any
}

type Instance_AutoscalingConfig_AutoscalingTargets struct {
	HighPriorityCpuUtilizationPercent any
	StorageUtilizationPercent any
	TotalCpuUtilizationPercent any
}

type Instance_AutoscalingConfig struct {
	AsymmetricAutoscalingOptions any
	AutoscalingLimits any
	AutoscalingTargets any
}

type Instance_Timeouts struct {
	Create any
	Delete any
	Update any
}

var Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_Overrides_AutoscalingLimitsFields = ubx.FieldMap{
		"MaxNodes": ubx.FieldSpec{WireName: "max_nodes"},
		"MaxProcessingUnits": ubx.FieldSpec{WireName: "max_processing_units"},
		"MinNodes": ubx.FieldSpec{WireName: "min_nodes"},
		"MinProcessingUnits": ubx.FieldSpec{WireName: "min_processing_units"},
	}

var Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_OverridesFields = ubx.FieldMap{
		"AutoscalingTargetHighPriorityCpuUtilizationPercent": ubx.FieldSpec{WireName: "autoscaling_target_high_priority_cpu_utilization_percent"},
		"AutoscalingTargetTotalCpuUtilizationPercent": ubx.FieldSpec{WireName: "autoscaling_target_total_cpu_utilization_percent"},
		"DisableHighPriorityCpuAutoscaling": ubx.FieldSpec{WireName: "disable_high_priority_cpu_autoscaling"},
		"DisableTotalCpuAutoscaling": ubx.FieldSpec{WireName: "disable_total_cpu_autoscaling"},
		"AutoscalingLimits": ubx.FieldSpec{
			WireName: "autoscaling_limits",
			Kind: "list",
			Fields: Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_Overrides_AutoscalingLimitsFields,
		},
	}

var Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_ReplicaSelectionFields = ubx.FieldMap{
		"Location": ubx.FieldSpec{WireName: "location"},
	}

var Instance_AutoscalingConfig_AsymmetricAutoscalingOptionsFields = ubx.FieldMap{
		"Overrides": ubx.FieldSpec{
			WireName: "overrides",
			Kind: "list",
			Fields: Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_OverridesFields,
		},
		"ReplicaSelection": ubx.FieldSpec{
			WireName: "replica_selection",
			Kind: "list",
			Fields: Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_ReplicaSelectionFields,
		},
	}

var Instance_AutoscalingConfig_AutoscalingTargetsFields = ubx.FieldMap{
		"HighPriorityCpuUtilizationPercent": ubx.FieldSpec{WireName: "high_priority_cpu_utilization_percent"},
		"StorageUtilizationPercent": ubx.FieldSpec{WireName: "storage_utilization_percent"},
		"TotalCpuUtilizationPercent": ubx.FieldSpec{WireName: "total_cpu_utilization_percent"},
	}

var Instance_AutoscalingConfigFields = ubx.FieldMap{
		"AsymmetricAutoscalingOptions": ubx.FieldSpec{
			WireName: "asymmetric_autoscaling_options",
			Kind: "list",
			Fields: Instance_AutoscalingConfig_AsymmetricAutoscalingOptionsFields,
		},
		"AutoscalingLimits": ubx.FieldSpec{
			WireName: "autoscaling_limits",
			Kind: "list",
			Fields: Instance_AutoscalingConfig_AsymmetricAutoscalingOptions_Overrides_AutoscalingLimitsFields,
		},
		"AutoscalingTargets": ubx.FieldSpec{
			WireName: "autoscaling_targets",
			Kind: "list",
			Fields: Instance_AutoscalingConfig_AutoscalingTargetsFields,
		},
	}

var Instance_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type InstanceConfig_ struct {
	Config any
	DefaultBackupScheduleType any
	DeletionPolicy any
	DisplayName any
	Edition any
	ForceDestroy any
	Id any
	InstanceType any
	Labels any
	Name any
	NumNodes any
	ProcessingUnits any
	Project any
	AutoscalingConfig any
	Timeouts any
}

var Instance = ubx.ResourceBinding{
	WireType: "google_spanner_instance",
	Fields: ubx.FieldMap{
		"Config": ubx.FieldSpec{WireName: "config"},
		"DefaultBackupScheduleType": ubx.FieldSpec{WireName: "default_backup_schedule_type"},
		"DeletionPolicy": ubx.FieldSpec{WireName: "deletion_policy"},
		"DisplayName": ubx.FieldSpec{WireName: "display_name"},
		"Edition": ubx.FieldSpec{WireName: "edition"},
		"ForceDestroy": ubx.FieldSpec{WireName: "force_destroy"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"InstanceType": ubx.FieldSpec{WireName: "instance_type"},
		"Labels": ubx.FieldSpec{WireName: "labels"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"NumNodes": ubx.FieldSpec{WireName: "num_nodes"},
		"ProcessingUnits": ubx.FieldSpec{WireName: "processing_units"},
		"Project": ubx.FieldSpec{WireName: "project"},
		"AutoscalingConfig": ubx.FieldSpec{
			WireName: "autoscaling_config",
			Kind: "list",
			Fields: Instance_AutoscalingConfigFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Instance_TimeoutsFields,
		},
	},
}
