// Code generated by `ubx sdk gen` from google_storage_transfer_agent_pool. DO NOT EDIT.
package storage

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TransferAgentPool_BandwidthLimit struct {
	LimitMbps any
}

type TransferAgentPool_Timeouts struct {
	Create any
	Delete any
	Update any
}

var TransferAgentPool_BandwidthLimitFields = ubx.FieldMap{
		"LimitMbps": ubx.FieldSpec{WireName: "limit_mbps"},
	}

var TransferAgentPool_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type TransferAgentPoolConfig struct {
	DeletionPolicy any
	DisplayName any
	Id any
	Name any
	Project any
	BandwidthLimit any
	Timeouts any
}

var TransferAgentPool = ubx.ResourceBinding{
	WireType: "google_storage_transfer_agent_pool",
	Fields: ubx.FieldMap{
		"DeletionPolicy": ubx.FieldSpec{WireName: "deletion_policy"},
		"DisplayName": ubx.FieldSpec{WireName: "display_name"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Project": ubx.FieldSpec{WireName: "project"},
		"BandwidthLimit": ubx.FieldSpec{
			WireName: "bandwidth_limit",
			Kind: "list",
			Fields: TransferAgentPool_BandwidthLimitFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: TransferAgentPool_TimeoutsFields,
		},
	},
}
