// Code generated by `ubx sdk gen` from google_biglake_iceberg_catalog_iam_member. DO NOT EDIT.
package biglake

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IcebergCatalogIamMember_Condition struct {
	Description any
	Expression any
	Title any
}

var IcebergCatalogIamMember_ConditionFields = ubx.FieldMap{
		"Description": ubx.FieldSpec{WireName: "description"},
		"Expression": ubx.FieldSpec{WireName: "expression"},
		"Title": ubx.FieldSpec{WireName: "title"},
	}

type IcebergCatalogIamMemberConfig struct {
	Id any
	Member any
	Name any
	Project any
	Role any
	Condition any
}

var IcebergCatalogIamMember = ubx.ResourceBinding{
	WireType: "google_biglake_iceberg_catalog_iam_member",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
		"Member": ubx.FieldSpec{WireName: "member"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Project": ubx.FieldSpec{WireName: "project"},
		"Role": ubx.FieldSpec{WireName: "role"},
		"Condition": ubx.FieldSpec{
			WireName: "condition",
			Kind: "list",
			Fields: IcebergCatalogIamMember_ConditionFields,
		},
	},
}
