# Code generated by `ubx sdk gen` from google_dataplex_lake_iam_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LakeIamPolicyConfig:
    id: Any = None
    lake: Any = None
    location: Any = None
    policy_data: Any = None
    project: Any = None

LakeIamPolicy = ubx.ResourceBinding(
    wire_type="google_dataplex_lake_iam_policy",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "lake": ubx.FieldSpec(wire_name="lake"),
        "location": ubx.FieldSpec(wire_name="location"),
        "policy_data": ubx.FieldSpec(wire_name="policy_data"),
        "project": ubx.FieldSpec(wire_name="project"),
    },
)
