# Code generated by `ubx sdk gen` from google_dataplex_zone_iam_binding. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ZoneIamBinding_Condition:
    description: Any = None
    expression: Any = None
    title: Any = None

_ZoneIamBinding_ConditionFields = {
    "description": ubx.FieldSpec(wire_name="description"),
    "expression": ubx.FieldSpec(wire_name="expression"),
    "title": ubx.FieldSpec(wire_name="title"),
}

@dataclasses.dataclass
class ZoneIamBindingConfig:
    dataplex_zone: Any = None
    id: Any = None
    lake: Any = None
    location: Any = None
    members: Any = None
    project: Any = None
    role: Any = None
    condition: Any = None

ZoneIamBinding = ubx.ResourceBinding(
    wire_type="google_dataplex_zone_iam_binding",
    fields={
        "dataplex_zone": ubx.FieldSpec(wire_name="dataplex_zone"),
        "id": ubx.FieldSpec(wire_name="id"),
        "lake": ubx.FieldSpec(wire_name="lake"),
        "location": ubx.FieldSpec(wire_name="location"),
        "members": ubx.FieldSpec(wire_name="members"),
        "project": ubx.FieldSpec(wire_name="project"),
        "role": ubx.FieldSpec(wire_name="role"),
        "condition": ubx.FieldSpec(
            wire_name="condition",
            kind="list",
            fields=_ZoneIamBinding_ConditionFields,
        ),
    },
)
