# Code generated by `ubx sdk gen` from google_pubsub_subscription. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Subscription_BigqueryConfig:
    drop_unknown_fields: Any = None
    service_account_email: Any = None
    table: Any = None
    use_table_schema: Any = None
    use_topic_schema: Any = None
    write_metadata: Any = None

@dataclasses.dataclass
class Subscription_CloudStorageConfig_AvroConfig:
    use_topic_schema: Any = None
    write_metadata: Any = None

@dataclasses.dataclass
class Subscription_CloudStorageConfig_TextConfig:
    state: Any = None

@dataclasses.dataclass
class Subscription_CloudStorageConfig:
    bucket: Any = None
    filename_datetime_format: Any = None
    filename_prefix: Any = None
    filename_suffix: Any = None
    max_bytes: Any = None
    max_duration: Any = None
    max_messages: Any = None
    service_account_email: Any = None
    state: Any = None
    avro_config: Any = None
    text_config: Any = None

@dataclasses.dataclass
class Subscription_DeadLetterPolicy:
    dead_letter_topic: Any = None
    max_delivery_attempts: Any = None

@dataclasses.dataclass
class Subscription_ExpirationPolicy:
    ttl: Any = None

@dataclasses.dataclass
class Subscription_MessageTransforms_AiInference_UnstructuredInference:
    parameters: Any = None

@dataclasses.dataclass
class Subscription_MessageTransforms_AiInference:
    endpoint: Any = None
    service_account_email: Any = None
    unstructured_inference: Any = None

@dataclasses.dataclass
class Subscription_MessageTransforms_JavascriptUdf:
    code: Any = None
    function_name: Any = None

@dataclasses.dataclass
class Subscription_MessageTransforms:
    disabled: Any = None
    ai_inference: Any = None
    javascript_udf: Any = None

@dataclasses.dataclass
class Subscription_PushConfig_NoWrapper:
    write_metadata: Any = None

@dataclasses.dataclass
class Subscription_PushConfig_OidcToken:
    audience: Any = None
    service_account_email: Any = None

@dataclasses.dataclass
class Subscription_PushConfig:
    attributes: Any = None
    push_endpoint: Any = None
    no_wrapper: Any = None
    oidc_token: Any = None

@dataclasses.dataclass
class Subscription_RetryPolicy:
    maximum_backoff: Any = None
    minimum_backoff: Any = None

@dataclasses.dataclass
class Subscription_Timeouts:
    create: Any = None
    delete: Any = None
    update: Any = None

_Subscription_BigqueryConfigFields = {
    "drop_unknown_fields": ubx.FieldSpec(wire_name="drop_unknown_fields"),
    "service_account_email": ubx.FieldSpec(wire_name="service_account_email"),
    "table": ubx.FieldSpec(wire_name="table"),
    "use_table_schema": ubx.FieldSpec(wire_name="use_table_schema"),
    "use_topic_schema": ubx.FieldSpec(wire_name="use_topic_schema"),
    "write_metadata": ubx.FieldSpec(wire_name="write_metadata"),
}

_Subscription_CloudStorageConfig_AvroConfigFields = {
    "use_topic_schema": ubx.FieldSpec(wire_name="use_topic_schema"),
    "write_metadata": ubx.FieldSpec(wire_name="write_metadata"),
}

_Subscription_CloudStorageConfig_TextConfigFields = {
    "state": ubx.FieldSpec(wire_name="state"),
}

_Subscription_CloudStorageConfigFields = {
    "bucket": ubx.FieldSpec(wire_name="bucket"),
    "filename_datetime_format": ubx.FieldSpec(wire_name="filename_datetime_format"),
    "filename_prefix": ubx.FieldSpec(wire_name="filename_prefix"),
    "filename_suffix": ubx.FieldSpec(wire_name="filename_suffix"),
    "max_bytes": ubx.FieldSpec(wire_name="max_bytes"),
    "max_duration": ubx.FieldSpec(wire_name="max_duration"),
    "max_messages": ubx.FieldSpec(wire_name="max_messages"),
    "service_account_email": ubx.FieldSpec(wire_name="service_account_email"),
    "state": ubx.FieldSpec(wire_name="state"),
    "avro_config": ubx.FieldSpec(
        wire_name="avro_config",
        kind="list",
        fields=_Subscription_CloudStorageConfig_AvroConfigFields,
    ),
    "text_config": ubx.FieldSpec(
        wire_name="text_config",
        kind="list",
        fields=_Subscription_CloudStorageConfig_TextConfigFields,
    ),
}

_Subscription_DeadLetterPolicyFields = {
    "dead_letter_topic": ubx.FieldSpec(wire_name="dead_letter_topic"),
    "max_delivery_attempts": ubx.FieldSpec(wire_name="max_delivery_attempts"),
}

_Subscription_ExpirationPolicyFields = {
    "ttl": ubx.FieldSpec(wire_name="ttl"),
}

_Subscription_MessageTransforms_AiInference_UnstructuredInferenceFields = {
    "parameters": ubx.FieldSpec(wire_name="parameters"),
}

_Subscription_MessageTransforms_AiInferenceFields = {
    "endpoint": ubx.FieldSpec(wire_name="endpoint"),
    "service_account_email": ubx.FieldSpec(wire_name="service_account_email"),
    "unstructured_inference": ubx.FieldSpec(
        wire_name="unstructured_inference",
        kind="list",
        fields=_Subscription_MessageTransforms_AiInference_UnstructuredInferenceFields,
    ),
}

_Subscription_MessageTransforms_JavascriptUdfFields = {
    "code": ubx.FieldSpec(wire_name="code"),
    "function_name": ubx.FieldSpec(wire_name="function_name"),
}

_Subscription_MessageTransformsFields = {
    "disabled": ubx.FieldSpec(wire_name="disabled"),
    "ai_inference": ubx.FieldSpec(
        wire_name="ai_inference",
        kind="list",
        fields=_Subscription_MessageTransforms_AiInferenceFields,
    ),
    "javascript_udf": ubx.FieldSpec(
        wire_name="javascript_udf",
        kind="list",
        fields=_Subscription_MessageTransforms_JavascriptUdfFields,
    ),
}

_Subscription_PushConfig_NoWrapperFields = {
    "write_metadata": ubx.FieldSpec(wire_name="write_metadata"),
}

_Subscription_PushConfig_OidcTokenFields = {
    "audience": ubx.FieldSpec(wire_name="audience"),
    "service_account_email": ubx.FieldSpec(wire_name="service_account_email"),
}

_Subscription_PushConfigFields = {
    "attributes": ubx.FieldSpec(wire_name="attributes"),
    "push_endpoint": ubx.FieldSpec(wire_name="push_endpoint"),
    "no_wrapper": ubx.FieldSpec(
        wire_name="no_wrapper",
        kind="list",
        fields=_Subscription_PushConfig_NoWrapperFields,
    ),
    "oidc_token": ubx.FieldSpec(
        wire_name="oidc_token",
        kind="list",
        fields=_Subscription_PushConfig_OidcTokenFields,
    ),
}

_Subscription_RetryPolicyFields = {
    "maximum_backoff": ubx.FieldSpec(wire_name="maximum_backoff"),
    "minimum_backoff": ubx.FieldSpec(wire_name="minimum_backoff"),
}

_Subscription_TimeoutsFields = {
    "create": ubx.FieldSpec(wire_name="create"),
    "delete": ubx.FieldSpec(wire_name="delete"),
    "update": ubx.FieldSpec(wire_name="update"),
}

@dataclasses.dataclass
class SubscriptionConfig:
    ack_deadline_seconds: Any = None
    deletion_policy: Any = None
    enable_exactly_once_delivery: Any = None
    enable_message_ordering: Any = None
    filter: Any = None
    id: Any = None
    labels: Any = None
    message_retention_duration: Any = None
    name: Any = None
    project: Any = None
    retain_acked_messages: Any = None
    tags: Any = None
    topic: Any = None
    bigquery_config: Any = None
    cloud_storage_config: Any = None
    dead_letter_policy: Any = None
    expiration_policy: Any = None
    message_transforms: Any = None
    push_config: Any = None
    retry_policy: Any = None
    timeouts: Any = None

Subscription = ubx.ResourceBinding(
    wire_type="google_pubsub_subscription",
    fields={
        "ack_deadline_seconds": ubx.FieldSpec(wire_name="ack_deadline_seconds"),
        "deletion_policy": ubx.FieldSpec(wire_name="deletion_policy"),
        "enable_exactly_once_delivery": ubx.FieldSpec(wire_name="enable_exactly_once_delivery"),
        "enable_message_ordering": ubx.FieldSpec(wire_name="enable_message_ordering"),
        "filter": ubx.FieldSpec(wire_name="filter"),
        "id": ubx.FieldSpec(wire_name="id"),
        "labels": ubx.FieldSpec(wire_name="labels"),
        "message_retention_duration": ubx.FieldSpec(wire_name="message_retention_duration"),
        "name": ubx.FieldSpec(wire_name="name"),
        "project": ubx.FieldSpec(wire_name="project"),
        "retain_acked_messages": ubx.FieldSpec(wire_name="retain_acked_messages"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "topic": ubx.FieldSpec(wire_name="topic"),
        "bigquery_config": ubx.FieldSpec(
            wire_name="bigquery_config",
            kind="list",
            fields=_Subscription_BigqueryConfigFields,
        ),
        "cloud_storage_config": ubx.FieldSpec(
            wire_name="cloud_storage_config",
            kind="list",
            fields=_Subscription_CloudStorageConfigFields,
        ),
        "dead_letter_policy": ubx.FieldSpec(
            wire_name="dead_letter_policy",
            kind="list",
            fields=_Subscription_DeadLetterPolicyFields,
        ),
        "expiration_policy": ubx.FieldSpec(
            wire_name="expiration_policy",
            kind="list",
            fields=_Subscription_ExpirationPolicyFields,
        ),
        "message_transforms": ubx.FieldSpec(
            wire_name="message_transforms",
            kind="list",
            fields=_Subscription_MessageTransformsFields,
        ),
        "push_config": ubx.FieldSpec(
            wire_name="push_config",
            kind="list",
            fields=_Subscription_PushConfigFields,
        ),
        "retry_policy": ubx.FieldSpec(
            wire_name="retry_policy",
            kind="list",
            fields=_Subscription_RetryPolicyFields,
        ),
        "timeouts": ubx.FieldSpec(
            wire_name="timeouts",
            kind="object",
            fields=_Subscription_TimeoutsFields,
        ),
    },
)
