// Code generated by `ubx sdk gen` from google_netapp_volume_quota_rule. DO NOT EDIT.
package netapp

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type VolumeQuotaRule_Timeouts struct {
	Create any
	Delete any
	Update any
}

var VolumeQuotaRule_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type VolumeQuotaRuleConfig struct {
	DeletionPolicy any
	Description any
	DiskLimitMib any
	Id any
	Labels any
	Location any
	Name any
	Project any
	Target any
	Type any
	VolumeName any
	Timeouts any
}

var VolumeQuotaRule = ubx.ResourceBinding{
	WireType: "google_netapp_volume_quota_rule",
	Fields: ubx.FieldMap{
		"DeletionPolicy": ubx.FieldSpec{WireName: "deletion_policy"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"DiskLimitMib": ubx.FieldSpec{WireName: "disk_limit_mib"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Labels": ubx.FieldSpec{WireName: "labels"},
		"Location": ubx.FieldSpec{WireName: "location"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Project": ubx.FieldSpec{WireName: "project"},
		"Target": ubx.FieldSpec{WireName: "target"},
		"Type": ubx.FieldSpec{WireName: "type"},
		"VolumeName": ubx.FieldSpec{WireName: "volume_name"},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: VolumeQuotaRule_TimeoutsFields,
		},
	},
}
