# Code generated by `ubx sdk gen` from google_iap_web_cloud_run_service_iam_binding. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class WebCloudRunServiceIamBinding_Condition:
    description: Any = None
    expression: Any = None
    title: Any = None

_WebCloudRunServiceIamBinding_ConditionFields = {
    "description": ubx.FieldSpec(wire_name="description"),
    "expression": ubx.FieldSpec(wire_name="expression"),
    "title": ubx.FieldSpec(wire_name="title"),
}

@dataclasses.dataclass
class WebCloudRunServiceIamBindingConfig:
    cloud_run_service_name: Any = None
    id: Any = None
    location: Any = None
    members: Any = None
    project: Any = None
    role: Any = None
    condition: Any = None

WebCloudRunServiceIamBinding = ubx.ResourceBinding(
    wire_type="google_iap_web_cloud_run_service_iam_binding",
    fields={
        "cloud_run_service_name": ubx.FieldSpec(wire_name="cloud_run_service_name"),
        "id": ubx.FieldSpec(wire_name="id"),
        "location": ubx.FieldSpec(wire_name="location"),
        "members": ubx.FieldSpec(wire_name="members"),
        "project": ubx.FieldSpec(wire_name="project"),
        "role": ubx.FieldSpec(wire_name="role"),
        "condition": ubx.FieldSpec(
            wire_name="condition",
            kind="list",
            fields=_WebCloudRunServiceIamBinding_ConditionFields,
        ),
    },
)
