# Code generated by `ubx sdk gen` from google_biglake_iceberg_namespace_iam_member. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class IcebergNamespaceIamMember_Condition:
    description: Any = None
    expression: Any = None
    title: Any = None

_IcebergNamespaceIamMember_ConditionFields = {
    "description": ubx.FieldSpec(wire_name="description"),
    "expression": ubx.FieldSpec(wire_name="expression"),
    "title": ubx.FieldSpec(wire_name="title"),
}

@dataclasses.dataclass
class IcebergNamespaceIamMemberConfig:
    catalog: Any = None
    id: Any = None
    member: Any = None
    namespace_id: Any = None
    project: Any = None
    role: Any = None
    condition: Any = None

IcebergNamespaceIamMember = ubx.ResourceBinding(
    wire_type="google_biglake_iceberg_namespace_iam_member",
    fields={
        "catalog": ubx.FieldSpec(wire_name="catalog"),
        "id": ubx.FieldSpec(wire_name="id"),
        "member": ubx.FieldSpec(wire_name="member"),
        "namespace_id": ubx.FieldSpec(wire_name="namespace_id"),
        "project": ubx.FieldSpec(wire_name="project"),
        "role": ubx.FieldSpec(wire_name="role"),
        "condition": ubx.FieldSpec(
            wire_name="condition",
            kind="list",
            fields=_IcebergNamespaceIamMember_ConditionFields,
        ),
    },
)
