// Code generated by `ubx sdk gen` from google_workflows_workflows_workflow. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface WorkflowsWorkflow_StateError {
  /** Provides specifics about the error. */
  details?: string | Computed<string>;
  /** The type of this state error. */
  type?: string | Computed<string>;
}

const WorkflowsWorkflow_StateErrorFields: FieldMap = {
  details: "details",
  type: "type",
};

export interface WorkflowsWorkflowConfig {
  /** Output only. A list of all KMS crypto keys used to encrypt or decrypt the data associated with the workflow. */
  allKmsKeys?: string[] | Computed<string[]>;
  /** Output only. A list of all KMS crypto key versions used to encrypt or decrypt the data associated with the workflow. */
  allKmsKeysVersions?: string[] | Computed<string[]>;
  /** Optional. Describes the level of platform logging to apply to calls and call responses during executions of this workflow. If both the workflow and the execution specify a logging level, the execution level takes precedence. */
  callLogLevel?: string | Computed<string>;
  /** Output only. The timestamp for when the workflow was created. This is a workflow-wide field and is not tied to a specific revision. */
  createTime?: string | Computed<string>;
  /** Optional. The resource name of a KMS crypto key used to encrypt or decrypt the data associated with the workflow. Format: projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey} Using `-` as a wildcard for the `{project}` or not providing one at all will infer the project from the account. If not provided, data associated with the workflow will not be CMEK-encrypted. */
  cryptoKeyName?: string | Computed<string>;
  /** Output only. The resource name of a KMS crypto key version used to encrypt or decrypt the data associated with the workflow. Format: projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}/cryptoKeyVersions/{cryptoKeyVersion} */
  cryptoKeyVersion?: string | Computed<string>;
  /** Description of the workflow provided by the user. Must be at most 1000 Unicode characters long. This is a workflow-wide field and is not tied to a specific revision. */
  description?: string | Computed<string>;
  /** Optional. Describes the execution history level to apply to this workflow. */
  executionHistoryLevel?: string | Computed<string>;
  /** Labels associated with this workflow. Labels can contain at most 64 entries. Keys and values can be no longer than 63 characters and can only contain lowercase letters, numeric characters, underscores, and dashes. Label keys must start with a letter. International characters are allowed. This is a workflow-wide field and is not tied to a specific revision. */
  labels?: Record<string, string> | Computed<Record<string, string>>;
  /** The resource name of the workflow. Format: projects/{project}/locations/{location}/workflows/{workflow}. This is a workflow-wide field and is not tied to a specific revision. */
  name?: string | Computed<string>;
  /** Output only. The timestamp for the latest revision of the workflow's creation. */
  revisionCreateTime?: string | Computed<string>;
  /** Output only. The revision of the workflow. A new revision of a workflow is created as a result of updating the following properties of a workflow: - Service account - Workflow code to be executed The format is "000001-a4d", where the first six characters define the zero-padded revision ordinal number. They are followed by a hyphen and three hexadecimal random characters. */
  revisionId?: string | Computed<string>;
  /** The service account associated with the latest workflow version. This service account represents the identity of the workflow and determines what permissions the workflow has. Format: projects/{project}/serviceAccounts/{account} or {account} Using `-` as a wildcard for the `{project}` or not providing one at all will infer the project from the account. The `{account}` value can be the `email` address or the `unique_id` of the service account. If not provided, workflow will use the project's default service account. Modifying this field for an existing workflow results in a new workflow revision. */
  serviceAccount?: string | Computed<string>;
  /** Workflow code to be executed. The size limit is 128KB. */
  sourceContents?: string | Computed<string>;
  /** Output only. State of the workflow deployment. */
  state?: string | Computed<string>;
  /** Describes an error related to the current state of the workflow. */
  stateError?: WorkflowsWorkflow_StateError | Computed<WorkflowsWorkflow_StateError>;
  /** Optional. Input only. Immutable. Tags associated with this workflow. */
  tags?: Record<string, string> | Computed<Record<string, string>>;
  /** Output only. The timestamp for when the workflow was last updated. This is a workflow-wide field and is not tied to a specific revision. */
  updateTime?: string | Computed<string>;
  /** Optional. User-defined environment variables associated with this workflow revision. This map has a maximum length of 20. Each string can take up to 4KiB. Keys cannot be empty strings and cannot start with "GOOGLE" or "WORKFLOWS". */
  userEnvVars?: Record<string, string> | Computed<Record<string, string>>;
}

export interface WorkflowsWorkflowAttrs {
  /** Output only. A list of all KMS crypto keys used to encrypt or decrypt the data associated with the workflow. */
  allKmsKeys: string[];
  /** Output only. A list of all KMS crypto key versions used to encrypt or decrypt the data associated with the workflow. */
  allKmsKeysVersions: string[];
  /** Optional. Describes the level of platform logging to apply to calls and call responses during executions of this workflow. If both the workflow and the execution specify a logging level, the execution level takes precedence. */
  callLogLevel: string;
  /** Output only. The timestamp for when the workflow was created. This is a workflow-wide field and is not tied to a specific revision. */
  createTime: string;
  /** Optional. The resource name of a KMS crypto key used to encrypt or decrypt the data associated with the workflow. Format: projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey} Using `-` as a wildcard for the `{project}` or not providing one at all will infer the project from the account. If not provided, data associated with the workflow will not be CMEK-encrypted. */
  cryptoKeyName: string;
  /** Output only. The resource name of a KMS crypto key version used to encrypt or decrypt the data associated with the workflow. Format: projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}/cryptoKeyVersions/{cryptoKeyVersion} */
  cryptoKeyVersion: string;
  /** Description of the workflow provided by the user. Must be at most 1000 Unicode characters long. This is a workflow-wide field and is not tied to a specific revision. */
  description: string;
  /** Optional. Describes the execution history level to apply to this workflow. */
  executionHistoryLevel: string;
  /** Labels associated with this workflow. Labels can contain at most 64 entries. Keys and values can be no longer than 63 characters and can only contain lowercase letters, numeric characters, underscores, and dashes. Label keys must start with a letter. International characters are allowed. This is a workflow-wide field and is not tied to a specific revision. */
  labels: Record<string, string>;
  /** The resource name of the workflow. Format: projects/{project}/locations/{location}/workflows/{workflow}. This is a workflow-wide field and is not tied to a specific revision. */
  name: string;
  /** Output only. The timestamp for the latest revision of the workflow's creation. */
  revisionCreateTime: string;
  /** Output only. The revision of the workflow. A new revision of a workflow is created as a result of updating the following properties of a workflow: - Service account - Workflow code to be executed The format is "000001-a4d", where the first six characters define the zero-padded revision ordinal number. They are followed by a hyphen and three hexadecimal random characters. */
  revisionId: string;
  /** The service account associated with the latest workflow version. This service account represents the identity of the workflow and determines what permissions the workflow has. Format: projects/{project}/serviceAccounts/{account} or {account} Using `-` as a wildcard for the `{project}` or not providing one at all will infer the project from the account. The `{account}` value can be the `email` address or the `unique_id` of the service account. If not provided, workflow will use the project's default service account. Modifying this field for an existing workflow results in a new workflow revision. */
  serviceAccount: string;
  /** Workflow code to be executed. The size limit is 128KB. */
  sourceContents: string;
  /** Output only. State of the workflow deployment. */
  state: string;
  /** Describes an error related to the current state of the workflow. */
  stateError: WorkflowsWorkflow_StateError;
  /** Optional. Input only. Immutable. Tags associated with this workflow. */
  tags: Record<string, string>;
  /** Output only. The timestamp for when the workflow was last updated. This is a workflow-wide field and is not tied to a specific revision. */
  updateTime: string;
  /** Optional. User-defined environment variables associated with this workflow revision. This map has a maximum length of 20. Each string can take up to 4KiB. Keys cannot be empty strings and cannot start with "GOOGLE" or "WORKFLOWS". */
  userEnvVars: Record<string, string>;
}

export const WorkflowsWorkflow: ResourceBinding<WorkflowsWorkflowConfig, WorkflowsWorkflowAttrs> = {
  wireType: "google_workflows_workflows_workflow",
  fields: {
    allKmsKeys: "all_kms_keys",
    allKmsKeysVersions: "all_kms_keys_versions",
    callLogLevel: "call_log_level",
    createTime: "create_time",
    cryptoKeyName: "crypto_key_name",
    cryptoKeyVersion: "crypto_key_version",
    description: "description",
    executionHistoryLevel: "execution_history_level",
    labels: "labels",
    name: "name",
    revisionCreateTime: "revision_create_time",
    revisionId: "revision_id",
    serviceAccount: "service_account",
    sourceContents: "source_contents",
    state: "state",
    stateError: {
      wireName: "state_error",
      kind: "object",
      fields: WorkflowsWorkflow_StateErrorFields,
    },
    tags: "tags",
    updateTime: "update_time",
    userEnvVars: "user_env_vars",
  },
};
