// Code generated by `ubx sdk gen` from google_compute_alpha_zone_queued_resource. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKey {
  kmsKeyName?: string | Computed<string>;
  kmsKeyServiceAccount?: string | Computed<string>;
  rawKey?: string | Computed<string>;
  rsaEncryptedKey?: string | Computed<string>;
  sha256?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_GuestOsFeatures {
  type?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_InitializeParams {
  architecture?: string | Computed<string>;
  description?: string | Computed<string>;
  diskName?: string | Computed<string>;
  diskSizeGb?: string | Computed<string>;
  diskType?: string | Computed<string>;
  enableConfidentialCompute?: boolean | Computed<boolean>;
  guestOsFeatures?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_GuestOsFeatures[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_GuestOsFeatures[]>;
  interface?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  licenseCodes?: string[] | Computed<string[]>;
  licenses?: string[] | Computed<string[]>;
  multiWriter?: boolean | Computed<boolean>;
  onUpdateAction?: string | Computed<string>;
  provisionedIops?: string | Computed<string>;
  provisionedThroughput?: string | Computed<string>;
  replicaZones?: string[] | Computed<string[]>;
  resourceManagerTags?: Record<string, string> | Computed<Record<string, string>>;
  resourcePolicies?: string[] | Computed<string[]>;
  sourceImage?: string | Computed<string>;
  sourceImageEncryptionKey?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKey | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKey>;
  sourceInstantSnapshot?: string | Computed<string>;
  sourceSnapshot?: string | Computed<string>;
  sourceSnapshotEncryptionKey?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKey | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKey>;
  storagePool?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs {
  content?: string | Computed<string>;
  fileType?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState {
  dbs?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs[]>;
  dbxs?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs[]>;
  keks?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs[]>;
  pk?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_Dbs>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks {
  architecture?: string | Computed<string>;
  autoDelete?: boolean | Computed<boolean>;
  boot?: boolean | Computed<boolean>;
  deviceName?: string | Computed<string>;
  diskEncryptionKey?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKey | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKey>;
  diskSizeGb?: string | Computed<string>;
  forceAttach?: boolean | Computed<boolean>;
  guestOsFeatures?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_GuestOsFeatures[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_GuestOsFeatures[]>;
  index?: number | Computed<number>;
  initializeParams?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_InitializeParams | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_InitializeParams>;
  interface?: string | Computed<string>;
  kind?: string | Computed<string>;
  licenses?: string[] | Computed<string[]>;
  locked?: boolean | Computed<boolean>;
  mode?: string | Computed<string>;
  savedState?: string | Computed<string>;
  shieldedInstanceInitialState?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState>;
  source?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections {
  disks?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks[]>;
  machineTypes?: string[] | Computed<string[]>;
  minCpuPlatform?: string | Computed<string>;
  rank?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy {
  /** Specification of alternative, flexible instance subsets. One of them will be selected to create the instances based on various criteria, like: - ranks, - location policy, - current capacity, - available reservations (you can specify affinity in InstanceProperties), - SWAN/GOOSE limitations. Key is an arbitrary, unique RFC1035 string that identifies the instance selection. */
  instanceSelections?: Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections> | Computed<Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections>>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_AdvancedMachineFeatures {
  /** Whether to enable nested virtualization or not (default is false). */
  enableNestedVirtualization?: boolean | Computed<boolean>;
  /** Whether to enable UEFI networking for instance creation. */
  enableUefiNetworking?: boolean | Computed<boolean>;
  /** Whether to enable the watchdog timer. */
  enableWatchdogTimer?: boolean | Computed<boolean>;
  /** The number of vNUMA nodes. */
  numaNodeCount?: number | Computed<number>;
  /** Type of Performance Monitoring Unit requested on instance. */
  performanceMonitoringUnit?: string | Computed<string>;
  /** The number of threads per physical core. To disable simultaneous multithreading (SMT) set this to 1. If unset, the maximum number of threads supported per core by the underlying processor is assumed. */
  threadsPerCore?: number | Computed<number>;
  /** Turbo frequency mode to use for the instance. Supported modes include: * ALL_CORE_MAX Using empty string or not setting this field will use the platform-specific default turbo mode. */
  turboMode?: string | Computed<string>;
  /** The number of physical cores to expose to an instance. Multiply by the number of threads per core to compute the total number of virtual CPUs to expose to the instance. If unset, the number of cores is inferred from the instance's nominal CPU count and the underlying platform's SMT width. */
  visibleCoreCount?: number | Computed<number>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfig_ConfidentialParavisorConfig {
  confidentialTpmType?: string | Computed<string>;
  sevSnpIrqMode?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfig {
  /** Defines the type of technology used by the confidential instance. */
  confidentialInstanceType?: string | Computed<string>;
  /** A set of Confidential Paravisor (SVSM) options. */
  confidentialParavisorConfig?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfig_ConfidentialParavisorConfig | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfig_ConfidentialParavisorConfig>;
  /** Defines whether the instance should have confidential compute enabled. */
  enableConfidentialCompute?: boolean | Computed<boolean>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_DisplayDevice {
  /** Defines whether the instance has Display enabled. */
  enableDisplay?: boolean | Computed<boolean>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_GuestAccelerators {
  acceleratorCount?: number | Computed<number>;
  acceleratorType?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Metadata_Items {
  key?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Metadata {
  /** Specifies a fingerprint for this request, which is essentially a hash of the metadata's contents and used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update metadata. You must always provide an up-to-date fingerprint hash in order to update or change metadata, otherwise the request will fail with error412 conditionNotMet. To see the latest fingerprint, make a get() request to retrieve the resource. */
  fingerprint?: string | Computed<string>;
  /** Array of key/value pairs. The total size of all keys and values must be less than 512 KB. */
  items?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Metadata_Items[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Metadata_Items[]>;
  /** Output only. [Output Only] Type of the resource. Always compute#metadata for metadata. */
  kind?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AccessConfigs {
  externalIpv6?: string | Computed<string>;
  externalIpv6PrefixLength?: number | Computed<number>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  natIp?: string | Computed<string>;
  networkTier?: string | Computed<string>;
  publicDnsName?: string | Computed<string>;
  publicPtrDomainName?: string | Computed<string>;
  securityPolicy?: string | Computed<string>;
  setPublicDns?: boolean | Computed<boolean>;
  setPublicPtr?: boolean | Computed<boolean>;
  type?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AliasIpRanges {
  candidateSubnetworkRangeNames?: string[] | Computed<string[]>;
  effectiveSubnetworkRangeName?: string | Computed<string>;
  ipCidrRange?: string | Computed<string>;
  subnetworkRangeName?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_Subinterfaces {
  ipAddress?: string | Computed<string>;
  ipAllocationMode?: string | Computed<string>;
  subnetwork?: string | Computed<string>;
  vlan?: number | Computed<number>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces {
  accessConfigs?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AccessConfigs[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AccessConfigs[]>;
  aliasIpRanges?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AliasIpRanges[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AliasIpRanges[]>;
  aliasIpv6Ranges?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AliasIpRanges[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AliasIpRanges[]>;
  dns64Eligible?: boolean | Computed<boolean>;
  enableVpcScopedDns?: boolean | Computed<boolean>;
  fingerprint?: string | Computed<string>;
  igmpQuery?: string | Computed<string>;
  internalIpv6PrefixLength?: number | Computed<number>;
  internalNicLoadBalancingIpv6Address?: string | Computed<string>;
  internalNicLoadBalancingIpv6PrefixLength?: number | Computed<number>;
  ipv6AccessConfigs?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AccessConfigs[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AccessConfigs[]>;
  ipv6AccessType?: string | Computed<string>;
  ipv6Address?: string | Computed<string>;
  kind?: string | Computed<string>;
  macAddress?: string | Computed<string>;
  name?: string | Computed<string>;
  nat64Eligible?: boolean | Computed<boolean>;
  network?: string | Computed<string>;
  networkAttachment?: string | Computed<string>;
  networkIp?: string | Computed<string>;
  nicType?: string | Computed<string>;
  parentNicName?: string | Computed<string>;
  queueCount?: number | Computed<number>;
  serviceClassId?: string | Computed<string>;
  stackType?: string | Computed<string>;
  subinterfaces?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_Subinterfaces[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_Subinterfaces[]>;
  subnetwork?: string | Computed<string>;
  vlan?: number | Computed<number>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkPerformanceConfig {
  externalIpEgressBandwidthTier?: string | Computed<string>;
  totalEgressBandwidthTier?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_PartnerMetadata {
  entries?: Record<string, unknown> | Computed<Record<string, unknown>>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ReservationAffinity {
  /** Specifies the type of reservation from which this instance can consume resources: ANY_RESERVATION (default),SPECIFIC_RESERVATION, or NO_RESERVATION. See Consuming reserved instances for examples. */
  consumeReservationType?: string | Computed<string>;
  /** Corresponds to the label key of a reservation resource. To target aSPECIFIC_RESERVATION by name, specifygoogleapis.com/reservation-name as the key and specify the name of your reservation as its value. */
  key?: string | Computed<string>;
  /** Corresponds to the label values of a reservation resource. This can be either a name to a reservation in the same project or "projects/different-project/reservations/some-reservation-name" to target a shared reservation in the same zone but in a different project. */
  values?: string[] | Computed<string[]>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration {
  /** Span of time that's a fraction of a second at nanosecond resolution. Durations less than one second are represented with a 0 `seconds` field and a positive `nanos` field. Must be from 0 to 999,999,999 inclusive. */
  nanos?: number | Computed<number>;
  /** Span of time at a resolution of a second. Must be from 0 to 315,576,000,000 inclusive. Note: these bounds are computed from: 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years */
  seconds?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown {
  /** Opts-in for graceful shutdown. */
  enabled?: boolean | Computed<boolean>;
  /** A Duration represents a fixed-length span of time represented as a count of seconds and fractions of seconds at nanosecond resolution. It is independent of any calendar and concepts like "day" or "month". Range is approximately 10,000 years. */
  maxDuration?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_NodeAffinities {
  key?: string | Computed<string>;
  operator?: string | Computed<string>;
  values?: string[] | Computed<string[]>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_OnInstanceStopAction {
  /** If true, the contents of any attached Local SSD disks will be discarded else, the Local SSD data will be preserved when the instance is stopped at the end of the run duration/termination time. */
  discardLocalSsd?: boolean | Computed<boolean>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_VsockMode {
  mode?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling {
  /** Specifies whether the instance should be automatically restarted if it is terminated by Compute Engine (not terminated by a user). You can only set the automatic restart option for standard instances.Preemptible instances cannot be automatically restarted. By default, this is set to true so an instance is automatically restarted if it is terminated by Compute Engine. */
  automaticRestart?: boolean | Computed<boolean>;
  /** Specifies the availability domain to place the instance in. The value must be a number between 1 and the number of availability domains specified in the spread placement policy attached to the instance. */
  availabilityDomain?: number | Computed<number>;
  /** Current number of vCPUs available for VM. 0 or unset means default vCPUs of the current machine type. */
  currentCpus?: number | Computed<number>;
  /** Current amount of memory (in MB) available for VM. 0 or unset means default amount of memory of the current machine type. */
  currentMemoryMb?: string | Computed<string>;
  /** This optional flag exposes the hashed physical host ID in the ResourceStatus resource of the VM. */
  exposeHostTopology?: boolean | Computed<boolean>;
  /** The configuration for gracefully shutting down the instance. */
  gracefulShutdown?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown>;
  /** Specify the time in seconds for host error detection, the value must be within the range of [90, 330] with the increment of 30, if unset, the default behavior of host error recovery will be used. */
  hostErrorTimeoutSeconds?: number | Computed<number>;
  /** Specifies the termination action for the instance. */
  instanceTerminationAction?: string | Computed<string>;
  /** Defines whether the instance is tolerant of higher cpu latency. This can only be set during instance creation, or when the instance is not currently running. It must not be set if thepreemptible option is also set. */
  latencyTolerant?: boolean | Computed<boolean>;
  /** A Duration represents a fixed-length span of time represented as a count of seconds and fractions of seconds at nanosecond resolution. It is independent of any calendar and concepts like "day" or "month". Range is approximately 10,000 years. */
  localSsdRecoveryTimeout?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration>;
  /** An opaque location hint used to place the instance close to other resources. This field is for use by internal tools that use the public API. */
  locationHint?: string | Computed<string>;
  /** Specifies the number of hours after VM instance creation where the VM won't be scheduled for maintenance. */
  maintenanceFreezeDurationHours?: number | Computed<number>;
  /** Specifies the frequency of planned maintenance events. The accepted values are: `PERIODIC`. */
  maintenanceInterval?: string | Computed<string>;
  /** A Duration represents a fixed-length span of time represented as a count of seconds and fractions of seconds at nanosecond resolution. It is independent of any calendar and concepts like "day" or "month". Range is approximately 10,000 years. */
  maxRunDuration?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration>;
  /** The minimum number of virtual CPUs this instance will consume when running on a sole-tenant node. */
  minNodeCpus?: number | Computed<number>;
  /** A set of node affinity and anti-affinity configurations. Refer toConfiguring node affinity for more information. Overrides reservationAffinity. */
  nodeAffinities?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_NodeAffinities[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_NodeAffinities[]>;
  /** Defines the maintenance behavior for this instance. For standard instances, the default behavior is MIGRATE. Forpreemptible instances, the default and only possible behavior is TERMINATE. For more information, see Set VM host maintenance policy. */
  onHostMaintenance?: string | Computed<string>;
  /** Defines the behaviour for instances with the instance_termination_actionSTOP. */
  onInstanceStopAction?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_OnInstanceStopAction | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_OnInstanceStopAction>;
  /** Defines whether the instance is preemptible. This can only be set during instance creation or while the instance isstopped and therefore, in a `TERMINATED` state. SeeInstance Life Cycle for more information on the possible instance states. */
  preemptible?: boolean | Computed<boolean>;
  /** A Duration represents a fixed-length span of time represented as a count of seconds and fractions of seconds at nanosecond resolution. It is independent of any calendar and concepts like "day" or "month". Range is approximately 10,000 years. */
  preemptionNoticeDuration?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration>;
  /** Specifies the provisioning model of the instance. */
  provisioningModel?: string | Computed<string>;
  /** A Duration represents a fixed-length span of time represented as a count of seconds and fractions of seconds at nanosecond resolution. It is independent of any calendar and concepts like "day" or "month". Range is approximately 10,000 years. */
  shutdownTimeout?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration>;
  /** Default is false and there will be 120 seconds between GCE ACPI G2 Soft Off and ACPI G3 Mechanical Off for Standard VMs and 30 seconds for Spot VMs. */
  skipGuestOsShutdown?: boolean | Computed<boolean>;
  /** Specifies the timestamp, when the instance will be terminated, inRFC3339 text format. If specified, the instance termination action will be performed at the termination time. */
  terminationTime?: string | Computed<string>;
  /** Message to control the enablement of the vsock device. */
  vsockMode?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_VsockMode | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_VsockMode>;
  /** Represents the Windows Server License Optimization Mode of the VM. If unspecified, the default mode is `OFF`. */
  windowsLicenseOptimizationMode?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceAccounts {
  email?: string | Computed<string>;
  scopes?: string[] | Computed<string[]>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecs_BackupDr {
  plan?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecs {
  backupDr?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecs_BackupDr | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecs_BackupDr>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ShieldedInstanceConfig {
  /** Defines whether the instance has integrity monitoring enabled.Enabled by default. */
  enableIntegrityMonitoring?: boolean | Computed<boolean>;
  /** Defines whether the instance has Secure Boot enabled.Disabled by default. */
  enableSecureBoot?: boolean | Computed<boolean>;
  /** Defines whether the instance has the vTPM enabled.Enabled by default. */
  enableVtpm?: boolean | Computed<boolean>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Tags {
  /** Specifies a fingerprint for this request, which is essentially a hash of the tags' contents and used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update tags. You must always provide an up-to-date fingerprint hash in order to update or change tags. To see the latest fingerprint, make get() request to the instance. */
  fingerprint?: string | Computed<string>;
  /** An array of tags. Each tag must be 1-63 characters long, and comply with RFC1035. */
  items?: string[] | Computed<string[]>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_WorkloadIdentityConfig {
  identity?: string | Computed<string>;
  identityCertificateEnabled?: boolean | Computed<boolean>;
  identityType?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties {
  /** Specifies options for controlling advanced machine features. Options that would traditionally be configured in a BIOS belong here. Features that require operating system support may have corresponding entries in the GuestOsFeatures of anImage (e.g., whether or not the OS in theImage supports nested virtualization being enabled or disabled). */
  advancedMachineFeatures?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_AdvancedMachineFeatures | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_AdvancedMachineFeatures>;
  /** Enables instances created based on these properties to send packets with source IP addresses other than their own and receive packets with destination IP addresses other than their own. If these instances will be used as an IP gateway or it will be set as the next-hop in a Route resource, specify true. If unsure, leave this set tofalse. See theEnable IP forwarding documentation for more information. */
  canIpForward?: boolean | Computed<boolean>;
  /** A set of Confidential Instance options. */
  confidentialInstanceConfig?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfig | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfig>;
  /** An optional text description for the instances that are created from these properties. */
  description?: string | Computed<string>;
  /** An array of disks that are associated with the instances that are created from these properties. */
  disks?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks[]>;
  /** A set of Display Device options */
  displayDevice?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_DisplayDevice | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_DisplayDevice>;
  /** A list of guest accelerator cards' type and count to use for instances created from these properties. */
  guestAccelerators?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_GuestAccelerators[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_GuestAccelerators[]>;
  identity?: string | Computed<string>;
  identityCertificate?: boolean | Computed<boolean>;
  /** KeyRevocationActionType of the instance. Supported options are "STOP" and "NONE". The default value is "NONE" if it is not specified. */
  keyRevocationActionType?: string | Computed<string>;
  /** Labels to apply to instances that are created from these properties. */
  labels?: Record<string, string> | Computed<Record<string, string>>;
  /** Specifies which method should be used for encrypting the Local SSDs attached to the VM. */
  localSsdEncryptionMode?: string | Computed<string>;
  /** The machine type to use for instances that are created from these properties. This field only accepts a machine type name, for example `n2-standard-4`. If you use the machine type full or partial URL, for example `projects/my-l7ilb-project/zones/us-central1-a/machineTypes/n2-standard-4`, the request will result in an `INTERNAL_ERROR`. */
  machineType?: string | Computed<string>;
  /** A metadata key/value entry. */
  metadata?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Metadata | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Metadata>;
  /** Minimum cpu/platform to be used by instances. The instance may be scheduled on the specified or newer cpu/platform. Applicable values are the friendly names of CPU platforms, such asminCpuPlatform: "Intel Haswell" orminCpuPlatform: "Intel Sandy Bridge". For more information, read Specifying a Minimum CPU Platform. */
  minCpuPlatform?: string | Computed<string>;
  /** An array of network access configurations for this interface. */
  networkInterfaces?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces[]>;
  networkPerformanceConfig?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkPerformanceConfig | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkPerformanceConfig>;
  /** Partner Metadata assigned to the instance properties. A map from a subdomain (namespace) to entries map. */
  partnerMetadata?: Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_PartnerMetadata> | Computed<Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_PartnerMetadata>>;
  /** PostKeyRevocationActionType of the instance. */
  postKeyRevocationActionType?: string | Computed<string>;
  /** The private IPv6 google access type for VMs. If not specified, use INHERIT_FROM_SUBNETWORK as default. Note that for MachineImage, this is not supported yet. */
  privateIpv6GoogleAccess?: string | Computed<string>;
  /** Specifies the reservations that this instance can consume from. */
  reservationAffinity?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ReservationAffinity | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ReservationAffinity>;
  /** Input only. Resource manager tags to be bound to the instance. Tag keys and values have the same definition as resource manager tags. Keys and values can be either in numeric format, such as `tagKeys/{tag_key_id}` and `tagValues/{tag_value_id}` or in namespaced format such as `{org_id|project_id}/{tag_key_short_name}` and `{tag_value_short_name}`. The field is ignored (both PUT & PATCH) when empty. */
  resourceManagerTags?: Record<string, string> | Computed<Record<string, string>>;
  /** Resource policies (names, not URLs) applied to instances created from these properties. Note that for MachineImage, this is not supported yet. */
  resourcePolicies?: string[] | Computed<string[]>;
  /** Sets the scheduling options for an Instance. */
  scheduling?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling>;
  /** [Input Only] Secure tags to apply to this instance. Maximum number of secure tags allowed is 50. Note that for MachineImage, this is not supported yet. */
  secureTags?: string[] | Computed<string[]>;
  /** A list of service accounts with specified scopes. Access tokens for these service accounts are available to the instances that are created from these properties. Use metadata queries to obtain the access tokens for these instances. */
  serviceAccounts?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceAccounts[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceAccounts[]>;
  /** Mapping of user defined keys to ServiceIntegrationSpec. */
  serviceIntegrationSpecs?: Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecs> | Computed<Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecs>>;
  /** A set of Shielded Instance options. */
  shieldedInstanceConfig?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ShieldedInstanceConfig | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ShieldedInstanceConfig>;
  /** A set of Shielded VM options. */
  shieldedVmConfig?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ShieldedInstanceConfig | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ShieldedInstanceConfig>;
  /** A set of instance tags. */
  tags?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Tags | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Tags>;
  workloadIdentityConfig?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_WorkloadIdentityConfig | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_WorkloadIdentityConfig>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Locations_Constraints {
  maxCount?: number | Computed<number>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Locations {
  constraints?: AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Locations_Constraints | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Locations_Constraints>;
  names?: string[] | Computed<string[]>;
  preference?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Zones {
  zone?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy {
  /** Location configurations mapped by location name. Currently only zone names are supported and must be represented as valid internal URLs, such as zones/us-central1-a. The bulkInsert operation doesn't create instances in an AI zone, even if an AI zone is available in the specified region. For example, if you set a DENY preference for us-central1-a, Compute Engine will consider us-central1-b and us-central1-c for instance creation, but not us-central1-ai1a. Also, you can't use the locations[] configuration to allow instance creation in an AI zone. To include an AI zone in bulkInsert operations, use the locationPolicy.zones[] field. */
  locations?: Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Locations> | Computed<Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Locations>>;
  /** Strategy for distributing VMs across zones in a region. */
  targetShape?: string | Computed<string>;
  /** The bulkInsert operation applies any preferences set in the locations field to the specific zones listed in the zones field if the same zones are specified in both fields. */
  zones?: AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Zones[] | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Zones[]>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource_PerInstanceProperties {
  hostname?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_BulkInsertInstanceResource {
  /** The maximum number of instances to create. */
  count?: string | Computed<string>;
  /** A flexible specification of machine types for instances to create. */
  instanceFlexibilityPolicy?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy>;
  instanceProperties?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties>;
  /** Configuration for location policy among multiple possible locations (e.g. preferences for zone selection among zones in a single region). */
  locationPolicy?: AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy>;
  /** The minimum number of instances to create. If no min_count is specified then count is used as the default value. Ifmin_count instances cannot be created, then no instances will be created and instances already created will be deleted. */
  minCount?: string | Computed<string>;
  /** The string pattern used for the names of the VMs. Either name_pattern or per_instance_properties must be set. The pattern must contain one continuous sequence of placeholder hash characters (#) with each character corresponding to one digit of the generated instance name. Example: a name_pattern of inst-#### generates instance names such asinst-0001 and inst-0002. If existing instances in the same project and zone have names that match the name pattern then the generated instance numbers start after the biggest existing number. For example, if there exists an instance with nameinst-0050, then instance names generated using the patterninst-#### begin with inst-0051. The name pattern placeholder #...# can contain up to 18 characters. */
  namePattern?: string | Computed<string>;
  /** Per-instance properties to be set on individual instances. Keys of this map specify requested instance names. Can be empty if name_pattern is used. */
  perInstanceProperties?: Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_PerInstanceProperties> | Computed<Record<string, AlphaZoneQueuedResource_BulkInsertInstanceResource_PerInstanceProperties>>;
  /** Specifies the instance template from which to create instances. You may combine sourceInstanceTemplate withinstanceProperties to override specific values from an existing instance template. Bulk API follows the semantics of JSON Merge Patch described by RFC 7396. It can be a full or partial URL. For example, the following are all valid URLs to an instance template: - https://www.googleapis.com/compute/v1/projects/project/global/instanceTemplates/instanceTemplate - projects/project/global/instanceTemplates/instanceTemplate - global/instanceTemplates/instanceTemplate This field is optional. */
  sourceInstanceTemplate?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_QueuingPolicy {
  /** A Duration represents a fixed-length span of time represented as a count of seconds and fractions of seconds at nanosecond resolution. It is independent of any calendar and concepts like "day" or "month". Range is approximately 10,000 years. */
  validUntilDuration?: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDuration>;
  /** Absolute deadline for waiting for capacity inRFC3339 text format. */
  validUntilTime?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_ErrorInfo {
  domain?: string | Computed<string>;
  metadatas?: Record<string, string> | Computed<Record<string, string>>;
  reason?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_Help_Links {
  description?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_Help {
  links?: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_Help_Links[] | Computed<AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_Help_Links[]>;
}

export interface AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_LocalizedMessage {
  locale?: string | Computed<string>;
  message?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_QuotaInfo {
  dimensions?: Record<string, string> | Computed<Record<string, string>>;
  futureLimit?: number | Computed<number>;
  limit?: number | Computed<number>;
  limitName?: string | Computed<string>;
  metricName?: string | Computed<string>;
  rolloutStatus?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails {
  errorInfo?: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_ErrorInfo | Computed<AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_ErrorInfo>;
  help?: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_Help | Computed<AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_Help>;
  localizedMessage?: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_LocalizedMessage | Computed<AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_LocalizedMessage>;
  quotaInfo?: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_QuotaInfo | Computed<AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_QuotaInfo>;
}

export interface AlphaZoneQueuedResource_Status_FailedData_Error_Errors {
  code?: string | Computed<string>;
  errorDetails?: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails[] | Computed<AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails[]>;
  location?: string | Computed<string>;
  message?: string | Computed<string>;
}

export interface AlphaZoneQueuedResource_Status_FailedData_Error {
  /** [Output Only] The array of errors encountered while processing this operation. */
  errors?: AlphaZoneQueuedResource_Status_FailedData_Error_Errors[] | Computed<AlphaZoneQueuedResource_Status_FailedData_Error_Errors[]>;
}

export interface AlphaZoneQueuedResource_Status_FailedData {
  /** The error(s) that caused the QueuedResource to enter the FAILED state. */
  error?: AlphaZoneQueuedResource_Status_FailedData_Error | Computed<AlphaZoneQueuedResource_Status_FailedData_Error>;
}

export interface AlphaZoneQueuedResource_Status {
  /** Additional status detail for the FAILED state. */
  failedData?: AlphaZoneQueuedResource_Status_FailedData | Computed<AlphaZoneQueuedResource_Status_FailedData>;
  /** Output only. [Output only] Fully qualified URL of the provisioning GCE operation to track the provisioning along with provisioning errors. The referenced operation may not exist after having been deleted or expired. */
  provisioningOperations?: string[] | Computed<string[]>;
  /** Queuing parameters for the requested deferred capacity. */
  queuingPolicy?: AlphaZoneQueuedResource_QueuingPolicy | Computed<AlphaZoneQueuedResource_QueuingPolicy>;
}

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKeyFields: FieldMap = {
  kmsKeyName: "kms_key_name",
  kmsKeyServiceAccount: "kms_key_service_account",
  rawKey: "raw_key",
  rsaEncryptedKey: "rsa_encrypted_key",
  sha256: "sha256",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_GuestOsFeaturesFields: FieldMap = {
  type: "type",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_InitializeParamsFields: FieldMap = {
  architecture: "architecture",
  description: "description",
  diskName: "disk_name",
  diskSizeGb: "disk_size_gb",
  diskType: "disk_type",
  enableConfidentialCompute: "enable_confidential_compute",
  guestOsFeatures: {
    wireName: "guest_os_features",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_GuestOsFeaturesFields,
  },
  interface: "interface",
  labels: "labels",
  licenseCodes: "license_codes",
  licenses: "licenses",
  multiWriter: "multi_writer",
  onUpdateAction: "on_update_action",
  provisionedIops: "provisioned_iops",
  provisionedThroughput: "provisioned_throughput",
  replicaZones: "replica_zones",
  resourceManagerTags: "resource_manager_tags",
  resourcePolicies: "resource_policies",
  sourceImage: "source_image",
  sourceImageEncryptionKey: {
    wireName: "source_image_encryption_key",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKeyFields,
  },
  sourceInstantSnapshot: "source_instant_snapshot",
  sourceSnapshot: "source_snapshot",
  sourceSnapshotEncryptionKey: {
    wireName: "source_snapshot_encryption_key",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKeyFields,
  },
  storagePool: "storage_pool",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_DbsFields: FieldMap = {
  content: "content",
  fileType: "file_type",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialStateFields: FieldMap = {
  dbs: {
    wireName: "dbs",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_DbsFields,
  },
  dbxs: {
    wireName: "dbxs",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_DbsFields,
  },
  keks: {
    wireName: "keks",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_DbsFields,
  },
  pk: {
    wireName: "pk",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialState_DbsFields,
  },
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_DisksFields: FieldMap = {
  architecture: "architecture",
  autoDelete: "auto_delete",
  boot: "boot",
  deviceName: "device_name",
  diskEncryptionKey: {
    wireName: "disk_encryption_key",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_DiskEncryptionKeyFields,
  },
  diskSizeGb: "disk_size_gb",
  forceAttach: "force_attach",
  guestOsFeatures: {
    wireName: "guest_os_features",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_GuestOsFeaturesFields,
  },
  index: "index",
  initializeParams: {
    wireName: "initialize_params",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_InitializeParamsFields,
  },
  interface: "interface",
  kind: "kind",
  licenses: "licenses",
  locked: "locked",
  mode: "mode",
  savedState: "saved_state",
  shieldedInstanceInitialState: {
    wireName: "shielded_instance_initial_state",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_Disks_ShieldedInstanceInitialStateFields,
  },
  source: "source",
  type: "type",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelectionsFields: FieldMap = {
  disks: {
    wireName: "disks",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_DisksFields,
  },
  machineTypes: "machine_types",
  minCpuPlatform: "min_cpu_platform",
  rank: "rank",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicyFields: FieldMap = {
  instanceSelections: {
    wireName: "instance_selections",
    kind: "map",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelectionsFields,
  },
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_AdvancedMachineFeaturesFields: FieldMap = {
  enableNestedVirtualization: "enable_nested_virtualization",
  enableUefiNetworking: "enable_uefi_networking",
  enableWatchdogTimer: "enable_watchdog_timer",
  numaNodeCount: "numa_node_count",
  performanceMonitoringUnit: "performance_monitoring_unit",
  threadsPerCore: "threads_per_core",
  turboMode: "turbo_mode",
  visibleCoreCount: "visible_core_count",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfig_ConfidentialParavisorConfigFields: FieldMap = {
  confidentialTpmType: "confidential_tpm_type",
  sevSnpIrqMode: "sev_snp_irq_mode",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfigFields: FieldMap = {
  confidentialInstanceType: "confidential_instance_type",
  confidentialParavisorConfig: {
    wireName: "confidential_paravisor_config",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfig_ConfidentialParavisorConfigFields,
  },
  enableConfidentialCompute: "enable_confidential_compute",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_DisplayDeviceFields: FieldMap = {
  enableDisplay: "enable_display",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_GuestAcceleratorsFields: FieldMap = {
  acceleratorCount: "accelerator_count",
  acceleratorType: "accelerator_type",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Metadata_ItemsFields: FieldMap = {
  key: "key",
  value: "value",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_MetadataFields: FieldMap = {
  fingerprint: "fingerprint",
  items: {
    wireName: "items",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Metadata_ItemsFields,
  },
  kind: "kind",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AccessConfigsFields: FieldMap = {
  externalIpv6: "external_ipv6",
  externalIpv6PrefixLength: "external_ipv6_prefix_length",
  kind: "kind",
  name: "name",
  natIp: "nat_ip",
  networkTier: "network_tier",
  publicDnsName: "public_dns_name",
  publicPtrDomainName: "public_ptr_domain_name",
  securityPolicy: "security_policy",
  setPublicDns: "set_public_dns",
  setPublicPtr: "set_public_ptr",
  type: "type",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AliasIpRangesFields: FieldMap = {
  candidateSubnetworkRangeNames: "candidate_subnetwork_range_names",
  effectiveSubnetworkRangeName: "effective_subnetwork_range_name",
  ipCidrRange: "ip_cidr_range",
  subnetworkRangeName: "subnetwork_range_name",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_SubinterfacesFields: FieldMap = {
  ipAddress: "ip_address",
  ipAllocationMode: "ip_allocation_mode",
  subnetwork: "subnetwork",
  vlan: "vlan",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfacesFields: FieldMap = {
  accessConfigs: {
    wireName: "access_configs",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AccessConfigsFields,
  },
  aliasIpRanges: {
    wireName: "alias_ip_ranges",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AliasIpRangesFields,
  },
  aliasIpv6Ranges: {
    wireName: "alias_ipv6_ranges",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AliasIpRangesFields,
  },
  dns64Eligible: "dns64_eligible",
  enableVpcScopedDns: "enable_vpc_scoped_dns",
  fingerprint: "fingerprint",
  igmpQuery: "igmp_query",
  internalIpv6PrefixLength: "internal_ipv6_prefix_length",
  internalNicLoadBalancingIpv6Address: "internal_nic_load_balancing_ipv6_address",
  internalNicLoadBalancingIpv6PrefixLength: "internal_nic_load_balancing_ipv6_prefix_length",
  ipv6AccessConfigs: {
    wireName: "ipv6_access_configs",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_AccessConfigsFields,
  },
  ipv6AccessType: "ipv6_access_type",
  ipv6Address: "ipv6_address",
  kind: "kind",
  macAddress: "mac_address",
  name: "name",
  nat64Eligible: "nat64_eligible",
  network: "network",
  networkAttachment: "network_attachment",
  networkIp: "network_ip",
  nicType: "nic_type",
  parentNicName: "parent_nic_name",
  queueCount: "queue_count",
  serviceClassId: "service_class_id",
  stackType: "stack_type",
  subinterfaces: {
    wireName: "subinterfaces",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfaces_SubinterfacesFields,
  },
  subnetwork: "subnetwork",
  vlan: "vlan",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkPerformanceConfigFields: FieldMap = {
  externalIpEgressBandwidthTier: "external_ip_egress_bandwidth_tier",
  totalEgressBandwidthTier: "total_egress_bandwidth_tier",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_PartnerMetadataFields: FieldMap = {
  entries: "entries",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ReservationAffinityFields: FieldMap = {
  consumeReservationType: "consume_reservation_type",
  key: "key",
  values: "values",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDurationFields: FieldMap = {
  nanos: "nanos",
  seconds: "seconds",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdownFields: FieldMap = {
  enabled: "enabled",
  maxDuration: {
    wireName: "max_duration",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDurationFields,
  },
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_NodeAffinitiesFields: FieldMap = {
  key: "key",
  operator: "operator",
  values: "values",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_OnInstanceStopActionFields: FieldMap = {
  discardLocalSsd: "discard_local_ssd",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_VsockModeFields: FieldMap = {
  mode: "mode",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_SchedulingFields: FieldMap = {
  automaticRestart: "automatic_restart",
  availabilityDomain: "availability_domain",
  currentCpus: "current_cpus",
  currentMemoryMb: "current_memory_mb",
  exposeHostTopology: "expose_host_topology",
  gracefulShutdown: {
    wireName: "graceful_shutdown",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdownFields,
  },
  hostErrorTimeoutSeconds: "host_error_timeout_seconds",
  instanceTerminationAction: "instance_termination_action",
  latencyTolerant: "latency_tolerant",
  localSsdRecoveryTimeout: {
    wireName: "local_ssd_recovery_timeout",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDurationFields,
  },
  locationHint: "location_hint",
  maintenanceFreezeDurationHours: "maintenance_freeze_duration_hours",
  maintenanceInterval: "maintenance_interval",
  maxRunDuration: {
    wireName: "max_run_duration",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDurationFields,
  },
  minNodeCpus: "min_node_cpus",
  nodeAffinities: {
    wireName: "node_affinities",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_NodeAffinitiesFields,
  },
  onHostMaintenance: "on_host_maintenance",
  onInstanceStopAction: {
    wireName: "on_instance_stop_action",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_OnInstanceStopActionFields,
  },
  preemptible: "preemptible",
  preemptionNoticeDuration: {
    wireName: "preemption_notice_duration",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDurationFields,
  },
  provisioningModel: "provisioning_model",
  shutdownTimeout: {
    wireName: "shutdown_timeout",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDurationFields,
  },
  skipGuestOsShutdown: "skip_guest_os_shutdown",
  terminationTime: "termination_time",
  vsockMode: {
    wireName: "vsock_mode",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_VsockModeFields,
  },
  windowsLicenseOptimizationMode: "windows_license_optimization_mode",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceAccountsFields: FieldMap = {
  email: "email",
  scopes: "scopes",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecs_BackupDrFields: FieldMap = {
  plan: "plan",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecsFields: FieldMap = {
  backupDr: {
    wireName: "backup_dr",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecs_BackupDrFields,
  },
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ShieldedInstanceConfigFields: FieldMap = {
  enableIntegrityMonitoring: "enable_integrity_monitoring",
  enableSecureBoot: "enable_secure_boot",
  enableVtpm: "enable_vtpm",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_TagsFields: FieldMap = {
  fingerprint: "fingerprint",
  items: "items",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_WorkloadIdentityConfigFields: FieldMap = {
  identity: "identity",
  identityCertificateEnabled: "identity_certificate_enabled",
  identityType: "identity_type",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_InstancePropertiesFields: FieldMap = {
  advancedMachineFeatures: {
    wireName: "advanced_machine_features",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_AdvancedMachineFeaturesFields,
  },
  canIpForward: "can_ip_forward",
  confidentialInstanceConfig: {
    wireName: "confidential_instance_config",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ConfidentialInstanceConfigFields,
  },
  description: "description",
  disks: {
    wireName: "disks",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicy_InstanceSelections_DisksFields,
  },
  displayDevice: {
    wireName: "display_device",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_DisplayDeviceFields,
  },
  guestAccelerators: {
    wireName: "guest_accelerators",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_GuestAcceleratorsFields,
  },
  identity: "identity",
  identityCertificate: "identity_certificate",
  keyRevocationActionType: "key_revocation_action_type",
  labels: "labels",
  localSsdEncryptionMode: "local_ssd_encryption_mode",
  machineType: "machine_type",
  metadata: {
    wireName: "metadata",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_MetadataFields,
  },
  minCpuPlatform: "min_cpu_platform",
  networkInterfaces: {
    wireName: "network_interfaces",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkInterfacesFields,
  },
  networkPerformanceConfig: {
    wireName: "network_performance_config",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_NetworkPerformanceConfigFields,
  },
  partnerMetadata: {
    wireName: "partner_metadata",
    kind: "map",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_PartnerMetadataFields,
  },
  postKeyRevocationActionType: "post_key_revocation_action_type",
  privateIpv6GoogleAccess: "private_ipv6_google_access",
  reservationAffinity: {
    wireName: "reservation_affinity",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ReservationAffinityFields,
  },
  resourceManagerTags: "resource_manager_tags",
  resourcePolicies: "resource_policies",
  scheduling: {
    wireName: "scheduling",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_SchedulingFields,
  },
  secureTags: "secure_tags",
  serviceAccounts: {
    wireName: "service_accounts",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceAccountsFields,
  },
  serviceIntegrationSpecs: {
    wireName: "service_integration_specs",
    kind: "map",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ServiceIntegrationSpecsFields,
  },
  shieldedInstanceConfig: {
    wireName: "shielded_instance_config",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ShieldedInstanceConfigFields,
  },
  shieldedVmConfig: {
    wireName: "shielded_vm_config",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_ShieldedInstanceConfigFields,
  },
  tags: {
    wireName: "tags",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_TagsFields,
  },
  workloadIdentityConfig: {
    wireName: "workload_identity_config",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_WorkloadIdentityConfigFields,
  },
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Locations_ConstraintsFields: FieldMap = {
  maxCount: "max_count",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_LocationsFields: FieldMap = {
  constraints: {
    wireName: "constraints",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_Locations_ConstraintsFields,
  },
  names: "names",
  preference: "preference",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_ZonesFields: FieldMap = {
  zone: "zone",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicyFields: FieldMap = {
  locations: {
    wireName: "locations",
    kind: "map",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_LocationsFields,
  },
  targetShape: "target_shape",
  zones: {
    wireName: "zones",
    kind: "list",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicy_ZonesFields,
  },
};

const AlphaZoneQueuedResource_BulkInsertInstanceResource_PerInstancePropertiesFields: FieldMap = {
  hostname: "hostname",
  name: "name",
};

const AlphaZoneQueuedResource_BulkInsertInstanceResourceFields: FieldMap = {
  count: "count",
  instanceFlexibilityPolicy: {
    wireName: "instance_flexibility_policy",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceFlexibilityPolicyFields,
  },
  instanceProperties: {
    wireName: "instance_properties",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstancePropertiesFields,
  },
  locationPolicy: {
    wireName: "location_policy",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_LocationPolicyFields,
  },
  minCount: "min_count",
  namePattern: "name_pattern",
  perInstanceProperties: {
    wireName: "per_instance_properties",
    kind: "map",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_PerInstancePropertiesFields,
  },
  sourceInstanceTemplate: "source_instance_template",
};

const AlphaZoneQueuedResource_QueuingPolicyFields: FieldMap = {
  validUntilDuration: {
    wireName: "valid_until_duration",
    kind: "object",
    fields: AlphaZoneQueuedResource_BulkInsertInstanceResource_InstanceProperties_Scheduling_GracefulShutdown_MaxDurationFields,
  },
  validUntilTime: "valid_until_time",
};

const AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_ErrorInfoFields: FieldMap = {
  domain: "domain",
  metadatas: "metadatas",
  reason: "reason",
};

const AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_Help_LinksFields: FieldMap = {
  description: "description",
  url: "url",
};

const AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_HelpFields: FieldMap = {
  links: {
    wireName: "links",
    kind: "list",
    fields: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_Help_LinksFields,
  },
};

const AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_LocalizedMessageFields: FieldMap = {
  locale: "locale",
  message: "message",
};

const AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_QuotaInfoFields: FieldMap = {
  dimensions: "dimensions",
  futureLimit: "future_limit",
  limit: "limit",
  limitName: "limit_name",
  metricName: "metric_name",
  rolloutStatus: "rollout_status",
};

const AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetailsFields: FieldMap = {
  errorInfo: {
    wireName: "error_info",
    kind: "object",
    fields: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_ErrorInfoFields,
  },
  help: {
    wireName: "help",
    kind: "object",
    fields: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_HelpFields,
  },
  localizedMessage: {
    wireName: "localized_message",
    kind: "object",
    fields: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_LocalizedMessageFields,
  },
  quotaInfo: {
    wireName: "quota_info",
    kind: "object",
    fields: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetails_QuotaInfoFields,
  },
};

const AlphaZoneQueuedResource_Status_FailedData_Error_ErrorsFields: FieldMap = {
  code: "code",
  errorDetails: {
    wireName: "error_details",
    kind: "list",
    fields: AlphaZoneQueuedResource_Status_FailedData_Error_Errors_ErrorDetailsFields,
  },
  location: "location",
  message: "message",
};

const AlphaZoneQueuedResource_Status_FailedData_ErrorFields: FieldMap = {
  errors: {
    wireName: "errors",
    kind: "list",
    fields: AlphaZoneQueuedResource_Status_FailedData_Error_ErrorsFields,
  },
};

const AlphaZoneQueuedResource_Status_FailedDataFields: FieldMap = {
  error: {
    wireName: "error",
    kind: "object",
    fields: AlphaZoneQueuedResource_Status_FailedData_ErrorFields,
  },
};

const AlphaZoneQueuedResource_StatusFields: FieldMap = {
  failedData: {
    wireName: "failed_data",
    kind: "object",
    fields: AlphaZoneQueuedResource_Status_FailedDataFields,
  },
  provisioningOperations: "provisioning_operations",
  queuingPolicy: {
    wireName: "queuing_policy",
    kind: "object",
    fields: AlphaZoneQueuedResource_QueuingPolicyFields,
  },
};

export interface AlphaZoneQueuedResourceConfig {
  /** A transient resource used in compute.instances.bulkInsert and compute.regionInstances.bulkInsert . This resource is not persisted anywhere, it is used only for processing the requests. */
  bulkInsertInstanceResource?: AlphaZoneQueuedResource_BulkInsertInstanceResource | Computed<AlphaZoneQueuedResource_BulkInsertInstanceResource>;
  /** Output only. [Output Only] Creation timestamp in RFC3339 text format. */
  creationTimestamp?: string | Computed<string>;
  /** An optional description of this resource. Provide this property when you create the resource. */
  description?: string | Computed<string>;
  /** Output only. [Output Only] The unique identifier for the resource. This identifier is defined by the server. */
  id?: string | Computed<string>;
  /** Output only. [Output Only] Type of the resource. Alwayscompute#queuedResource for QueuedResources. */
  kind?: string | Computed<string>;
  /** Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and comply withRFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash. */
  name?: string | Computed<string>;
  /** Queuing parameters for the requested deferred capacity. */
  queuingPolicy?: AlphaZoneQueuedResource_QueuingPolicy | Computed<AlphaZoneQueuedResource_QueuingPolicy>;
  /** Output only. [Output only] Server-defined URL for the resource. */
  selfLink?: string | Computed<string>;
  /** Output only. [Output Only] Server-defined URL for this resource with the resource id. */
  selfLinkWithId?: string | Computed<string>;
  /** Output only. [Output only] High-level status of the request. */
  state?: string | Computed<string>;
  /** [Output only] Result of queuing and provisioning based on deferred capacity. */
  status?: AlphaZoneQueuedResource_Status | Computed<AlphaZoneQueuedResource_Status>;
  /** Output only. [Output Only] URL of the zone where the resource resides. Only applicable for zonal resources. You must specify this field as part of the HTTP request URL. It is not settable as a field in the request body. */
  zone?: string | Computed<string>;
}

export interface AlphaZoneQueuedResourceAttrs {
  /** A transient resource used in compute.instances.bulkInsert and compute.regionInstances.bulkInsert . This resource is not persisted anywhere, it is used only for processing the requests. */
  bulkInsertInstanceResource: AlphaZoneQueuedResource_BulkInsertInstanceResource;
  /** Output only. [Output Only] Creation timestamp in RFC3339 text format. */
  creationTimestamp: string;
  /** An optional description of this resource. Provide this property when you create the resource. */
  description: string;
  /** Output only. [Output Only] The unique identifier for the resource. This identifier is defined by the server. */
  id: string;
  /** Output only. [Output Only] Type of the resource. Alwayscompute#queuedResource for QueuedResources. */
  kind: string;
  /** Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and comply withRFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash. */
  name: string;
  /** Queuing parameters for the requested deferred capacity. */
  queuingPolicy: AlphaZoneQueuedResource_QueuingPolicy;
  /** Output only. [Output only] Server-defined URL for the resource. */
  selfLink: string;
  /** Output only. [Output Only] Server-defined URL for this resource with the resource id. */
  selfLinkWithId: string;
  /** Output only. [Output only] High-level status of the request. */
  state: string;
  /** [Output only] Result of queuing and provisioning based on deferred capacity. */
  status: AlphaZoneQueuedResource_Status;
  /** Output only. [Output Only] URL of the zone where the resource resides. Only applicable for zonal resources. You must specify this field as part of the HTTP request URL. It is not settable as a field in the request body. */
  zone: string;
}

export const AlphaZoneQueuedResource: ResourceBinding<AlphaZoneQueuedResourceConfig, AlphaZoneQueuedResourceAttrs> = {
  wireType: "google_compute_alpha_zone_queued_resource",
  fields: {
    bulkInsertInstanceResource: {
      wireName: "bulk_insert_instance_resource",
      kind: "object",
      fields: AlphaZoneQueuedResource_BulkInsertInstanceResourceFields,
    },
    creationTimestamp: "creation_timestamp",
    description: "description",
    id: "id",
    kind: "kind",
    name: "name",
    queuingPolicy: {
      wireName: "queuing_policy",
      kind: "object",
      fields: AlphaZoneQueuedResource_QueuingPolicyFields,
    },
    selfLink: "self_link",
    selfLinkWithId: "self_link_with_id",
    state: "state",
    status: {
      wireName: "status",
      kind: "object",
      fields: AlphaZoneQueuedResource_StatusFields,
    },
    zone: "zone",
  },
};
