// Code generated by `ubx sdk gen` from google_compute_beta_snapshot. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface BetaSnapshot_GuestOsFeatures {
  type?: string | Computed<string>;
}

export interface BetaSnapshot_Params {
  /** Input only. Resource manager tags to be bound to the snapshot. Tag keys and values have the same definition as resource manager tags. Keys and values can be either in numeric format, such as `tagKeys/{tag_key_id}` and `tagValues/{tag_value_id}` or in namespaced format such as `{org_id|project_id}/{tag_key_short_name}` and `{tag_value_short_name}`. The field is ignored (both PUT & PATCH) when empty. */
  resourceManagerTags?: Record<string, string> | Computed<Record<string, string>>;
}

export interface BetaSnapshot_SnapshotEncryptionKey {
  /** The name of the encryption key that is stored in Google Cloud KMS. For example: "kmsKeyName": "projects/kms_project_id/locations/region/keyRings/ key_region/cryptoKeys/key The fully-qualifed key name may be returned for resource GET requests. For example: "kmsKeyName": "projects/kms_project_id/locations/region/keyRings/ key_region/cryptoKeys/key /cryptoKeyVersions/1 */
  kmsKeyName?: string | Computed<string>;
  /** The service account being used for the encryption request for the given KMS key. If absent, the Compute Engine default service account is used. For example: "kmsKeyServiceAccount": "name@project_id.iam.gserviceaccount.com/ */
  kmsKeyServiceAccount?: string | Computed<string>;
  /** [DEPRECATED] CSEK is no longer supported. Use CMEK instead. Specifies a 256-bit customer-supplied encryption key, encoded in RFC 4648 base64 to either encrypt or decrypt this resource. You can provide either the rawKey or thersaEncryptedKey. For example: "rawKey": "SGVsbG8gZnJvbSBHb29nbGUgQ2xvdWQgUGxhdGZvcm0=" */
  rawKey?: string | Computed<string>;
  /** [DEPRECATED] CSEK is no longer supported. Use CMEK instead. Specifies an RFC 4648 base64 encoded, RSA-wrapped 2048-bit customer-supplied encryption key to either encrypt or decrypt this resource. You can provide either the rawKey or thersaEncryptedKey. For example: "rsaEncryptedKey": "ieCx/NcW06PcT7Ep1X6LUTc/hLvUDYyzSZPPVCVPTVEohpeHASqC8uw5TzyO9U+Fka9JFH z0mBibXUInrC/jEk014kCK/NPjYgEMOyssZ4ZINPKxlUh2zn1bV+MCaTICrdmuSBTWlUUiFoD D6PYznLwh8ZNdaheCeZ8ewEXgFQ8V+sDroLaN3Xs3MDTXQEMMoNUXMCZEIpg9Vtp9x2oe==" The key must meet the following requirements before you can provide it to Compute Engine: 1. The key is wrapped using a RSA public key certificate provided by Google. 2. After being wrapped, the key must be encoded in RFC 4648 base64 encoding. Gets the RSA public key certificate provided by Google at: https://cloud-certs.storage.googleapis.com/google-cloud-csek-ingress.pem */
  rsaEncryptedKey?: string | Computed<string>;
  /** [DEPRECATED] CSEK is no longer supported. Use CMEK instead. [Output only] TheRFC 4648 base64 encoded SHA-256 hash of the customer-supplied encryption key that protects this resource. */
  sha256?: string | Computed<string>;
}

const BetaSnapshot_GuestOsFeaturesFields: FieldMap = {
  type: "type",
};

const BetaSnapshot_ParamsFields: FieldMap = {
  resourceManagerTags: "resource_manager_tags",
};

const BetaSnapshot_SnapshotEncryptionKeyFields: FieldMap = {
  kmsKeyName: "kms_key_name",
  kmsKeyServiceAccount: "kms_key_service_account",
  rawKey: "raw_key",
  rsaEncryptedKey: "rsa_encrypted_key",
  sha256: "sha256",
};

export interface BetaSnapshotConfig {
  /** Output only. [Output Only] The architecture of the snapshot. Valid values are ARM64 or X86_64. */
  architecture?: string | Computed<string>;
  /** Output only. [Output Only] Set to true if snapshots are automatically created by applying resource policy on the target disk. */
  autoCreated?: boolean | Computed<boolean>;
  /** Creates the new snapshot in the snapshot chain labeled with the specified name. The chain name must be 1-63 characters long and comply with RFC1035. This is an uncommon option only for advanced service owners who needs to create separate snapshot chains, for example, for chargeback tracking. When you describe your snapshot resource, this field is visible only if it has a non-empty value. */
  chainName?: string | Computed<string>;
  /** Output only. [Output Only] Size in bytes of the snapshot at creation time. */
  creationSizeBytes?: string | Computed<string>;
  /** Output only. [Output Only] Creation timestamp inRFC3339 text format. */
  creationTimestamp?: string | Computed<string>;
  /** An optional description of this resource. Provide this property when you create the resource. */
  description?: string | Computed<string>;
  /** Output only. [Output Only] Size of the source disk, specified in GB. */
  diskSizeGb?: string | Computed<string>;
  /** Output only. [Output Only] Number of bytes downloaded to restore a snapshot to a disk. */
  downloadBytes?: string | Computed<string>;
  /** Output only. Whether this snapshot is created from a confidential compute mode disk. [Output Only]: This field is not set by user, but from source disk. */
  enableConfidentialCompute?: boolean | Computed<boolean>;
  /** [Input Only] Whether to attempt an application consistent snapshot by informing the OS to prepare for the snapshot process. */
  guestFlush?: boolean | Computed<boolean>;
  /** Output only. [Output Only] A list of features to enable on the guest operating system. Applicable only for bootable images. Read Enabling guest operating system features to see a list of available options. */
  guestOsFeatures?: BetaSnapshot_GuestOsFeatures[] | Computed<BetaSnapshot_GuestOsFeatures[]>;
  /** Output only. [Output Only] The unique identifier for the resource. This identifier is defined by the server. */
  id?: string | Computed<string>;
  /** Output only. [Output Only] Type of the resource. Always compute#snapshot for Snapshot resources. */
  kind?: string | Computed<string>;
  /** A fingerprint for the labels being applied to this snapshot, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error412 conditionNotMet. To see the latest fingerprint, make a get() request to retrieve a snapshot. */
  labelFingerprint?: string | Computed<string>;
  /** Labels to apply to this snapshot. These can be later modified by the setLabels method. Label values may be empty. */
  labels?: Record<string, string> | Computed<Record<string, string>>;
  /** Output only. [Output Only] Integer license codes indicating which licenses are attached to this snapshot. */
  licenseCodes?: string[] | Computed<string[]>;
  /** Output only. [Output Only] A list of public visible licenses that apply to this snapshot. This can be because the original image had licenses attached (such as a Windows image). */
  licenses?: string[] | Computed<string[]>;
  /** An opaque location hint used to place the snapshot close to other resources. This field is for use by internal tools that use the public API. */
  locationHint?: string | Computed<string>;
  /** Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply withRFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash. */
  name?: string | Computed<string>;
  /** Additional snapshot params. */
  params?: BetaSnapshot_Params | Computed<BetaSnapshot_Params>;
  /** Output only. [Output Only] URL of the region where the snapshot resides. Only applicable for regional snapshots. */
  region?: string | Computed<string>;
  /** Output only. Reserved for future use. */
  satisfiesPzi?: boolean | Computed<boolean>;
  /** Output only. [Output Only] Reserved for future use. */
  satisfiesPzs?: boolean | Computed<boolean>;
  /** Output only. [Output Only] Server-defined URL for the resource. */
  selfLink?: string | Computed<string>;
  snapshotEncryptionKey?: BetaSnapshot_SnapshotEncryptionKey | Computed<BetaSnapshot_SnapshotEncryptionKey>;
  /** Output only. [Output Only] The unique ID of the snapshot group that this snapshot belongs to. The usage of snapshot group feature is restricted. */
  snapshotGroupId?: string | Computed<string>;
  /** Output only. [Output only] The snapshot group that this snapshot belongs to. The usage of snapshot group feature is restricted. */
  snapshotGroupName?: string | Computed<string>;
  /** Indicates the type of the snapshot. */
  snapshotType?: string | Computed<string>;
  /** The source disk used to create this snapshot. */
  sourceDisk?: string | Computed<string>;
  sourceDiskEncryptionKey?: BetaSnapshot_SnapshotEncryptionKey | Computed<BetaSnapshot_SnapshotEncryptionKey>;
  /** The source disk whose recovery checkpoint will be used to create this snapshot. */
  sourceDiskForRecoveryCheckpoint?: string | Computed<string>;
  /** Output only. [Output Only] The ID value of the disk used to create this snapshot. This value may be used to determine whether the snapshot was taken from the current or a previous instance of a given disk name. */
  sourceDiskId?: string | Computed<string>;
  /** The source instant snapshot used to create this snapshot. You can provide this as a partial or full URL to the resource. For example, the following are valid values: - https://www.googleapis.com/compute/v1/projects/project/zones/zone/instantSnapshots/instantSnapshot - projects/project/zones/zone/instantSnapshots/instantSnapshot - zones/zone/instantSnapshots/instantSnapshot */
  sourceInstantSnapshot?: string | Computed<string>;
  sourceInstantSnapshotEncryptionKey?: BetaSnapshot_SnapshotEncryptionKey | Computed<BetaSnapshot_SnapshotEncryptionKey>;
  /** Output only. [Output Only] The unique ID of the instant snapshot used to create this snapshot. This value identifies the exact instant snapshot that was used to create this snapshot. For example, if you created the snapshot from an instant snapshot that was later deleted and recreated under the same name, the source instant snapshot ID would identify the exact instant snapshot that was used. */
  sourceInstantSnapshotId?: string | Computed<string>;
  /** Output only. [Output Only] URL of the resource policy which created this scheduled snapshot. */
  sourceSnapshotSchedulePolicy?: string | Computed<string>;
  /** Output only. [Output Only] ID of the resource policy which created this scheduled snapshot. */
  sourceSnapshotSchedulePolicyId?: string | Computed<string>;
  /** Output only. [Output Only] The status of the snapshot. This can beCREATING, DELETING, FAILED,READY, or UPLOADING. */
  status?: string | Computed<string>;
  /** Output only. [Output Only] A size of the storage used by the snapshot. As snapshots share storage, this number is expected to change with snapshot creation/deletion. */
  storageBytes?: string | Computed<string>;
  /** Output only. [Deprecated] Instead, check the storageBytes field. After snapshot creation, the storageBytesStatus field is alwaysUP_TO_DATE. [Output Only] An indicator whether storageBytes is in a stable state or it is being adjusted as a result of shared storage reallocation. This status can either be unset, meaning the snapshot is being created, or UP_TO_DATE, meaning the size of the snapshot is up-to-date. */
  storageBytesStatus?: string | Computed<string>;
  /** Cloud Storage bucket storage location of the snapshot (regional or multi-regional). */
  storageLocations?: string[] | Computed<string[]>;
}

export interface BetaSnapshotAttrs {
  /** Output only. [Output Only] The architecture of the snapshot. Valid values are ARM64 or X86_64. */
  architecture: string;
  /** Output only. [Output Only] Set to true if snapshots are automatically created by applying resource policy on the target disk. */
  autoCreated: boolean;
  /** Creates the new snapshot in the snapshot chain labeled with the specified name. The chain name must be 1-63 characters long and comply with RFC1035. This is an uncommon option only for advanced service owners who needs to create separate snapshot chains, for example, for chargeback tracking. When you describe your snapshot resource, this field is visible only if it has a non-empty value. */
  chainName: string;
  /** Output only. [Output Only] Size in bytes of the snapshot at creation time. */
  creationSizeBytes: string;
  /** Output only. [Output Only] Creation timestamp inRFC3339 text format. */
  creationTimestamp: string;
  /** An optional description of this resource. Provide this property when you create the resource. */
  description: string;
  /** Output only. [Output Only] Size of the source disk, specified in GB. */
  diskSizeGb: string;
  /** Output only. [Output Only] Number of bytes downloaded to restore a snapshot to a disk. */
  downloadBytes: string;
  /** Output only. Whether this snapshot is created from a confidential compute mode disk. [Output Only]: This field is not set by user, but from source disk. */
  enableConfidentialCompute: boolean;
  /** [Input Only] Whether to attempt an application consistent snapshot by informing the OS to prepare for the snapshot process. */
  guestFlush: boolean;
  /** Output only. [Output Only] A list of features to enable on the guest operating system. Applicable only for bootable images. Read Enabling guest operating system features to see a list of available options. */
  guestOsFeatures: BetaSnapshot_GuestOsFeatures[];
  /** Output only. [Output Only] The unique identifier for the resource. This identifier is defined by the server. */
  id: string;
  /** Output only. [Output Only] Type of the resource. Always compute#snapshot for Snapshot resources. */
  kind: string;
  /** A fingerprint for the labels being applied to this snapshot, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error412 conditionNotMet. To see the latest fingerprint, make a get() request to retrieve a snapshot. */
  labelFingerprint: string;
  /** Labels to apply to this snapshot. These can be later modified by the setLabels method. Label values may be empty. */
  labels: Record<string, string>;
  /** Output only. [Output Only] Integer license codes indicating which licenses are attached to this snapshot. */
  licenseCodes: string[];
  /** Output only. [Output Only] A list of public visible licenses that apply to this snapshot. This can be because the original image had licenses attached (such as a Windows image). */
  licenses: string[];
  /** An opaque location hint used to place the snapshot close to other resources. This field is for use by internal tools that use the public API. */
  locationHint: string;
  /** Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply withRFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash. */
  name: string;
  /** Additional snapshot params. */
  params: BetaSnapshot_Params;
  /** Output only. [Output Only] URL of the region where the snapshot resides. Only applicable for regional snapshots. */
  region: string;
  /** Output only. Reserved for future use. */
  satisfiesPzi: boolean;
  /** Output only. [Output Only] Reserved for future use. */
  satisfiesPzs: boolean;
  /** Output only. [Output Only] Server-defined URL for the resource. */
  selfLink: string;
  snapshotEncryptionKey: BetaSnapshot_SnapshotEncryptionKey;
  /** Output only. [Output Only] The unique ID of the snapshot group that this snapshot belongs to. The usage of snapshot group feature is restricted. */
  snapshotGroupId: string;
  /** Output only. [Output only] The snapshot group that this snapshot belongs to. The usage of snapshot group feature is restricted. */
  snapshotGroupName: string;
  /** Indicates the type of the snapshot. */
  snapshotType: string;
  /** The source disk used to create this snapshot. */
  sourceDisk: string;
  sourceDiskEncryptionKey: BetaSnapshot_SnapshotEncryptionKey;
  /** The source disk whose recovery checkpoint will be used to create this snapshot. */
  sourceDiskForRecoveryCheckpoint: string;
  /** Output only. [Output Only] The ID value of the disk used to create this snapshot. This value may be used to determine whether the snapshot was taken from the current or a previous instance of a given disk name. */
  sourceDiskId: string;
  /** The source instant snapshot used to create this snapshot. You can provide this as a partial or full URL to the resource. For example, the following are valid values: - https://www.googleapis.com/compute/v1/projects/project/zones/zone/instantSnapshots/instantSnapshot - projects/project/zones/zone/instantSnapshots/instantSnapshot - zones/zone/instantSnapshots/instantSnapshot */
  sourceInstantSnapshot: string;
  sourceInstantSnapshotEncryptionKey: BetaSnapshot_SnapshotEncryptionKey;
  /** Output only. [Output Only] The unique ID of the instant snapshot used to create this snapshot. This value identifies the exact instant snapshot that was used to create this snapshot. For example, if you created the snapshot from an instant snapshot that was later deleted and recreated under the same name, the source instant snapshot ID would identify the exact instant snapshot that was used. */
  sourceInstantSnapshotId: string;
  /** Output only. [Output Only] URL of the resource policy which created this scheduled snapshot. */
  sourceSnapshotSchedulePolicy: string;
  /** Output only. [Output Only] ID of the resource policy which created this scheduled snapshot. */
  sourceSnapshotSchedulePolicyId: string;
  /** Output only. [Output Only] The status of the snapshot. This can beCREATING, DELETING, FAILED,READY, or UPLOADING. */
  status: string;
  /** Output only. [Output Only] A size of the storage used by the snapshot. As snapshots share storage, this number is expected to change with snapshot creation/deletion. */
  storageBytes: string;
  /** Output only. [Deprecated] Instead, check the storageBytes field. After snapshot creation, the storageBytesStatus field is alwaysUP_TO_DATE. [Output Only] An indicator whether storageBytes is in a stable state or it is being adjusted as a result of shared storage reallocation. This status can either be unset, meaning the snapshot is being created, or UP_TO_DATE, meaning the size of the snapshot is up-to-date. */
  storageBytesStatus: string;
  /** Cloud Storage bucket storage location of the snapshot (regional or multi-regional). */
  storageLocations: string[];
}

export const BetaSnapshot: ResourceBinding<BetaSnapshotConfig, BetaSnapshotAttrs> = {
  wireType: "google_compute_beta_snapshot",
  fields: {
    architecture: "architecture",
    autoCreated: "auto_created",
    chainName: "chain_name",
    creationSizeBytes: "creation_size_bytes",
    creationTimestamp: "creation_timestamp",
    description: "description",
    diskSizeGb: "disk_size_gb",
    downloadBytes: "download_bytes",
    enableConfidentialCompute: "enable_confidential_compute",
    guestFlush: "guest_flush",
    guestOsFeatures: {
      wireName: "guest_os_features",
      kind: "list",
      fields: BetaSnapshot_GuestOsFeaturesFields,
    },
    id: "id",
    kind: "kind",
    labelFingerprint: "label_fingerprint",
    labels: "labels",
    licenseCodes: "license_codes",
    licenses: "licenses",
    locationHint: "location_hint",
    name: "name",
    params: {
      wireName: "params",
      kind: "object",
      fields: BetaSnapshot_ParamsFields,
    },
    region: "region",
    satisfiesPzi: "satisfies_pzi",
    satisfiesPzs: "satisfies_pzs",
    selfLink: "self_link",
    snapshotEncryptionKey: {
      wireName: "snapshot_encryption_key",
      kind: "object",
      fields: BetaSnapshot_SnapshotEncryptionKeyFields,
    },
    snapshotGroupId: "snapshot_group_id",
    snapshotGroupName: "snapshot_group_name",
    snapshotType: "snapshot_type",
    sourceDisk: "source_disk",
    sourceDiskEncryptionKey: {
      wireName: "source_disk_encryption_key",
      kind: "object",
      fields: BetaSnapshot_SnapshotEncryptionKeyFields,
    },
    sourceDiskForRecoveryCheckpoint: "source_disk_for_recovery_checkpoint",
    sourceDiskId: "source_disk_id",
    sourceInstantSnapshot: "source_instant_snapshot",
    sourceInstantSnapshotEncryptionKey: {
      wireName: "source_instant_snapshot_encryption_key",
      kind: "object",
      fields: BetaSnapshot_SnapshotEncryptionKeyFields,
    },
    sourceInstantSnapshotId: "source_instant_snapshot_id",
    sourceSnapshotSchedulePolicy: "source_snapshot_schedule_policy",
    sourceSnapshotSchedulePolicyId: "source_snapshot_schedule_policy_id",
    status: "status",
    storageBytes: "storage_bytes",
    storageBytesStatus: "storage_bytes_status",
    storageLocations: "storage_locations",
  },
};
