// Code generated by `ubx sdk gen` from google_containeranalysis_v1beta1_containeranalysis_v1beta1_note. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface V1beta1ContaineranalysisV1beta1Note_AttestationAuthority_Hint {
  /** Required. The human readable name of this attestation authority, for example "qa". */
  humanReadableName?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_AttestationAuthority {
  /** This submessage provides human-readable hints about the purpose of the authority. Because the name of a note acts as its resource reference, it is important to disambiguate the canonical name of the Note (which might be a UUID for security purposes) from "readable" names more suitable for debug output. Note that these hints should not be used to look up authorities in security sensitive contexts, such as when looking up attestations to verify. */
  hint?: V1beta1ContaineranalysisV1beta1Note_AttestationAuthority_Hint | Computed<V1beta1ContaineranalysisV1beta1Note_AttestationAuthority_Hint>;
}

export interface V1beta1ContaineranalysisV1beta1Note_BaseImage_Fingerprint {
  /** Required. The layer ID of the final layer in the Docker image's v1 representation. */
  v1Name?: string | Computed<string>;
  /** Required. The ordered list of v2 blobs that represent a given image. */
  v2Blob?: string[] | Computed<string[]>;
  /** Output only. The name of the image's v2 blobs computed via: [bottom] := v2_blobbottom := sha256(v2_blob[N] + " " + v2_name[N+1]) Only the name of the final blob is kept. */
  v2Name?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_BaseImage {
  /** A set of properties that uniquely identify a given Docker image. */
  fingerprint?: V1beta1ContaineranalysisV1beta1Note_BaseImage_Fingerprint | Computed<V1beta1ContaineranalysisV1beta1Note_BaseImage_Fingerprint>;
  /** Required. Immutable. The resource_url for the resource representing the basis of associated occurrence images. */
  resourceUrl?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Build_Signature {
  /** An ID for the key used to sign. This could be either an ID for the key stored in `public_key` (such as the ID or fingerprint for a PGP key, or the CN for a cert), or a reference to an external key (such as a reference to a key in Cloud Key Management Service). */
  keyId?: string | Computed<string>;
  /** The type of the key, either stored in `public_key` or referenced in `key_id`. */
  keyType?: string | Computed<string>;
  /** Public key of the builder which can be used to verify that the related findings are valid and unchanged. If `key_type` is empty, this defaults to PEM encoded public keys. This field may be empty if `key_id` references an external key. For Cloud Build based signatures, this is a PEM encoded public key. To verify the Cloud Build signature, place the contents of this field into a file (public.pem). The signature field is base64-decoded into its binary representation in signature.bin, and the provenance bytes from `BuildDetails` are base64-decoded into a binary representation in signed.bin. OpenSSL can then verify the signature: `openssl sha256 -verify public.pem -signature signature.bin signed.bin` */
  publicKey?: string | Computed<string>;
  /** Required. Signature of the related `BuildProvenance`. In JSON, this is base-64 encoded. */
  signature?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Build {
  /** Required. Immutable. Version of the builder which produced this build. */
  builderVersion?: string | Computed<string>;
  /** Message encapsulating the signature of the verified build. */
  signature?: V1beta1ContaineranalysisV1beta1Note_Build_Signature | Computed<V1beta1ContaineranalysisV1beta1Note_Build_Signature>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Deployable {
  /** Required. Resource URI for the artifact being deployed. */
  resourceUri?: string[] | Computed<string[]>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Discovery {
  /** Required. Immutable. The kind of analysis that is handled by this discovery. */
  analysisKind?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Intoto_ExpectedMaterials {
  artifactRule?: string[] | Computed<string[]>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Intoto_SigningKeys {
  keyId?: string | Computed<string>;
  keyScheme?: string | Computed<string>;
  keyType?: string | Computed<string>;
  publicKeyValue?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Intoto {
  /** This field contains the expected command used to perform the step. */
  expectedCommand?: string[] | Computed<string[]>;
  /** The following fields contain in-toto artifact rules identifying the artifacts that enter this supply chain step, and exit the supply chain step, i.e. materials and products of the step. */
  expectedMaterials?: V1beta1ContaineranalysisV1beta1Note_Intoto_ExpectedMaterials[] | Computed<V1beta1ContaineranalysisV1beta1Note_Intoto_ExpectedMaterials[]>;
  expectedProducts?: V1beta1ContaineranalysisV1beta1Note_Intoto_ExpectedMaterials[] | Computed<V1beta1ContaineranalysisV1beta1Note_Intoto_ExpectedMaterials[]>;
  /** This field contains the public keys that can be used to verify the signatures on the step metadata. */
  signingKeys?: V1beta1ContaineranalysisV1beta1Note_Intoto_SigningKeys[] | Computed<V1beta1ContaineranalysisV1beta1Note_Intoto_SigningKeys[]>;
  /** This field identifies the name of the step in the supply chain. */
  stepName?: string | Computed<string>;
  /** This field contains a value that indicates the minimum number of keys that need to be used to sign the step's in-toto link. */
  threshold?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Package_Digest {
  algo?: string | Computed<string>;
  digestBytes?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion {
  epoch?: number | Computed<number>;
  inclusive?: boolean | Computed<boolean>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  revision?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Package_Distribution {
  architecture?: string | Computed<string>;
  cpeUri?: string | Computed<string>;
  description?: string | Computed<string>;
  latestVersion?: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion | Computed<V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion>;
  maintainer?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Package_License {
  /** Comments */
  comments?: string | Computed<string>;
  /** Often a single license can be used to represent the licensing terms. Sometimes it is necessary to include a choice of one or more licenses or some combination of license identifiers. Examples: "LGPL-2.1-only OR MIT", "LGPL-2.1-only AND MIT", "GPL-2.0-or-later WITH Bison-exception-2.2". */
  expression?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Package {
  /** The CPU architecture for which packages in this distribution channel were built. Architecture will be blank for language packages. */
  architecture?: string | Computed<string>;
  /** The cpe_uri in [CPE format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package. The cpe_uri will be blank for language packages. */
  cpeUri?: string | Computed<string>;
  /** The description of this package. */
  description?: string | Computed<string>;
  /** Hash value, typically a file digest, that allows unique identification a specific package. */
  digest?: V1beta1ContaineranalysisV1beta1Note_Package_Digest[] | Computed<V1beta1ContaineranalysisV1beta1Note_Package_Digest[]>;
  /** The various channels by which a package is distributed. */
  distribution?: V1beta1ContaineranalysisV1beta1Note_Package_Distribution[] | Computed<V1beta1ContaineranalysisV1beta1Note_Package_Distribution[]>;
  /** License information. */
  license?: V1beta1ContaineranalysisV1beta1Note_Package_License | Computed<V1beta1ContaineranalysisV1beta1Note_Package_License>;
  /** A freeform text denoting the maintainer of this package. */
  maintainer?: string | Computed<string>;
  /** Required. Immutable. The name of the package. */
  name?: string | Computed<string>;
  /** The type of package; whether native or non native (e.g., ruby gems, node.js packages, etc.). */
  packageType?: string | Computed<string>;
  /** The homepage for this package. */
  url?: string | Computed<string>;
  /** Version contains structured information about the version of a package. */
  version?: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion | Computed<V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion>;
}

export interface V1beta1ContaineranalysisV1beta1Note_RelatedUrl {
  label?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Sbom {
  /** Compliance with the SPDX specification includes populating the SPDX fields therein with data related to such fields ("SPDX-Metadata") */
  dataLicence?: string | Computed<string>;
  /** Provide a reference number that can be used to understand how to parse and interpret the rest of the file */
  spdxVersion?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_SbomReference {
  /** The format that SBOM takes. E.g. may be spdx, cyclonedx, etc... */
  format?: string | Computed<string>;
  /** The version of the format that the SBOM takes. E.g. if the format is spdx, the version may be 2.3. */
  version?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_SpdxFile {
  /** Provide a unique identifier to match analysis information on each specific file in a package */
  checksum?: string[] | Computed<string[]>;
  /** This field provides information about the type of file identified */
  fileType?: string | Computed<string>;
  /** Identify the full path and filename that corresponds to the file information in this section */
  title?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_SpdxPackage_ExternalRefs {
  category?: string | Computed<string>;
  comment?: string | Computed<string>;
  locator?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_SpdxPackage {
  /** Indicates whether the file content of this package has been available for or subjected to analysis when creating the SPDX document */
  analyzed?: boolean | Computed<boolean>;
  /** A place for the SPDX data creator to record, at the package level, acknowledgements that may be needed to be communicated in some contexts */
  attribution?: string | Computed<string>;
  /** Provide an independently reproducible mechanism that permits unique identification of a specific package that correlates to the data in this SPDX file */
  checksum?: string | Computed<string>;
  /** Identify the copyright holders of the package, as well as any dates present */
  copyright?: string | Computed<string>;
  /** A more detailed description of the package */
  detailedDescription?: string | Computed<string>;
  /** This section identifies the download Universal Resource Locator (URL), or a specific location within a version control system (VCS) for the package at the time that the SPDX file was created */
  downloadLocation?: string | Computed<string>;
  /** ExternalRef */
  externalRefs?: V1beta1ContaineranalysisV1beta1Note_SpdxPackage_ExternalRefs[] | Computed<V1beta1ContaineranalysisV1beta1Note_SpdxPackage_ExternalRefs[]>;
  /** Contain the license the SPDX file creator has concluded as governing the This field is to contain a list of all licenses found in the package. The relationship between licenses (i.e., conjunctive, disjunctive) is not specified in this field – it is simply a listing of all licenses found */
  filesLicenseInfo?: string[] | Computed<string[]>;
  /** Provide a place for the SPDX file creator to record a web site that serves as the package's home page */
  homePage?: string | Computed<string>;
  /** License information. */
  licenseDeclared?: V1beta1ContaineranalysisV1beta1Note_Package_License | Computed<V1beta1ContaineranalysisV1beta1Note_Package_License>;
  /** If the package identified in the SPDX file originated from a different person or organization than identified as Package Supplier, this field identifies from where or whom the package originally came */
  originator?: string | Computed<string>;
  /** The type of package: OS, MAVEN, GO, GO_STDLIB, etc. */
  packageType?: string | Computed<string>;
  /** A short description of the package */
  summaryDescription?: string | Computed<string>;
  /** Identify the actual distribution source for the package/directory identified in the SPDX file */
  supplier?: string | Computed<string>;
  /** Identify the full name of the package as given by the Package Originator */
  title?: string | Computed<string>;
  /** This field provides an independently reproducible mechanism identifying specific contents of a package based on the actual files (except the SPDX file itself, if it is included in the package) that make up each package and that correlates to the data in this SPDX file */
  verificationCode?: string | Computed<string>;
  /** Identify the version of the package */
  version?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_SpdxRelationship {
  /** The type of relationship between the source and target SPDX elements */
  type?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV2 {
  /** Attack Complexity (AC). Defined in CVSS v2, v3, v4. */
  attackComplexity?: string | Computed<string>;
  /** Attack Requirements (AT). Defined in CVSS v4. */
  attackRequirements?: string | Computed<string>;
  /** Attack Vector (AV). Defined in CVSS v2, v3, v4. */
  attackVector?: string | Computed<string>;
  /** Authentication (Au). Defined in CVSS v2. */
  authentication?: string | Computed<string>;
  /** Availability Impact (A). Defined in CVSS v2, v3. */
  availabilityImpact?: string | Computed<string>;
  /** The base score is a function of the base metric scores. */
  baseScore?: number | Computed<number>;
  /** Confidentiality Impact (C). Defined in CVSS v2, v3. */
  confidentialityImpact?: string | Computed<string>;
  /** Exploit Maturity (E). Defined in CVSS v4. */
  exploitMaturity?: string | Computed<string>;
  exploitabilityScore?: number | Computed<number>;
  impactScore?: number | Computed<number>;
  /** Integrity Impact (I). Defined in CVSS v2, v3. */
  integrityImpact?: string | Computed<string>;
  /** Privileges Required (PR). Defined in CVSS v3, v4. */
  privilegesRequired?: string | Computed<string>;
  /** Scope (S). Defined in CVSS v3. */
  scope?: string | Computed<string>;
  /** Subsequent System Availability Impact (SA). Defined in CVSS v4. */
  subsequentSystemAvailabilityImpact?: string | Computed<string>;
  /** Subsequent System Confidentiality Impact (SC). Defined in CVSS v4. */
  subsequentSystemConfidentialityImpact?: string | Computed<string>;
  /** Subsequent System Integrity Impact (SI). Defined in CVSS v4. */
  subsequentSystemIntegrityImpact?: string | Computed<string>;
  /** User Interaction (UI). Defined in CVSS v3, v4. */
  userInteraction?: string | Computed<string>;
  /** Vulnerable System Availability Impact (VA). Defined in CVSS v4. */
  vulnerableSystemAvailabilityImpact?: string | Computed<string>;
  /** Vulnerable System Confidentiality Impact (VC). Defined in CVSS v4. */
  vulnerableSystemConfidentialityImpact?: string | Computed<string>;
  /** Vulnerable System Integrity Impact (VI). Defined in CVSS v4. */
  vulnerableSystemIntegrityImpact?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV3 {
  attackComplexity?: string | Computed<string>;
  /** Base Metrics Represents the intrinsic characteristics of a vulnerability that are constant over time and across user environments. */
  attackVector?: string | Computed<string>;
  availabilityImpact?: string | Computed<string>;
  /** The base score is a function of the base metric scores. */
  baseScore?: number | Computed<number>;
  confidentialityImpact?: string | Computed<string>;
  exploitabilityScore?: number | Computed<number>;
  impactScore?: number | Computed<number>;
  integrityImpact?: string | Computed<string>;
  privilegesRequired?: string | Computed<string>;
  scope?: string | Computed<string>;
  userInteraction?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Vulnerability_Details_FixedLocation {
  cpeUri?: string | Computed<string>;
  package?: string | Computed<string>;
  version?: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion | Computed<V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Vulnerability_Details {
  cpeUri?: string | Computed<string>;
  description?: string | Computed<string>;
  fixedLocation?: V1beta1ContaineranalysisV1beta1Note_Vulnerability_Details_FixedLocation | Computed<V1beta1ContaineranalysisV1beta1Note_Vulnerability_Details_FixedLocation>;
  isObsolete?: boolean | Computed<boolean>;
  maxAffectedVersion?: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion | Computed<V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion>;
  minAffectedVersion?: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion | Computed<V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersion>;
  package?: string | Computed<string>;
  packageType?: string | Computed<string>;
  severityName?: string | Computed<string>;
  source?: string | Computed<string>;
  sourceUpdateTime?: string | Computed<string>;
  vendor?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetails_FixingKbs {
  name?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetails {
  cpeUri?: string | Computed<string>;
  description?: string | Computed<string>;
  fixingKbs?: V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetails_FixingKbs[] | Computed<V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetails_FixingKbs[]>;
  name?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_Vulnerability {
  /** The time this advisory was published by the source. */
  advisoryPublishTime?: string | Computed<string>;
  /** The CVSS score for this vulnerability. */
  cvssScore?: number | Computed<number>;
  /** Common Vulnerability Scoring System. This message is compatible with CVSS v2, v3, and v4. For CVSS v2 details, see https://www.first.org/cvss/v2/guide CVSS v2 calculator: https://nvd.nist.gov/vuln-metrics/cvss/v2-calculator For CVSS v3 details, see https://www.first.org/cvss/specification-document CVSS v3 calculator: https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator For CVSS v4 details, see https://www.first.org/cvss/v4.0/user-guide CVSS v4 calculator: https://nvd.nist.gov/vuln-metrics/cvss/v4-calculator */
  cvssV2?: V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV2 | Computed<V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV2>;
  /** Deprecated. Common Vulnerability Scoring System version 3. For details, see https://www.first.org/cvss/specification-document */
  cvssV3?: V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV3 | Computed<V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV3>;
  /** Common Vulnerability Scoring System. This message is compatible with CVSS v2, v3, and v4. For CVSS v2 details, see https://www.first.org/cvss/v2/guide CVSS v2 calculator: https://nvd.nist.gov/vuln-metrics/cvss/v2-calculator For CVSS v3 details, see https://www.first.org/cvss/specification-document CVSS v3 calculator: https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator For CVSS v4 details, see https://www.first.org/cvss/v4.0/user-guide CVSS v4 calculator: https://nvd.nist.gov/vuln-metrics/cvss/v4-calculator */
  cvssV4?: V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV2 | Computed<V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV2>;
  /** CVSS version used to populate cvss_score and severity. */
  cvssVersion?: string | Computed<string>;
  /** A list of CWE for this vulnerability. For details, see: https://cwe.mitre.org/index.html */
  cwe?: string[] | Computed<string[]>;
  /** All information about the package to specifically identify this vulnerability. One entry per (version range and cpe_uri) the package vulnerability has manifested in. */
  details?: V1beta1ContaineranalysisV1beta1Note_Vulnerability_Details[] | Computed<V1beta1ContaineranalysisV1beta1Note_Vulnerability_Details[]>;
  /** Note provider assigned impact of the vulnerability. */
  severity?: string | Computed<string>;
  /** The time this information was last changed at the source. This is an upstream timestamp from the underlying information source - e.g. Ubuntu security tracker. */
  sourceUpdateTime?: string | Computed<string>;
  /** Windows details get their own format because the information format and model don't match a normal detail. Specifically Windows updates are done as patches, thus Windows vulnerabilities really are a missing package, rather than a package being at an incorrect version. */
  windowsDetails?: V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetails[] | Computed<V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetails[]>;
}

export interface V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_Justification {
  /** Additional details on why this justification was chosen. */
  details?: string | Computed<string>;
  /** The justification type for this vulnerability. */
  justificationType?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_Remediations {
  details?: string | Computed<string>;
  remediationType?: string | Computed<string>;
  remediationUri?: V1beta1ContaineranalysisV1beta1Note_RelatedUrl | Computed<V1beta1ContaineranalysisV1beta1Note_RelatedUrl>;
}

export interface V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment {
  /** Holds the MITRE standard Common Vulnerabilities and Exposures (CVE) tracking number for the vulnerability. Deprecated: Use vulnerability_id instead to denote CVEs. */
  cve?: string | Computed<string>;
  /** Contains information about the impact of this vulnerability, this will change with time. */
  impacts?: string[] | Computed<string[]>;
  /** Justification provides the justification when the state of the assessment if NOT_AFFECTED. */
  justification?: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_Justification | Computed<V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_Justification>;
  /** A detailed description of this Vex. */
  longDescription?: string | Computed<string>;
  /** Holds a list of references associated with this vulnerability item and assessment. These uris have additional information about the vulnerability and the assessment itself. E.g. Link to a document which details how this assessment concluded the state of this vulnerability. */
  relatedUris?: V1beta1ContaineranalysisV1beta1Note_RelatedUrl[] | Computed<V1beta1ContaineranalysisV1beta1Note_RelatedUrl[]>;
  /** Specifies details on how to handle (and presumably, fix) a vulnerability. */
  remediations?: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_Remediations[] | Computed<V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_Remediations[]>;
  /** A one sentence description of this Vex. */
  shortDescription?: string | Computed<string>;
  /** Provides the state of this Vulnerability assessment. */
  state?: string | Computed<string>;
  /** The vulnerability identifier for this Assessment. Will hold one of common identifiers e.g. CVE, GHSA etc. */
  vulnerabilityId?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Product {
  /** Contains a URI which is vendor-specific. Example: The artifact repository URL of an image. */
  genericUri?: string | Computed<string>;
  /** Token that identifies a product so that it can be referred to from other parts in the document. There is no predefined format as long as it uniquely identifies a group in the context of the current document. */
  id?: string | Computed<string>;
  /** Name of the product. */
  name?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Publisher {
  /** Provides information about the authority of the issuing party to release the document, in particular, the party's constituency and responsibilities or other obligations. */
  issuingAuthority?: string | Computed<string>;
  /** Name of the publisher. Examples: 'Google', 'Google Cloud Platform'. */
  name?: string | Computed<string>;
  /** The context or namespace. Contains a URL which is under control of the issuing party and can be used as a globally unique identifier for that issuing party. Example: https://csaf.io */
  publisherNamespace?: string | Computed<string>;
}

export interface V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment {
  /** Assessment provides all information that is related to a single vulnerability for this product. */
  assessment?: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment | Computed<V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment>;
  /** Identifies the language used by this document, corresponding to IETF BCP 47 / RFC 5646. */
  languageCode?: string | Computed<string>;
  /** A detailed description of this Vex. */
  longDescription?: string | Computed<string>;
  /** Product contains information about a product and how to uniquely identify it. */
  product?: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Product | Computed<V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Product>;
  /** Publisher contains information about the publisher of this Note. */
  publisher?: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Publisher | Computed<V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Publisher>;
  /** A one sentence description of this Vex. */
  shortDescription?: string | Computed<string>;
  /** The title of the note. E.g. `Vex-Debian-11.4` */
  title?: string | Computed<string>;
}

const V1beta1ContaineranalysisV1beta1Note_AttestationAuthority_HintFields: FieldMap = {
  humanReadableName: "human_readable_name",
};

const V1beta1ContaineranalysisV1beta1Note_AttestationAuthorityFields: FieldMap = {
  hint: {
    wireName: "hint",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_AttestationAuthority_HintFields,
  },
};

const V1beta1ContaineranalysisV1beta1Note_BaseImage_FingerprintFields: FieldMap = {
  v1Name: "v1_name",
  v2Blob: "v2_blob",
  v2Name: "v2_name",
};

const V1beta1ContaineranalysisV1beta1Note_BaseImageFields: FieldMap = {
  fingerprint: {
    wireName: "fingerprint",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_BaseImage_FingerprintFields,
  },
  resourceUrl: "resource_url",
};

const V1beta1ContaineranalysisV1beta1Note_Build_SignatureFields: FieldMap = {
  keyId: "key_id",
  keyType: "key_type",
  publicKey: "public_key",
  signature: "signature",
};

const V1beta1ContaineranalysisV1beta1Note_BuildFields: FieldMap = {
  builderVersion: "builder_version",
  signature: {
    wireName: "signature",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Build_SignatureFields,
  },
};

const V1beta1ContaineranalysisV1beta1Note_DeployableFields: FieldMap = {
  resourceUri: "resource_uri",
};

const V1beta1ContaineranalysisV1beta1Note_DiscoveryFields: FieldMap = {
  analysisKind: "analysis_kind",
};

const V1beta1ContaineranalysisV1beta1Note_Intoto_ExpectedMaterialsFields: FieldMap = {
  artifactRule: "artifact_rule",
};

const V1beta1ContaineranalysisV1beta1Note_Intoto_SigningKeysFields: FieldMap = {
  keyId: "key_id",
  keyScheme: "key_scheme",
  keyType: "key_type",
  publicKeyValue: "public_key_value",
};

const V1beta1ContaineranalysisV1beta1Note_IntotoFields: FieldMap = {
  expectedCommand: "expected_command",
  expectedMaterials: {
    wireName: "expected_materials",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_Intoto_ExpectedMaterialsFields,
  },
  expectedProducts: {
    wireName: "expected_products",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_Intoto_ExpectedMaterialsFields,
  },
  signingKeys: {
    wireName: "signing_keys",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_Intoto_SigningKeysFields,
  },
  stepName: "step_name",
  threshold: "threshold",
};

const V1beta1ContaineranalysisV1beta1Note_Package_DigestFields: FieldMap = {
  algo: "algo",
  digestBytes: "digest_bytes",
};

const V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersionFields: FieldMap = {
  epoch: "epoch",
  inclusive: "inclusive",
  kind: "kind",
  name: "name",
  revision: "revision",
};

const V1beta1ContaineranalysisV1beta1Note_Package_DistributionFields: FieldMap = {
  architecture: "architecture",
  cpeUri: "cpe_uri",
  description: "description",
  latestVersion: {
    wireName: "latest_version",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersionFields,
  },
  maintainer: "maintainer",
  url: "url",
};

const V1beta1ContaineranalysisV1beta1Note_Package_LicenseFields: FieldMap = {
  comments: "comments",
  expression: "expression",
};

const V1beta1ContaineranalysisV1beta1Note_PackageFields: FieldMap = {
  architecture: "architecture",
  cpeUri: "cpe_uri",
  description: "description",
  digest: {
    wireName: "digest",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_DigestFields,
  },
  distribution: {
    wireName: "distribution",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_DistributionFields,
  },
  license: {
    wireName: "license",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_LicenseFields,
  },
  maintainer: "maintainer",
  name: "name",
  packageType: "package_type",
  url: "url",
  version: {
    wireName: "version",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersionFields,
  },
};

const V1beta1ContaineranalysisV1beta1Note_RelatedUrlFields: FieldMap = {
  label: "label",
  url: "url",
};

const V1beta1ContaineranalysisV1beta1Note_SbomFields: FieldMap = {
  dataLicence: "data_licence",
  spdxVersion: "spdx_version",
};

const V1beta1ContaineranalysisV1beta1Note_SbomReferenceFields: FieldMap = {
  format: "format",
  version: "version",
};

const V1beta1ContaineranalysisV1beta1Note_SpdxFileFields: FieldMap = {
  checksum: "checksum",
  fileType: "file_type",
  title: "title",
};

const V1beta1ContaineranalysisV1beta1Note_SpdxPackage_ExternalRefsFields: FieldMap = {
  category: "category",
  comment: "comment",
  locator: "locator",
  type: "type",
};

const V1beta1ContaineranalysisV1beta1Note_SpdxPackageFields: FieldMap = {
  analyzed: "analyzed",
  attribution: "attribution",
  checksum: "checksum",
  copyright: "copyright",
  detailedDescription: "detailed_description",
  downloadLocation: "download_location",
  externalRefs: {
    wireName: "external_refs",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_SpdxPackage_ExternalRefsFields,
  },
  filesLicenseInfo: "files_license_info",
  homePage: "home_page",
  licenseDeclared: {
    wireName: "license_declared",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_LicenseFields,
  },
  originator: "originator",
  packageType: "package_type",
  summaryDescription: "summary_description",
  supplier: "supplier",
  title: "title",
  verificationCode: "verification_code",
  version: "version",
};

const V1beta1ContaineranalysisV1beta1Note_SpdxRelationshipFields: FieldMap = {
  type: "type",
};

const V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV2Fields: FieldMap = {
  attackComplexity: "attack_complexity",
  attackRequirements: "attack_requirements",
  attackVector: "attack_vector",
  authentication: "authentication",
  availabilityImpact: "availability_impact",
  baseScore: "base_score",
  confidentialityImpact: "confidentiality_impact",
  exploitMaturity: "exploit_maturity",
  exploitabilityScore: "exploitability_score",
  impactScore: "impact_score",
  integrityImpact: "integrity_impact",
  privilegesRequired: "privileges_required",
  scope: "scope",
  subsequentSystemAvailabilityImpact: "subsequent_system_availability_impact",
  subsequentSystemConfidentialityImpact: "subsequent_system_confidentiality_impact",
  subsequentSystemIntegrityImpact: "subsequent_system_integrity_impact",
  userInteraction: "user_interaction",
  vulnerableSystemAvailabilityImpact: "vulnerable_system_availability_impact",
  vulnerableSystemConfidentialityImpact: "vulnerable_system_confidentiality_impact",
  vulnerableSystemIntegrityImpact: "vulnerable_system_integrity_impact",
};

const V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV3Fields: FieldMap = {
  attackComplexity: "attack_complexity",
  attackVector: "attack_vector",
  availabilityImpact: "availability_impact",
  baseScore: "base_score",
  confidentialityImpact: "confidentiality_impact",
  exploitabilityScore: "exploitability_score",
  impactScore: "impact_score",
  integrityImpact: "integrity_impact",
  privilegesRequired: "privileges_required",
  scope: "scope",
  userInteraction: "user_interaction",
};

const V1beta1ContaineranalysisV1beta1Note_Vulnerability_Details_FixedLocationFields: FieldMap = {
  cpeUri: "cpe_uri",
  package: "package",
  version: {
    wireName: "version",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersionFields,
  },
};

const V1beta1ContaineranalysisV1beta1Note_Vulnerability_DetailsFields: FieldMap = {
  cpeUri: "cpe_uri",
  description: "description",
  fixedLocation: {
    wireName: "fixed_location",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Vulnerability_Details_FixedLocationFields,
  },
  isObsolete: "is_obsolete",
  maxAffectedVersion: {
    wireName: "max_affected_version",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersionFields,
  },
  minAffectedVersion: {
    wireName: "min_affected_version",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Package_Distribution_LatestVersionFields,
  },
  package: "package",
  packageType: "package_type",
  severityName: "severity_name",
  source: "source",
  sourceUpdateTime: "source_update_time",
  vendor: "vendor",
};

const V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetails_FixingKbsFields: FieldMap = {
  name: "name",
  url: "url",
};

const V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetailsFields: FieldMap = {
  cpeUri: "cpe_uri",
  description: "description",
  fixingKbs: {
    wireName: "fixing_kbs",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetails_FixingKbsFields,
  },
  name: "name",
};

const V1beta1ContaineranalysisV1beta1Note_VulnerabilityFields: FieldMap = {
  advisoryPublishTime: "advisory_publish_time",
  cvssScore: "cvss_score",
  cvssV2: {
    wireName: "cvss_v2",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV2Fields,
  },
  cvssV3: {
    wireName: "cvss_v3",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV3Fields,
  },
  cvssV4: {
    wireName: "cvss_v4",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_Vulnerability_CvssV2Fields,
  },
  cvssVersion: "cvss_version",
  cwe: "cwe",
  details: {
    wireName: "details",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_Vulnerability_DetailsFields,
  },
  severity: "severity",
  sourceUpdateTime: "source_update_time",
  windowsDetails: {
    wireName: "windows_details",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_Vulnerability_WindowsDetailsFields,
  },
};

const V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_JustificationFields: FieldMap = {
  details: "details",
  justificationType: "justification_type",
};

const V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_RemediationsFields: FieldMap = {
  details: "details",
  remediationType: "remediation_type",
  remediationUri: {
    wireName: "remediation_uri",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_RelatedUrlFields,
  },
};

const V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_AssessmentFields: FieldMap = {
  cve: "cve",
  impacts: "impacts",
  justification: {
    wireName: "justification",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_JustificationFields,
  },
  longDescription: "long_description",
  relatedUris: {
    wireName: "related_uris",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_RelatedUrlFields,
  },
  remediations: {
    wireName: "remediations",
    kind: "list",
    fields: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_Assessment_RemediationsFields,
  },
  shortDescription: "short_description",
  state: "state",
  vulnerabilityId: "vulnerability_id",
};

const V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_ProductFields: FieldMap = {
  genericUri: "generic_uri",
  id: "id",
  name: "name",
};

const V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_PublisherFields: FieldMap = {
  issuingAuthority: "issuing_authority",
  name: "name",
  publisherNamespace: "publisher_namespace",
};

const V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessmentFields: FieldMap = {
  assessment: {
    wireName: "assessment",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_AssessmentFields,
  },
  languageCode: "language_code",
  longDescription: "long_description",
  product: {
    wireName: "product",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_ProductFields,
  },
  publisher: {
    wireName: "publisher",
    kind: "object",
    fields: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment_PublisherFields,
  },
  shortDescription: "short_description",
  title: "title",
};

export interface V1beta1ContaineranalysisV1beta1NoteConfig {
  /** AISkillAnalysisNote provides the metadata of an AI-based skill analysis. */
  aiSkillAnalysis?: unknown | Computed<unknown>;
  /** Note kind that represents a logical attestation "role" or "authority". For example, an organization might have one `Authority` for "QA" and one for "build". This note is intended to act strictly as a grouping mechanism for the attached occurrences (Attestations). This grouping mechanism also provides a security boundary, since IAM ACLs gate the ability for a principle to attach an occurrence to a given note. It also provides a single point of lookup to find all attached attestation occurrences, even if they don't all live in the same project. */
  attestationAuthority?: V1beta1ContaineranalysisV1beta1Note_AttestationAuthority | Computed<V1beta1ContaineranalysisV1beta1Note_AttestationAuthority>;
  /** Basis describes the base image portion (Note) of the DockerImage relationship. Linked occurrences are derived from this or an equivalent image via: FROM Or an equivalent reference, e.g. a tag of the resource_url. */
  baseImage?: V1beta1ContaineranalysisV1beta1Note_BaseImage | Computed<V1beta1ContaineranalysisV1beta1Note_BaseImage>;
  /** Note holding the version of the provider's builder and the signature of the provenance message in the build details occurrence. */
  build?: V1beta1ContaineranalysisV1beta1Note_Build | Computed<V1beta1ContaineranalysisV1beta1Note_Build>;
  /** Output only. The time this note was created. This field can be used as a filter in list requests. */
  createTime?: string | Computed<string>;
  /** An artifact that can be deployed in some runtime. */
  deployable?: V1beta1ContaineranalysisV1beta1Note_Deployable | Computed<V1beta1ContaineranalysisV1beta1Note_Deployable>;
  /** A note that indicates a type of analysis a provider would perform. This note exists in a provider's project. A `Discovery` occurrence is created in a consumer's project at the start of analysis. */
  discovery?: V1beta1ContaineranalysisV1beta1Note_Discovery | Computed<V1beta1ContaineranalysisV1beta1Note_Discovery>;
  /** Time of expiration for this note. Empty if note does not expire. */
  expirationTime?: string | Computed<string>;
  /** This contains the fields corresponding to the definition of a software supply chain step in an in-toto layout. This information goes into a Grafeas note. */
  intoto?: V1beta1ContaineranalysisV1beta1Note_Intoto | Computed<V1beta1ContaineranalysisV1beta1Note_Intoto>;
  /** Output only. The type of analysis. This field can be used as a filter in list requests. */
  kind?: string | Computed<string>;
  /** A detailed description of this note. */
  longDescription?: string | Computed<string>;
  /** Output only. The name of the note in the form of `projects/[PROVIDER_ID]/notes/[NOTE_ID]`. */
  name?: string | Computed<string>;
  /** Package represents a particular package version. */
  package?: V1beta1ContaineranalysisV1beta1Note_Package | Computed<V1beta1ContaineranalysisV1beta1Note_Package>;
  /** Other notes related to this note. */
  relatedNoteNames?: string[] | Computed<string[]>;
  /** URLs associated with this note. */
  relatedUrl?: V1beta1ContaineranalysisV1beta1Note_RelatedUrl[] | Computed<V1beta1ContaineranalysisV1beta1Note_RelatedUrl[]>;
  /** DocumentNote represents an SPDX Document Creation Information section: https://spdx.github.io/spdx-spec/2-document-creation-information/ */
  sbom?: V1beta1ContaineranalysisV1beta1Note_Sbom | Computed<V1beta1ContaineranalysisV1beta1Note_Sbom>;
  /** The note representing an SBOM reference. */
  sbomReference?: V1beta1ContaineranalysisV1beta1Note_SbomReference | Computed<V1beta1ContaineranalysisV1beta1Note_SbomReference>;
  /** The note representing a secret. */
  secret?: unknown | Computed<unknown>;
  /** A one sentence description of this note. */
  shortDescription?: string | Computed<string>;
  /** FileNote represents an SPDX File Information section: https://spdx.github.io/spdx-spec/4-file-information/ */
  spdxFile?: V1beta1ContaineranalysisV1beta1Note_SpdxFile | Computed<V1beta1ContaineranalysisV1beta1Note_SpdxFile>;
  /** PackageInfoNote represents an SPDX Package Information section: https://spdx.github.io/spdx-spec/3-package-information/ */
  spdxPackage?: V1beta1ContaineranalysisV1beta1Note_SpdxPackage | Computed<V1beta1ContaineranalysisV1beta1Note_SpdxPackage>;
  /** RelationshipNote represents an SPDX Relationship section: https://spdx.github.io/spdx-spec/7-relationships-between-SPDX-elements/ */
  spdxRelationship?: V1beta1ContaineranalysisV1beta1Note_SpdxRelationship | Computed<V1beta1ContaineranalysisV1beta1Note_SpdxRelationship>;
  /** Output only. The time this note was last updated. This field can be used as a filter in list requests. */
  updateTime?: string | Computed<string>;
  /** Vulnerability provides metadata about a security vulnerability in a Note. */
  vulnerability?: V1beta1ContaineranalysisV1beta1Note_Vulnerability | Computed<V1beta1ContaineranalysisV1beta1Note_Vulnerability>;
  /** A single VulnerabilityAssessmentNote represents one particular product's vulnerability assessment for one CVE. */
  vulnerabilityAssessment?: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment | Computed<V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment>;
}

export interface V1beta1ContaineranalysisV1beta1NoteAttrs {
  /** AISkillAnalysisNote provides the metadata of an AI-based skill analysis. */
  aiSkillAnalysis: unknown;
  /** Note kind that represents a logical attestation "role" or "authority". For example, an organization might have one `Authority` for "QA" and one for "build". This note is intended to act strictly as a grouping mechanism for the attached occurrences (Attestations). This grouping mechanism also provides a security boundary, since IAM ACLs gate the ability for a principle to attach an occurrence to a given note. It also provides a single point of lookup to find all attached attestation occurrences, even if they don't all live in the same project. */
  attestationAuthority: V1beta1ContaineranalysisV1beta1Note_AttestationAuthority;
  /** Basis describes the base image portion (Note) of the DockerImage relationship. Linked occurrences are derived from this or an equivalent image via: FROM Or an equivalent reference, e.g. a tag of the resource_url. */
  baseImage: V1beta1ContaineranalysisV1beta1Note_BaseImage;
  /** Note holding the version of the provider's builder and the signature of the provenance message in the build details occurrence. */
  build: V1beta1ContaineranalysisV1beta1Note_Build;
  /** Output only. The time this note was created. This field can be used as a filter in list requests. */
  createTime: string;
  /** An artifact that can be deployed in some runtime. */
  deployable: V1beta1ContaineranalysisV1beta1Note_Deployable;
  /** A note that indicates a type of analysis a provider would perform. This note exists in a provider's project. A `Discovery` occurrence is created in a consumer's project at the start of analysis. */
  discovery: V1beta1ContaineranalysisV1beta1Note_Discovery;
  /** Time of expiration for this note. Empty if note does not expire. */
  expirationTime: string;
  /** This contains the fields corresponding to the definition of a software supply chain step in an in-toto layout. This information goes into a Grafeas note. */
  intoto: V1beta1ContaineranalysisV1beta1Note_Intoto;
  /** Output only. The type of analysis. This field can be used as a filter in list requests. */
  kind: string;
  /** A detailed description of this note. */
  longDescription: string;
  /** Output only. The name of the note in the form of `projects/[PROVIDER_ID]/notes/[NOTE_ID]`. */
  name: string;
  /** Package represents a particular package version. */
  package: V1beta1ContaineranalysisV1beta1Note_Package;
  /** Other notes related to this note. */
  relatedNoteNames: string[];
  /** URLs associated with this note. */
  relatedUrl: V1beta1ContaineranalysisV1beta1Note_RelatedUrl[];
  /** DocumentNote represents an SPDX Document Creation Information section: https://spdx.github.io/spdx-spec/2-document-creation-information/ */
  sbom: V1beta1ContaineranalysisV1beta1Note_Sbom;
  /** The note representing an SBOM reference. */
  sbomReference: V1beta1ContaineranalysisV1beta1Note_SbomReference;
  /** The note representing a secret. */
  secret: unknown;
  /** A one sentence description of this note. */
  shortDescription: string;
  /** FileNote represents an SPDX File Information section: https://spdx.github.io/spdx-spec/4-file-information/ */
  spdxFile: V1beta1ContaineranalysisV1beta1Note_SpdxFile;
  /** PackageInfoNote represents an SPDX Package Information section: https://spdx.github.io/spdx-spec/3-package-information/ */
  spdxPackage: V1beta1ContaineranalysisV1beta1Note_SpdxPackage;
  /** RelationshipNote represents an SPDX Relationship section: https://spdx.github.io/spdx-spec/7-relationships-between-SPDX-elements/ */
  spdxRelationship: V1beta1ContaineranalysisV1beta1Note_SpdxRelationship;
  /** Output only. The time this note was last updated. This field can be used as a filter in list requests. */
  updateTime: string;
  /** Vulnerability provides metadata about a security vulnerability in a Note. */
  vulnerability: V1beta1ContaineranalysisV1beta1Note_Vulnerability;
  /** A single VulnerabilityAssessmentNote represents one particular product's vulnerability assessment for one CVE. */
  vulnerabilityAssessment: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessment;
}

export const V1beta1ContaineranalysisV1beta1Note: ResourceBinding<V1beta1ContaineranalysisV1beta1NoteConfig, V1beta1ContaineranalysisV1beta1NoteAttrs> = {
  wireType: "google_containeranalysis_v1beta1_containeranalysis_v1beta1_note",
  fields: {
    aiSkillAnalysis: "ai_skill_analysis",
    attestationAuthority: {
      wireName: "attestation_authority",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_AttestationAuthorityFields,
    },
    baseImage: {
      wireName: "base_image",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_BaseImageFields,
    },
    build: {
      wireName: "build",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_BuildFields,
    },
    createTime: "create_time",
    deployable: {
      wireName: "deployable",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_DeployableFields,
    },
    discovery: {
      wireName: "discovery",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_DiscoveryFields,
    },
    expirationTime: "expiration_time",
    intoto: {
      wireName: "intoto",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_IntotoFields,
    },
    kind: "kind",
    longDescription: "long_description",
    name: "name",
    package: {
      wireName: "package",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_PackageFields,
    },
    relatedNoteNames: "related_note_names",
    relatedUrl: {
      wireName: "related_url",
      kind: "list",
      fields: V1beta1ContaineranalysisV1beta1Note_RelatedUrlFields,
    },
    sbom: {
      wireName: "sbom",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_SbomFields,
    },
    sbomReference: {
      wireName: "sbom_reference",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_SbomReferenceFields,
    },
    secret: "secret",
    shortDescription: "short_description",
    spdxFile: {
      wireName: "spdx_file",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_SpdxFileFields,
    },
    spdxPackage: {
      wireName: "spdx_package",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_SpdxPackageFields,
    },
    spdxRelationship: {
      wireName: "spdx_relationship",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_SpdxRelationshipFields,
    },
    updateTime: "update_time",
    vulnerability: {
      wireName: "vulnerability",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_VulnerabilityFields,
    },
    vulnerabilityAssessment: {
      wireName: "vulnerability_assessment",
      kind: "object",
      fields: V1beta1ContaineranalysisV1beta1Note_VulnerabilityAssessmentFields,
    },
  },
};
