// Code generated by `ubx sdk gen` from google_privateca_privateca_certificate_authority. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PrivatecaCertificateAuthority_AccessUrls {
  /** The URL where this CertificateAuthority's CA certificate is published. This will only be set for CAs that have been activated. */
  caCertificateAccessUrl?: string | Computed<string>;
  /** The URLs where this CertificateAuthority's CRLs are published. This will only be set for CAs that have been activated. */
  crlAccessUrls?: string[] | Computed<string[]>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyId {
  keyId?: string | Computed<string>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_CertFingerprint {
  sha256Hash?: string | Computed<string>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_PublicKey {
  format?: string | Computed<string>;
  key?: string | Computed<string>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId {
  objectIdPath?: number[] | Computed<number[]>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes {
  objectId?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId>;
  type?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence {
  attributes?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes[] | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes[]>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject {
  commonName?: string | Computed<string>;
  countryCode?: string | Computed<string>;
  locality?: string | Computed<string>;
  organization?: string | Computed<string>;
  organizationalUnit?: string | Computed<string>;
  postalCode?: string | Computed<string>;
  province?: string | Computed<string>;
  rdnSequence?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence[] | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence[]>;
  streetAddress?: string | Computed<string>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName_CustomSans {
  critical?: boolean | Computed<boolean>;
  objectId?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId>;
  value?: string | Computed<string>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName {
  customSans?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName_CustomSans[] | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName_CustomSans[]>;
  dnsNames?: string[] | Computed<string[]>;
  emailAddresses?: string[] | Computed<string[]>;
  ipAddresses?: string[] | Computed<string[]>;
  uris?: string[] | Computed<string[]>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription {
  hexSerialNumber?: string | Computed<string>;
  lifetime?: string | Computed<string>;
  notAfterTime?: string | Computed<string>;
  notBeforeTime?: string | Computed<string>;
  subject?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject>;
  subjectAltName?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_CaOptions {
  isCa?: boolean | Computed<boolean>;
  maxIssuerPathLength?: number | Computed<number>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_BaseKeyUsage {
  certSign?: boolean | Computed<boolean>;
  contentCommitment?: boolean | Computed<boolean>;
  crlSign?: boolean | Computed<boolean>;
  dataEncipherment?: boolean | Computed<boolean>;
  decipherOnly?: boolean | Computed<boolean>;
  digitalSignature?: boolean | Computed<boolean>;
  encipherOnly?: boolean | Computed<boolean>;
  keyAgreement?: boolean | Computed<boolean>;
  keyEncipherment?: boolean | Computed<boolean>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_ExtendedKeyUsage {
  clientAuth?: boolean | Computed<boolean>;
  codeSigning?: boolean | Computed<boolean>;
  emailProtection?: boolean | Computed<boolean>;
  ocspSigning?: boolean | Computed<boolean>;
  serverAuth?: boolean | Computed<boolean>;
  timeStamping?: boolean | Computed<boolean>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage {
  baseKeyUsage?: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_BaseKeyUsage | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_BaseKeyUsage>;
  extendedKeyUsage?: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_ExtendedKeyUsage | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_ExtendedKeyUsage>;
  unknownExtendedKeyUsages?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId[] | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId[]>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_NameConstraints {
  critical?: boolean | Computed<boolean>;
  excludedDnsNames?: string[] | Computed<string[]>;
  excludedEmailAddresses?: string[] | Computed<string[]>;
  excludedIpRanges?: string[] | Computed<string[]>;
  excludedUris?: string[] | Computed<string[]>;
  permittedDnsNames?: string[] | Computed<string[]>;
  permittedEmailAddresses?: string[] | Computed<string[]>;
  permittedIpRanges?: string[] | Computed<string[]>;
  permittedUris?: string[] | Computed<string[]>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description {
  additionalExtensions?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName_CustomSans[] | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName_CustomSans[]>;
  aiaOcspServers?: string[] | Computed<string[]>;
  caOptions?: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_CaOptions | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_CaOptions>;
  keyUsage?: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage>;
  nameConstraints?: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_NameConstraints | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_NameConstraints>;
  policyIds?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId[] | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectId[]>;
}

export interface PrivatecaCertificateAuthority_CaCertificateDescriptions {
  aiaIssuingCertificateUrls?: string[] | Computed<string[]>;
  authorityKeyId?: PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyId | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyId>;
  certFingerprint?: PrivatecaCertificateAuthority_CaCertificateDescriptions_CertFingerprint | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_CertFingerprint>;
  crlDistributionPoints?: string[] | Computed<string[]>;
  publicKey?: PrivatecaCertificateAuthority_CaCertificateDescriptions_PublicKey | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_PublicKey>;
  subjectDescription?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription>;
  subjectKeyId?: PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyId | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyId>;
  tbsCertificateDigest?: string | Computed<string>;
  x509Description?: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description>;
}

export interface PrivatecaCertificateAuthority_Config_SubjectConfig {
  /** Subject describes parts of a distinguished name that, in turn, describes the subject of the certificate. */
  subject?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject>;
  /** SubjectAltNames corresponds to a more modern way of listing what the asserted identity is in a certificate (i.e., compared to the "common name" in the distinguished name). */
  subjectAltName?: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName>;
}

export interface PrivatecaCertificateAuthority_Config {
  /** A PublicKey describes a public key. */
  publicKey?: PrivatecaCertificateAuthority_CaCertificateDescriptions_PublicKey | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_PublicKey>;
  /** These values are used to create the distinguished name and subject alternative name fields in an X.509 certificate. */
  subjectConfig?: PrivatecaCertificateAuthority_Config_SubjectConfig | Computed<PrivatecaCertificateAuthority_Config_SubjectConfig>;
  /** A KeyId identifies a specific public key, usually by hashing the public key. */
  subjectKeyId?: PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyId | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyId>;
  /** An X509Parameters is used to describe certain fields of an X.509 certificate, such as the key usage fields, fields specific to CA certificates, certificate policy extensions and custom extensions. */
  x509Config?: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description>;
}

export interface PrivatecaCertificateAuthority_KeySpec {
  /** The algorithm to use for creating a managed Cloud KMS key for a for a simplified experience. All managed keys will be have their ProtectionLevel as `HSM`. */
  algorithm?: string | Computed<string>;
  /** The resource name for an existing Cloud KMS CryptoKeyVersion in the format `projects/* /locations/* /keyRings/* /cryptoKeys/* /cryptoKeyVersions/*`. This option enables full flexibility in the key's capabilities and properties. */
  cloudKmsKeyVersion?: string | Computed<string>;
}

export interface PrivatecaCertificateAuthority_SubordinateConfig_PemIssuerChain {
  /** Required. Expected to be in leaf-to-root order according to RFC 5246. */
  pemCertificates?: string[] | Computed<string[]>;
}

export interface PrivatecaCertificateAuthority_SubordinateConfig {
  /** Required. This can refer to a CertificateAuthority that was used to create a subordinate CertificateAuthority. This field is used for information and usability purposes only. The resource name is in the format `projects/* /locations/* /caPools/* /certificateAuthorities/*`. */
  certificateAuthority?: string | Computed<string>;
  /** This message describes a subordinate CA's issuer certificate chain. This wrapper exists for compatibility reasons. */
  pemIssuerChain?: PrivatecaCertificateAuthority_SubordinateConfig_PemIssuerChain | Computed<PrivatecaCertificateAuthority_SubordinateConfig_PemIssuerChain>;
}

export interface PrivatecaCertificateAuthority_UserDefinedAccessUrls {
  /** Optional. A list of URLs where the issuer CA certificate may be downloaded, which appears in the "Authority Information Access" extension in the certificate. If specified, the default Cloud Storage URLs will be omitted. */
  aiaIssuingCertificateUrls?: string[] | Computed<string[]>;
  /** Optional. A list of URLs where to obtain CRL information, i.e. the DistributionPoint.fullName described by https://tools.ietf.org/html/rfc5280#section-4.2.1.13. If specified, the default Cloud Storage URLs will be omitted. */
  crlAccessUrls?: string[] | Computed<string[]>;
}

const PrivatecaCertificateAuthority_AccessUrlsFields: FieldMap = {
  caCertificateAccessUrl: "ca_certificate_access_url",
  crlAccessUrls: "crl_access_urls",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyIdFields: FieldMap = {
  keyId: "key_id",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_CertFingerprintFields: FieldMap = {
  sha256Hash: "sha256_hash",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_PublicKeyFields: FieldMap = {
  format: "format",
  key: "key",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectIdFields: FieldMap = {
  objectIdPath: "object_id_path",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_AttributesFields: FieldMap = {
  objectId: {
    wireName: "object_id",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectIdFields,
  },
  type: "type",
  value: "value",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequenceFields: FieldMap = {
  attributes: {
    wireName: "attributes",
    kind: "list",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_AttributesFields,
  },
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectFields: FieldMap = {
  commonName: "common_name",
  countryCode: "country_code",
  locality: "locality",
  organization: "organization",
  organizationalUnit: "organizational_unit",
  postalCode: "postal_code",
  province: "province",
  rdnSequence: {
    wireName: "rdn_sequence",
    kind: "list",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequenceFields,
  },
  streetAddress: "street_address",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName_CustomSansFields: FieldMap = {
  critical: "critical",
  objectId: {
    wireName: "object_id",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectIdFields,
  },
  value: "value",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltNameFields: FieldMap = {
  customSans: {
    wireName: "custom_sans",
    kind: "list",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName_CustomSansFields,
  },
  dnsNames: "dns_names",
  emailAddresses: "email_addresses",
  ipAddresses: "ip_addresses",
  uris: "uris",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescriptionFields: FieldMap = {
  hexSerialNumber: "hex_serial_number",
  lifetime: "lifetime",
  notAfterTime: "not_after_time",
  notBeforeTime: "not_before_time",
  subject: {
    wireName: "subject",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectFields,
  },
  subjectAltName: {
    wireName: "subject_alt_name",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltNameFields,
  },
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_CaOptionsFields: FieldMap = {
  isCa: "is_ca",
  maxIssuerPathLength: "max_issuer_path_length",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_BaseKeyUsageFields: FieldMap = {
  certSign: "cert_sign",
  contentCommitment: "content_commitment",
  crlSign: "crl_sign",
  dataEncipherment: "data_encipherment",
  decipherOnly: "decipher_only",
  digitalSignature: "digital_signature",
  encipherOnly: "encipher_only",
  keyAgreement: "key_agreement",
  keyEncipherment: "key_encipherment",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_ExtendedKeyUsageFields: FieldMap = {
  clientAuth: "client_auth",
  codeSigning: "code_signing",
  emailProtection: "email_protection",
  ocspSigning: "ocsp_signing",
  serverAuth: "server_auth",
  timeStamping: "time_stamping",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsageFields: FieldMap = {
  baseKeyUsage: {
    wireName: "base_key_usage",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_BaseKeyUsageFields,
  },
  extendedKeyUsage: {
    wireName: "extended_key_usage",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsage_ExtendedKeyUsageFields,
  },
  unknownExtendedKeyUsages: {
    wireName: "unknown_extended_key_usages",
    kind: "list",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectIdFields,
  },
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_NameConstraintsFields: FieldMap = {
  critical: "critical",
  excludedDnsNames: "excluded_dns_names",
  excludedEmailAddresses: "excluded_email_addresses",
  excludedIpRanges: "excluded_ip_ranges",
  excludedUris: "excluded_uris",
  permittedDnsNames: "permitted_dns_names",
  permittedEmailAddresses: "permitted_email_addresses",
  permittedIpRanges: "permitted_ip_ranges",
  permittedUris: "permitted_uris",
};

const PrivatecaCertificateAuthority_CaCertificateDescriptions_X509DescriptionFields: FieldMap = {
  additionalExtensions: {
    wireName: "additional_extensions",
    kind: "list",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltName_CustomSansFields,
  },
  aiaOcspServers: "aia_ocsp_servers",
  caOptions: {
    wireName: "ca_options",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_CaOptionsFields,
  },
  keyUsage: {
    wireName: "key_usage",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_KeyUsageFields,
  },
  nameConstraints: {
    wireName: "name_constraints",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509Description_NameConstraintsFields,
  },
  policyIds: {
    wireName: "policy_ids",
    kind: "list",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_Subject_RdnSequence_Attributes_ObjectIdFields,
  },
};

const PrivatecaCertificateAuthority_CaCertificateDescriptionsFields: FieldMap = {
  aiaIssuingCertificateUrls: "aia_issuing_certificate_urls",
  authorityKeyId: {
    wireName: "authority_key_id",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyIdFields,
  },
  certFingerprint: {
    wireName: "cert_fingerprint",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_CertFingerprintFields,
  },
  crlDistributionPoints: "crl_distribution_points",
  publicKey: {
    wireName: "public_key",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_PublicKeyFields,
  },
  subjectDescription: {
    wireName: "subject_description",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescriptionFields,
  },
  subjectKeyId: {
    wireName: "subject_key_id",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyIdFields,
  },
  tbsCertificateDigest: "tbs_certificate_digest",
  x509Description: {
    wireName: "x509_description",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509DescriptionFields,
  },
};

const PrivatecaCertificateAuthority_Config_SubjectConfigFields: FieldMap = {
  subject: {
    wireName: "subject",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectFields,
  },
  subjectAltName: {
    wireName: "subject_alt_name",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_SubjectDescription_SubjectAltNameFields,
  },
};

const PrivatecaCertificateAuthority_ConfigFields: FieldMap = {
  publicKey: {
    wireName: "public_key",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_PublicKeyFields,
  },
  subjectConfig: {
    wireName: "subject_config",
    kind: "object",
    fields: PrivatecaCertificateAuthority_Config_SubjectConfigFields,
  },
  subjectKeyId: {
    wireName: "subject_key_id",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_AuthorityKeyIdFields,
  },
  x509Config: {
    wireName: "x509_config",
    kind: "object",
    fields: PrivatecaCertificateAuthority_CaCertificateDescriptions_X509DescriptionFields,
  },
};

const PrivatecaCertificateAuthority_KeySpecFields: FieldMap = {
  algorithm: "algorithm",
  cloudKmsKeyVersion: "cloud_kms_key_version",
};

const PrivatecaCertificateAuthority_SubordinateConfig_PemIssuerChainFields: FieldMap = {
  pemCertificates: "pem_certificates",
};

const PrivatecaCertificateAuthority_SubordinateConfigFields: FieldMap = {
  certificateAuthority: "certificate_authority",
  pemIssuerChain: {
    wireName: "pem_issuer_chain",
    kind: "object",
    fields: PrivatecaCertificateAuthority_SubordinateConfig_PemIssuerChainFields,
  },
};

const PrivatecaCertificateAuthority_UserDefinedAccessUrlsFields: FieldMap = {
  aiaIssuingCertificateUrls: "aia_issuing_certificate_urls",
  crlAccessUrls: "crl_access_urls",
};

export interface PrivatecaCertificateAuthorityConfig {
  /** URLs where a CertificateAuthority will publish content. */
  accessUrls?: PrivatecaCertificateAuthority_AccessUrls | Computed<PrivatecaCertificateAuthority_AccessUrls>;
  /** Output only. A structured description of this CertificateAuthority's CA certificate and its issuers. Ordered as self-to-root. */
  caCertificateDescriptions?: PrivatecaCertificateAuthority_CaCertificateDescriptions[] | Computed<PrivatecaCertificateAuthority_CaCertificateDescriptions[]>;
  /** A CertificateConfig describes an X.509 certificate or CSR that is to be created, as an alternative to using ASN.1. */
  config?: PrivatecaCertificateAuthority_Config | Computed<PrivatecaCertificateAuthority_Config>;
  /** Output only. The time at which this CertificateAuthority was created. */
  createTime?: string | Computed<string>;
  /** Output only. The time at which this CertificateAuthority was soft deleted, if it is in the DELETED state. */
  deleteTime?: string | Computed<string>;
  /** Output only. The time at which this CertificateAuthority will be permanently purged, if it is in the DELETED state. */
  expireTime?: string | Computed<string>;
  /** Immutable. The name of a Cloud Storage bucket where this CertificateAuthority will publish content, such as the CA certificate and CRLs. This must be a bucket name, without any prefixes (such as `gs://`) or suffixes (such as `.googleapis.com`). For example, to use a bucket named `my-bucket`, you would simply specify `my-bucket`. If not specified, a managed bucket will be created. */
  gcsBucket?: string | Computed<string>;
  /** A Cloud KMS key configuration that a CertificateAuthority will use. */
  keySpec?: PrivatecaCertificateAuthority_KeySpec | Computed<PrivatecaCertificateAuthority_KeySpec>;
  /** Optional. Labels with user-defined metadata. */
  labels?: Record<string, string> | Computed<Record<string, string>>;
  /** Required. Immutable. The desired lifetime of the CA certificate. Used to create the "not_before_time" and "not_after_time" fields inside an X.509 certificate. */
  lifetime?: string | Computed<string>;
  /** Identifier. The resource name for this CertificateAuthority in the format `projects/* /locations/* /caPools/* /certificateAuthorities/*`. */
  name?: string | Computed<string>;
  /** Output only. This CertificateAuthority's certificate chain, including the current CertificateAuthority's certificate. Ordered such that the root issuer is the final element (consistent with RFC 5246). For a self-signed CA, this will only list the current CertificateAuthority's certificate. */
  pemCaCertificates?: string[] | Computed<string[]>;
  /** Output only. Reserved for future use. */
  satisfiesPzi?: boolean | Computed<boolean>;
  /** Output only. Reserved for future use. */
  satisfiesPzs?: boolean | Computed<boolean>;
  /** Output only. The State for this CertificateAuthority. */
  state?: string | Computed<string>;
  /** Describes a subordinate CA's issuers. This is either a resource name to a known issuing CertificateAuthority, or a PEM issuer certificate chain. */
  subordinateConfig?: PrivatecaCertificateAuthority_SubordinateConfig | Computed<PrivatecaCertificateAuthority_SubordinateConfig>;
  /** Output only. The CaPool.Tier of the CaPool that includes this CertificateAuthority. */
  tier?: string | Computed<string>;
  /** Required. Immutable. The Type of this CertificateAuthority. */
  type?: string | Computed<string>;
  /** Output only. The time at which this CertificateAuthority was last updated. */
  updateTime?: string | Computed<string>;
  /** User-defined URLs for accessing content published by this CertificateAuthority. */
  userDefinedAccessUrls?: PrivatecaCertificateAuthority_UserDefinedAccessUrls | Computed<PrivatecaCertificateAuthority_UserDefinedAccessUrls>;
}

export interface PrivatecaCertificateAuthorityAttrs {
  /** URLs where a CertificateAuthority will publish content. */
  accessUrls: PrivatecaCertificateAuthority_AccessUrls;
  /** Output only. A structured description of this CertificateAuthority's CA certificate and its issuers. Ordered as self-to-root. */
  caCertificateDescriptions: PrivatecaCertificateAuthority_CaCertificateDescriptions[];
  /** A CertificateConfig describes an X.509 certificate or CSR that is to be created, as an alternative to using ASN.1. */
  config: PrivatecaCertificateAuthority_Config;
  /** Output only. The time at which this CertificateAuthority was created. */
  createTime: string;
  /** Output only. The time at which this CertificateAuthority was soft deleted, if it is in the DELETED state. */
  deleteTime: string;
  /** Output only. The time at which this CertificateAuthority will be permanently purged, if it is in the DELETED state. */
  expireTime: string;
  /** Immutable. The name of a Cloud Storage bucket where this CertificateAuthority will publish content, such as the CA certificate and CRLs. This must be a bucket name, without any prefixes (such as `gs://`) or suffixes (such as `.googleapis.com`). For example, to use a bucket named `my-bucket`, you would simply specify `my-bucket`. If not specified, a managed bucket will be created. */
  gcsBucket: string;
  /** A Cloud KMS key configuration that a CertificateAuthority will use. */
  keySpec: PrivatecaCertificateAuthority_KeySpec;
  /** Optional. Labels with user-defined metadata. */
  labels: Record<string, string>;
  /** Required. Immutable. The desired lifetime of the CA certificate. Used to create the "not_before_time" and "not_after_time" fields inside an X.509 certificate. */
  lifetime: string;
  /** Identifier. The resource name for this CertificateAuthority in the format `projects/* /locations/* /caPools/* /certificateAuthorities/*`. */
  name: string;
  /** Output only. This CertificateAuthority's certificate chain, including the current CertificateAuthority's certificate. Ordered such that the root issuer is the final element (consistent with RFC 5246). For a self-signed CA, this will only list the current CertificateAuthority's certificate. */
  pemCaCertificates: string[];
  /** Output only. Reserved for future use. */
  satisfiesPzi: boolean;
  /** Output only. Reserved for future use. */
  satisfiesPzs: boolean;
  /** Output only. The State for this CertificateAuthority. */
  state: string;
  /** Describes a subordinate CA's issuers. This is either a resource name to a known issuing CertificateAuthority, or a PEM issuer certificate chain. */
  subordinateConfig: PrivatecaCertificateAuthority_SubordinateConfig;
  /** Output only. The CaPool.Tier of the CaPool that includes this CertificateAuthority. */
  tier: string;
  /** Required. Immutable. The Type of this CertificateAuthority. */
  type: string;
  /** Output only. The time at which this CertificateAuthority was last updated. */
  updateTime: string;
  /** User-defined URLs for accessing content published by this CertificateAuthority. */
  userDefinedAccessUrls: PrivatecaCertificateAuthority_UserDefinedAccessUrls;
}

export const PrivatecaCertificateAuthority: ResourceBinding<PrivatecaCertificateAuthorityConfig, PrivatecaCertificateAuthorityAttrs> = {
  wireType: "google_privateca_privateca_certificate_authority",
  fields: {
    accessUrls: {
      wireName: "access_urls",
      kind: "object",
      fields: PrivatecaCertificateAuthority_AccessUrlsFields,
    },
    caCertificateDescriptions: {
      wireName: "ca_certificate_descriptions",
      kind: "list",
      fields: PrivatecaCertificateAuthority_CaCertificateDescriptionsFields,
    },
    config: {
      wireName: "config",
      kind: "object",
      fields: PrivatecaCertificateAuthority_ConfigFields,
    },
    createTime: "create_time",
    deleteTime: "delete_time",
    expireTime: "expire_time",
    gcsBucket: "gcs_bucket",
    keySpec: {
      wireName: "key_spec",
      kind: "object",
      fields: PrivatecaCertificateAuthority_KeySpecFields,
    },
    labels: "labels",
    lifetime: "lifetime",
    name: "name",
    pemCaCertificates: "pem_ca_certificates",
    satisfiesPzi: "satisfies_pzi",
    satisfiesPzs: "satisfies_pzs",
    state: "state",
    subordinateConfig: {
      wireName: "subordinate_config",
      kind: "object",
      fields: PrivatecaCertificateAuthority_SubordinateConfigFields,
    },
    tier: "tier",
    type: "type",
    updateTime: "update_time",
    userDefinedAccessUrls: {
      wireName: "user_defined_access_urls",
      kind: "object",
      fields: PrivatecaCertificateAuthority_UserDefinedAccessUrlsFields,
    },
  },
};
