// Code generated by `ubx sdk gen` from google_sqladmin_v1beta4_sqladmin_v1beta4_ssl_cert. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface V1beta4SqladminV1beta4SslCertConfig {
  /** User supplied name. Must be a distinct name from the other certificates for this instance. */
  commonName?: string | Computed<string>;
}

export interface V1beta4SqladminV1beta4SslCertAttrs {
  /** PEM representation. */
  cert: string;
  /** Serial number, as extracted from the certificate. */
  certSerialNumber: string;
  /** User supplied name. Must be a distinct name from the other certificates for this instance. */
  commonName: string;
  /** The time when the certificate was created in [RFC 3339](https://tools.ietf.org/html/rfc3339) format, for example `2012-11-15T16:19:00.094Z`. */
  createTime: string;
  /** The time when the certificate expires in [RFC 3339](https://tools.ietf.org/html/rfc3339) format, for example `2012-11-15T16:19:00.094Z`. */
  expirationTime: string;
  /** Name of the database instance. */
  instance: string;
  /** This is always `sql#sslCert`. */
  kind: string;
  /** The URI of this resource. */
  selfLink: string;
  /** Sha1 Fingerprint. */
  sha1Fingerprint: string;
}

export const V1beta4SqladminV1beta4SslCert: ResourceBinding<V1beta4SqladminV1beta4SslCertConfig, V1beta4SqladminV1beta4SslCertAttrs> = {
  wireType: "google_sqladmin_v1beta4_sqladmin_v1beta4_ssl_cert",
  fields: {
    commonName: "common_name",
  },
};
