// Code generated by `ubx sdk gen` from google_documentai_processor_version. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ProcessorVersion_DeprecationInfo {
  /** The time at which this processor version will be deprecated. */
  deprecationTime?: string | Computed<string>;
  /** If set, the processor version that will be used as a replacement. */
  replacementProcessorVersion?: string | Computed<string>;
}

export interface ProcessorVersion_DocumentSchema_EntityTypes_EnumValues {
  values?: string[] | Computed<string[]>;
}

export interface ProcessorVersion_DocumentSchema_EntityTypes_Properties {
  displayName?: string | Computed<string>;
  method?: string | Computed<string>;
  name?: string | Computed<string>;
  occurrenceType?: string | Computed<string>;
  valueType?: string | Computed<string>;
}

export interface ProcessorVersion_DocumentSchema_EntityTypes {
  baseTypes?: string[] | Computed<string[]>;
  displayName?: string | Computed<string>;
  enumValues?: ProcessorVersion_DocumentSchema_EntityTypes_EnumValues | Computed<ProcessorVersion_DocumentSchema_EntityTypes_EnumValues>;
  name?: string | Computed<string>;
  properties?: ProcessorVersion_DocumentSchema_EntityTypes_Properties[] | Computed<ProcessorVersion_DocumentSchema_EntityTypes_Properties[]>;
}

export interface ProcessorVersion_DocumentSchema_Metadata {
  /** If true, on a given page, there can be multiple `document` annotations covering it. */
  documentAllowMultipleLabels?: boolean | Computed<boolean>;
  /** If true, a `document` entity type can be applied to subdocument (splitting). Otherwise, it can only be applied to the entire document (classification). */
  documentSplitter?: boolean | Computed<boolean>;
  /** If set, all the nested entities must be prefixed with the parents. */
  prefixedNamingOnProperties?: boolean | Computed<boolean>;
  /** If set, this will skip the naming format validation in the schema. So the string values in `DocumentSchema.EntityType.name` and `DocumentSchema.EntityType.Property.name` will not be checked. */
  skipNamingValidation?: boolean | Computed<boolean>;
}

export interface ProcessorVersion_DocumentSchema {
  /** Description of the schema. */
  description?: string | Computed<string>;
  /** Display name to show users. */
  displayName?: string | Computed<string>;
  /** Optional. Document-level prompt provided by the user. This custom text is injected into the AI model's prompt to provide extra, document-wide guidance for processing. */
  documentPrompt?: string | Computed<string>;
  /** Entity types of the schema. */
  entityTypes?: ProcessorVersion_DocumentSchema_EntityTypes[] | Computed<ProcessorVersion_DocumentSchema_EntityTypes[]>;
  /** Metadata for global schema behavior. */
  metadata?: ProcessorVersion_DocumentSchema_Metadata | Computed<ProcessorVersion_DocumentSchema_Metadata>;
}

export interface ProcessorVersion_GenAiModelInfo_CustomGenAiModelInfo {
  /** The base processor version ID for the custom model. */
  baseProcessorVersionId?: string | Computed<string>;
  /** The type of custom model created by the user. */
  customModelType?: string | Computed<string>;
}

export interface ProcessorVersion_GenAiModelInfo_FoundationGenAiModelInfo {
  /** Whether fine tuning is allowed for this base processor version. */
  finetuningAllowed?: boolean | Computed<boolean>;
  /** The minimum number of labeled documents in the training dataset required for fine tuning. */
  minTrainLabeledDocuments?: number | Computed<number>;
}

export interface ProcessorVersion_GenAiModelInfo {
  /** Information for a custom Generative AI model created by the user. These are created with `Create New Version` in either the `Call foundation model` or `Fine tuning` tabs. */
  customGenAiModelInfo?: ProcessorVersion_GenAiModelInfo_CustomGenAiModelInfo | Computed<ProcessorVersion_GenAiModelInfo_CustomGenAiModelInfo>;
  /** Information for a pretrained Google-managed foundation model. */
  foundationGenAiModelInfo?: ProcessorVersion_GenAiModelInfo_FoundationGenAiModelInfo | Computed<ProcessorVersion_GenAiModelInfo_FoundationGenAiModelInfo>;
}

export interface ProcessorVersion_LatestEvaluation_AggregateMetrics {
  /** The calculated F1 score. */
  f1Score?: number | Computed<number>;
  /** The amount of false negatives. */
  falseNegativesCount?: number | Computed<number>;
  /** The amount of false positives. */
  falsePositivesCount?: number | Computed<number>;
  /** The amount of documents with a ground truth occurrence. */
  groundTruthDocumentCount?: number | Computed<number>;
  /** The amount of occurrences in ground truth documents. */
  groundTruthOccurrencesCount?: number | Computed<number>;
  /** The calculated precision. */
  precision?: number | Computed<number>;
  /** The amount of documents with a predicted occurrence. */
  predictedDocumentCount?: number | Computed<number>;
  /** The amount of occurrences in predicted documents. */
  predictedOccurrencesCount?: number | Computed<number>;
  /** The calculated recall. */
  recall?: number | Computed<number>;
  /** The amount of documents that had an occurrence of this label. */
  totalDocumentsCount?: number | Computed<number>;
  /** The amount of true positives. */
  truePositivesCount?: number | Computed<number>;
}

export interface ProcessorVersion_LatestEvaluation {
  /** Evaluation metrics, either in aggregate or about a specific entity. */
  aggregateMetrics?: ProcessorVersion_LatestEvaluation_AggregateMetrics | Computed<ProcessorVersion_LatestEvaluation_AggregateMetrics>;
  /** Evaluation metrics, either in aggregate or about a specific entity. */
  aggregateMetricsExact?: ProcessorVersion_LatestEvaluation_AggregateMetrics | Computed<ProcessorVersion_LatestEvaluation_AggregateMetrics>;
  /** The resource name of the evaluation. */
  evaluation?: string | Computed<string>;
  /** The resource name of the Long Running Operation for the evaluation. */
  operation?: string | Computed<string>;
}

export interface ProcessorVersionConfig {
  name: string | Computed<string>;
}

export interface ProcessorVersionAttrs {
  /** Output only. The time the processor version was created. */
  createTime: string;
  /** Information about the upcoming deprecation of this processor version. */
  deprecationInfo: ProcessorVersion_DeprecationInfo;
  /** The display name of the processor version. */
  displayName: string;
  /** The schema defines the output of the processed document by a processor. */
  documentSchema: ProcessorVersion_DocumentSchema;
  /** Information about Generative AI model-based processor versions. */
  genAiModelInfo: ProcessorVersion_GenAiModelInfo;
  /** Output only. Denotes that this `ProcessorVersion` is managed by Google. */
  googleManaged: boolean;
  /** Output only. The KMS key name used for encryption. */
  kmsKeyName: string;
  /** Output only. The KMS key version with which data is encrypted. */
  kmsKeyVersionName: string;
  /** Gives a short summary of an evaluation, and links to the evaluation itself. */
  latestEvaluation: ProcessorVersion_LatestEvaluation;
  /** Output only. The model type of this processor version. */
  modelType: string;
  name: string;
  /** Output only. Reserved for future use. */
  satisfiesPzi: boolean;
  /** Output only. Reserved for future use. */
  satisfiesPzs: boolean;
  /** Output only. The state of the processor version. */
  state: string;
}

export const ProcessorVersion: DataSourceBinding<ProcessorVersionConfig, ProcessorVersionAttrs> = {
  wireType: "google_documentai_processor_version",
  fields: {
    name: "name",
  },
};
